- pkg/qemu/qemu.go
Thanks to @Tarik02 for suggestion.
Close #25
> qemu: -boot splash-time=0,menu=on

- pkg/cidata/user-data.TEMPLATE
https://github.com/containerd/nerdctl/releases/tag/v0.8.3
> update nerdctl to v0.8.3

- cmd/limactl/shell.go
- examples/k3s.yaml
- pkg/cidata/user-data.TEMPLATE
- pkg/limayaml/default.TEMPLATE.yaml
> Follow-up to "Implement system and user provisioning scripts" (#38)

- pkg/cidata/user-data.TEMPLATE
- pkg/hostagent/mount.go
- pkg/hostagent/requirements.go
Fix #5 , by running sshfs with `-o allow_root`
> Fix "Mounted filesystems not accessible by root"

- .github/workflows/test.yml
- cmd/limactl/main.go
- cmd/limactl/start.go
- cmd/limactl/validate.go
```console
$ limactl validate examples/*.yaml
INFO[0000] "examples/default.yaml": OK                  
INFO[0000] "examples/fedora.yaml": OK                   
INFO[0000] "examples/k3s.yaml": OK                      
INFO[0000] "examples/ubuntu.yaml": OK   
```
> add `limactl validate FILE.yaml [FILE.yaml, ...]`

- hack/test-example.sh
Could/should probably be extended to check that containers and images persist across reboots too, but this is good enough for me (for now).
> Check that files in the guest home directory persist across restarts

- .github/workflows/test.yml
- README.md
Thanks to @jandubois for the info https://github.com/AkihiroSuda/lima/pull/56#discussion_r653716731
> brew pin libslirp

- cmd/limactl/start.go
- docs/internal.md
- pkg/store/filenames/filenames.go
Follow-up to #59 
cc @jandubois
> Follow-up to "Implement LIMA_HOME to override ~/.lima location"

- cmd/limactl/start.go
- docs/internal.md
- pkg/osutil/osutil_linux.go
- pkg/osutil/osutil_others.go
- pkg/sshutil/sshutil.go
- pkg/store/filenames/filenames.go
#62 
Forgot to push my local change before merging :(
> Follow-up to "Follow-up to \"Implement LIMA_HOME to override ~/.lima location\""

- cmd/lima
- pkg/cidata/cidata.go
https://github.com/containerd/nerdctl/releases/tag/v0.9.0
> nerdctl: update to v0.9.0

- hack/lima-and-qemu.pl
Such a big PR for a single-character change 😄
> Check for directory with -d and not -f

- examples/debian.yaml
> examples: update debian.yaml

- pkg/sshutil/sshutil.go
> sshutil: specify username explicitly

- go.mod
- go.sum
- pkg/lockutil/lockutil.go
- pkg/sshutil/sshutil.go
> sshutil: lock ${LIMA_HOME}/_config

- .cirrus.yml
- examples/archlinux.yaml
- examples/opensuse.yaml
- hack/test-example.sh
- pkg/cidata/cidata.go
https://github.com/containerd/nerdctl/releases/tag/v0.10.0
Fix #79
> nerdctl: update to v0.10.0 + fix CI stuff

- pkg/cidata/cidata.go
https://github.com/containerd/nerdctl/releases/tag/v0.11.0
> nerdctl: update to v0.11.0

- pkg/store/instance.go
And delete the PID file if it is not. Still vulnerable to the PID being reused before it is being checked.
Fixes https://github.com/rancher-sandbox/rancher-desktop/issues/456#issuecomment-894551102
> Verify that the process specified in a PID file is still running

- pkg/cidata/cidata.go
https://github.com/containerd/nerdctl/releases/tag/v0.11.1
> nerdctl: update to v0.11.1

- cmd/lima-guestagent/daemon_linux.go
- cmd/limactl/copy.go
- cmd/limactl/delete.go
- cmd/limactl/hostagent.go
- cmd/limactl/list.go
- cmd/limactl/shell.go
- cmd/limactl/start.go
- cmd/limactl/stop.go
- cmd/limactl/validate.go
- go.mod
- pkg/cidata/cidata.go
- pkg/cidata/template.go
- pkg/downloader/downloader.go
- pkg/guestagent/procnettcp/procnettcp.go
- pkg/guestagent/procnettcp/procnettcp_linux.go
- pkg/hostagent/hostagent.go
- pkg/hostagent/mount.go
- pkg/hostagent/port.go
- pkg/hostagent/requirements.go
- pkg/httpclientutil/httpclientutil.go
- pkg/limayaml/validate.go
- pkg/localpathutil/localpathutil.go
- pkg/lockutil/lockutil.go
- pkg/qemu/qemu.go
- pkg/sshutil/sshutil.go
- pkg/start/start.go
- pkg/store/store.go
Used https://github.com/AkihiroSuda/go-wrap-to-percent-w for converting `errors.Wrap` to `%w`
> remove direct dependency on github.com/pkg/errors

- pkg/limayaml/validate.go
- pkg/qemu/qemu.go
- pkg/start/start.go
> `vde: defer vnl validation until starting qemu` + `pkg/start: exit when hostagent process exited`

- pkg/osutil/user.go
> Only fallback to "lima" user when host user is invalid

- README.md
Thanks to @zchee for the info
https://twitter.com/_zchee_/status/1435153687756693509
> README.md: update ARM installation steps (`brew install simnalamburt/x/qemu-hvf`)

- README.md
To save some time for Manual Installation/ ARM Mac users.
> Provide an easier binary manual installation example command

- README.md
cc @jandubois @mook-as @abiosoft
> README.md: add adopters list (Rancher Desktop, Colima)

- hack/lima-and-qemu.pl
It is kind-of heavy-handed by hardcoding the 2 dependencies, but extending the opensnoop processing just to deal with `/opt/vde` would be rather convoluted (it would only cover the dylib; the executables have to be added manually anyways).
Installation will have to move the `vde` directory from the tarball into a location only `root` can write to.
> Add `/opt/vde/bin/vde_vmnet` and prerequites to lima-and-qemu tarball

- README.md
- Add link to [lima-xbar-plugin](https://github.com/unixorn/lima-xbar-plugin)
- Sort adopters list
Closes https://github.com/lima-vm/lima/issues/253
> Add link to lima xbar plugin

- cmd/limactl/copy.go
Hi all,
simple pr to add the functionality to copy files / folder recursive.
See issue #259
Regards
Tobi
> [NEW] add recursive copy

- cmd/limactl/start.go
Follow-up to #276 
- start: check YAML file size
- start: support file:// URL
> Follow-up to `Implement starting instances from a HTTP URL ` (#276)

- pkg/cidata/cidata.go
https://github.com/containerd/nerdctl/releases/tag/v0.12.0
Signed-off-by: JACQUES Francois <Francois.JACQUES@murex.com>
> nerdctl: update to v0.12.0

- pkg/cidata/cidata.TEMPLATE.d/boot.sh
- pkg/cidata/cidata.TEMPLATE.d/boot/25-guestagent-base.sh
When talking about the init and not the distro
(there are some other places with apk and such)
Otherwise it will hang forever, waiting for systemd
> Check for openrc-init instead of alpine-release

- examples/docker.yaml
- examples/podman.yaml
> Follow-up to "Implement unix socket forwarding"

- cmd/limactl/debug.go
- cmd/limactl/main.go
- pkg/hostagent/dns/dns.go
- pkg/hostagent/hostagent.go
> pkg/hostagent/dns: truncate messages

- examples/k8s.yaml
Need to also add certificate for 127.0.0.1
Closes #377
> Add external kubeconfig to the k8s example

- cmd/limactl/list.go
As mentioned in https://github.com/lima-vm/lima/pull/324#issuecomment-942611305
`limactl list default`
> Add possibility to list particular instances

- README.md
> docs: show --tty usage

- examples/faasd.yaml
Add an example to deploy faasd
fixes #440
> add example to deploy faasd

- .github/workflows/test.yml
Includes https://github.com/virtualsquare/vde-2/pull/35
> Bump vde-2 to include ENOBUFS fix for vde_switch

- hack/test-example.sh
- pkg/limayaml/defaults.go
https://github.com/containerd/nerdctl/releases/tag/v0.15.0
> nerdctl: update to v0.15.0

- pkg/hostagent/mount.go
- pkg/limayaml/defaults.go
- pkg/limayaml/defaults_test.go
- pkg/limayaml/limayaml.go
Signed-off-by: Jason W. Ehrlich <jwehrlich@outlook.com>
> Refactor Mount#Writable to be boolean pointer

- Makefile
I only noticed that #507 was not indented correctly after I already merged it. :(
> Fix indentation

- examples/debian.yaml
Signed-off-by: KOSHIKAWA Kenichi <reishoku.misc ~at~ pm.me>
> examples/debian.yaml: bump debian version

- .cirrus.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .golangci.yml
- .yamllint
- examples/archlinux.yaml
- examples/debian.yaml
- examples/docker.yaml
- examples/fedora.yaml
- examples/k8s.yaml
- examples/nomad.yaml
- examples/opensuse.yaml
- examples/podman.yaml
- examples/rocky.yaml
- examples/singularity.yaml
- examples/ubuntu.yaml
- examples/vmnet.yaml
- pkg/limayaml/default.yaml
As promised in https://github.com/lima-vm/lima/pull/376#issuecomment-971313664
> Don't indent sequences in YAML files

- README.md
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Fixes #552
> docs(README): mention nerdctl.lima shortcut

- pkg/cidata/cidata.TEMPLATE.d/boot/30-install-packages.sh
~~maybe fix https://github.com/lima-vm/lima/issues/431~~
Not the main reason, but useful.
> dont upgrade pkg when install sshf

- examples/README.md
- examples/ubuntu-lts.yaml
This PR includes:
- Example YAML file: Bringing Ubuntu LTS (20.04 focal) to Lima.
I want to add Ubuntu LTS YAML file to Lima because this change will make creation of Ubuntu LTS VM/container more convenient.
-----------------------
Signed-off-by: KOSHIKAWA Kenichi <reishoku.misc ~@~ pm.me>
> examples: Bring Ubuntu LTS (20.04 focal) to Lima

- cmd/limactl/edit.go
- cmd/limactl/start.go
> editor: print a warning when override.yaml exists

- pkg/qemu/qemu.go
THis PR contains:
- Fix for comment in code.
---------------------
Signed-off-by: KOSHIKAWA Kenichi <reishoku.misc ~~@~~ pm.me>
> Fix comment

- README.ja.md
This PR contains:
- fix for Pull Request #621 (link in README.ja.md is broken)
* https://github.com/lima-vm/lima/pull/621#discussion_r799668328_
----------------------------------------
Signed-off-by: KOSHIKAWA Kenichi <reishoku.misc ~~@~~ pm.me>
> fix for PR #621

- examples/almalinux.yaml
- examples/rocky.yaml
> examples/{almalinux,rocky}.yaml: use Lima v0.8.3 cpuType

- .github/workflows/test.yml
- .shellcheckrc
- hack/common.inc.sh
- hack/test-example.sh
- hack/test-mount-home.sh
- hack/test-upgrade.sh
> CI: add upgrade test

- README.md
Signed-off-by: Ye Sijun <junnplus@gmail.com>
URL copied to the terminal will be escaped.
> Fix curl url

- pkg/qemu/qemu.go
Signed-off-by: Ye Sijun <junnplus@gmail.com>
> Add ovmf candidates for archlinux

- .github/workflows/test.yml
https://github.com/lima-vm/vde_vmnet/compare/v0.5.2...v0.6.0
> CI: use vde_vmnet v0.6.0

- README.md
- cmd/limactl/factory-reset.go
- cmd/limactl/main.go
Signed-off-by: Ye Sijun <junnplus@gmail.com>
Add `limactl factory-reset` command for wiping the data of instance.
> Add factory reset cmd

- examples/buildkit.yaml
I'm highly uncertain if this is correct.
Might need to enforce path inside the VM.
Need input from someone who knows the plumbing here.
#802
> Fix buildkit guestSocket

- pkg/qemu/qemu.go
If nix-darwin (no FHS) is being used to install qemu, but not lima, then figuring out what's going wrong with the firmware can get tricky.
This allows search in `$HOME/.local/share/qemu` for the firmware. It also hints to the user that they could try copying the firmware there.
Signed-off-by: Jonathan Dickinson <jdickinson@cmgx.io>
> feat: look for firmware in $HOME/.local/share/qemu

- pkg/qemu/qemu.go
> Make sure macOS version is in dotted-tri format

- cmd/limactl/debug.go
- pkg/hostagent/dns/dns.go
- pkg/hostagent/dns/dns_test.go
- pkg/hostagent/hostagent.go
This change introduces additional debug lines which makes the debugging process slightly better.
> Allow dns.go to be consumed by external projects 5/5

- pkg/iso9660util/iso9660util.go
The "go-embed" library has hardcoded forward slashes (`/`)
and doesn't like when mixing them with backslashes (`\`).
> Use forward slash for iso9660.Create on windows

- Makefile
- SECURITY.md
Moved to https://github.com/lima-vm/.github/blob/main/SECURITY.md
> SECURITY.md: move to lima-vm/.github repo

- README.md
- docs/talks.md
Signed-off-by: Jan Dubois <jan.dubois@suse.com>
> Add Lima KubeCon 22 EU talk to repo

- examples/README.md
- examples/docker-rootful.yaml
`docker-rootful.yaml` is same as `docker.yaml` but runs `dockerd` as the root user in the VM
> templates: add docker-rootful

- README.md
- https://github.com/cncf/toc/issues/924
> - [X] GitHub: ensure that hat the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
> - [X] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).
> README.md: Lima is now a CNCF Sandbox project

- cmd/limactl/start.go
Fix #1070
Fix e5a79f13f048c8d1e1df84362eb43c4c1f668e63
> Fix segfault (master regression 2022-09-26)

- pkg/hostagent/dns/dns.go
Fixing TruncateReply option passing, fixes issues with oauth2.googleapis.com dns resolution
Signed-off-by: Valery Masiutsin <val.masutin@gmail.com>
> Fixing TruncateReply option passing

- examples/almalinux.yaml
- examples/centos-stream.yaml
- examples/oraclelinux.yaml
- examples/rocky.yaml
> examples: add note that EL8 distros do not work on M1 (EL9 works)

- .github/workflows/test.yml
The site seems currently down (500 Internal Server Error)
> CI: allow broken hyperlinks to https://xbarapp.com

- examples/alpine.yaml
Request in https://github.com/lima-vm/lima/issues/1103#issuecomment-1279996427
> Bump alpine-lime to 0.2.23 to include growpart

- pkg/cidata/cidata.go
- pkg/cidata/cidata_test.go
> Fix the regexp for the localhost proxy match

- pkg/cidata/cidata.TEMPLATE.d/boot/05-persistent-data-volume.sh
Update '05-persistent-data-volume.sh' to find the datadisk, grow partition, and grow filesystem.
The resize will *not* happen when `e2fsck` finds filesystem corruption.
`cloud-init` logs when resize is not needed:
```
+ DATA_DISK=/dev/vdb
+ set +e
+ growpart /dev/vdb 1
NOCHANGE: partition 1 is size 272627679. it cannot be grown
+ e2fsck -f -p /dev/disk/by-label/data-volume
data-volume: 668/8519680 files (0.1% non-contiguous), 683533/34078459 blocks
+ set -e
+ '[' 0 '==' 0 ]
+ resize2fs /dev/disk/by-label/data-volume
resize2fs 1.46.5 (30-Dec-2021)
The filesystem is already 34078459 (4k) blocks long.  Nothing to do!
+ mount -t ext4 /dev/disk/by-label/data-volume /mnt/data
```
`cloud-init` logs when resize is needed:
```
+ DATA_DISK=/dev/vdb
+ set +e
+ growpart /dev/vdb 1
CHANGED: …
```
> Automatically expand filesystem on mounted volumes when they have grown

- docs/mount.md
- docs/vmtype.md
- examples/default.yaml
- examples/experimental/vz.yaml
> vz: update docs

- Makefile
> Makefile: add .NOTPARALLEL

- pkg/networks/gvisor.go
> fix host network resolver issue with alpine

- .github/workflows/test.yml
- Makefile
- pkg/vz/vm_darwin.go
- pkg/vz/vz_driver_darwin.go
- pkg/vz/vz_driver_others.go
> Fix compilation on macOS 10.15

- .github/workflows/test.yml
https://github.com/lima-vm/socket_vmnet/releases/tag/v1.0.0
> CI: update socket_vmnet (1.0.0)

- .github/workflows/test.yml
https://github.com/lima-vm/socket_vmnet/releases/tag/v1.1.0
> CI: update socket_vmnet (1.1.0)

- .github/workflows/release.yml
- .github/workflows/test.yml
- Makefile
> CI: release: use Xcode 14.1 to enable the macOS 13 SDK

- README.md
Signed-off-by: Phil Estes <estesp@amazon.com>
> Add Finch as an adopter of Lima

- cmd/limactl/list.go
For reducing the column width.
This does not affect the JSON output.
> limactl list: "/Users/<USERNAME>/.lima/..." -> "~/.lima/..."

- pkg/limayaml/defaults.go
- pkg/reflectutil/reflectutil.go
- pkg/vz/vz_driver_darwin.go
Signed-off-by: Balaji Vijayakumar <kuttibalaji.v6@gmail.com>
Fixes #1162
> support for validating unknown fields

- pkg/sysprof/sysprof_darwin.go
> system_profiler -> /usr/sbin/system_profiler

- Makefile
Signed-off-by: Hanfeng Qin <hanfengtsin@gmail.com>
> docs: fix diagram path

- website/README.md
- website/index.html
> website: set up https://lima-vm.io/

- examples/almalinux-9.yaml
> templates: almalinux-9: fix 404

- cmd/limactl/inspect.go
- cmd/limactl/list.go
- cmd/limactl/main.go
- pkg/store/instance.go
> add inspect CLI option

- pkg/store/instance.go
- pkg/textutil/textutil.go
- pkg/textutil/textutil_test.go
Fix #1280
A regression in 75594fa33bd73a2cc80a389993c7573b4bf3ec58 (#1249)
> Make sure `limactl list --json` to print line-delimited JSON

- README.ja.md
- README.md
- README.zh.md
Signed-off-by: suyanhanx <suyanhanx@gmail.com>
> docs: add README zh translation and fix some bad links

- MAINTAINERS.md
Anders F Björklund (@afbjorklund) and Balaji Vijayakumar (@balajiv113) have been very actively contributing to the project:
- https://github.com/lima-vm/lima/pulls?q=is%3Apr+author%3Aafbjorklund 
- https://github.com/lima-vm/lima/pulls?q=is%3Apr+author%3Abalajiv113
Thank you and welcome @afbjorklund @balajiv113 !
(Please review and approve this PR)
> MAINTAINERS.md: add afbjorklund and balajiv113

- .github/workflows/release.yml
- .github/workflows/test.yml
Depends on
- https://github.com/golangci/golangci-lint/pull/3414
> CI: update Go (1.20)

- cmd/limactl/list.go
- go.mod
- go.sum
- pkg/store/instance.go
> Remove extra indentation of list help

- pkg/sshutil/sshutil.go
Looks like `x/sys/cpu` lacks support for `darwin/arm64`: https://github.com/golang/sys/blob/v0.5.0/cpu/cpu_arm64.go#L43-L60
Fix #1360
> detectAESAcceleration: workaround for darwin/amd64

- pkg/hostagent/hostagent.go
- pkg/limayaml/defaults.go
> Fix vz crash with video configuration

- README.md
And discourage us of `limactl` with the Rancher Desktop VM.
> Document `rdctl shell` command for Rancher Desktop

- cmd/limactl/start.go
- pkg/limayaml/validate.go
ref: https://github.com/lima-vm/lima/blob/master/docs/experimental.md
> Add warnings for experimental features

- pkg/vz/vm_darwin.go
- pkg/vz/vz_driver_darwin.go
These changes fixes panic that appears even after updating to 3.0.5
Fixes #1381
> Fix panic during stop in vz driver

- pkg/hostagent/dns/dns.go
- pkg/networks/gvisor.go
- pkg/osutil/dns_darwin.go
> Use net.JoinHostPort

- pkg/downloader/downloader.go
> Add progress bar for decompressing

- go.mod
- go.sum
> Update vz to 3.0.6

- pkg/vz/vz_driver_darwin.go
> vz: validate required version before hostagent start

- cmd/limactl/snapshot.go
- docs/experimental.md
> Mark `limactl snapshot` experimental

- docs/vmtype.md
- examples/experimental/vz.yaml
> vz: add a note about kernel v6.2 (used by Ubuntu 23.04, Fedora 38, etc.)

- pkg/vz/vm_darwin.go
Follow-up to PR #1532
Can be added again, with an additional knob in the YAML
> vz: remove audio input

- pkg/networks/config.go
- pkg/networks/config_test.go
> Support for adding user-v2 network by default

- pkg/limayaml/defaults.go
- pkg/vz/vz_driver_darwin.go
> Fix crash in vz driver when Video.Display is not set

- pkg/networks/usernet/client.go
> vz: Fix usernet sshLocalPort check failure for vz driver

- examples/centos-stream-8.yaml
> Add fallback for the centos-stream-8 image too

- cmd/limactl/start.go
- pkg/start/start.go
For:
- https://github.com/lima-vm/lima/discussions/1647
> limactl create: prepare images

- pkg/vz/vz_driver_darwin.go
> Avoid warning about prefix with vz driver

- pkg/networks/usernet/config.go
- pkg/networks/usernet/config_test.go
- pkg/vz/vm_darwin.go
> Fix usernet socket name too long

- .cirrus.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- hack/debug-cache.sh
> CI: debug cache

- cmd/limactl/edit.go
- cmd/limactl/editflags/editflags.go
- cmd/limactl/start.go
- pkg/yqutil/yqutil.go
> limactl start: apply edit flags for existing instances

- examples/k8s.yaml
Bumps "flannel" cni plugin from 1.1.2 to 1.2.0
> Bump k8s flannel version from 0.21.4 to 0.22.1

- Makefile
- cmd/limactl/gendoc.go
- cmd/limactl/main.go
Like man, docsy
Reference: https://github.com/lima-vm/lima/pull/1754#issuecomment-1705219198
> Support for generating cli reference with different output formats

- README.md
The most of the contents were moved to https://lima-vm.io/docs/
> README.md: simplify

- examples/README.md
Before: `limactl start ./FILE`
After: `limactl start template://TEMPLATE`
> docs: templates: recommend the new CLI form

- website/content/en/docs/Installation/_index.md
https://deploy-preview-1810--lima-vm.netlify.app/docs/installation/
> docs: installation: use tabpane

- website/content/en/docs/Examples/_index.md
https://deploy-preview-1813--lima-vm.netlify.app/docs/examples/
> docs: examples: update

- Makefile
- README.md
- docs/mount.md
- docs/mutli-arch.md
- docs/network.md
- docs/vmtype.md
- website/content/en/docs/Config/Mount/_index.md
- website/content/en/docs/Config/Multi-arch/_index.md
- website/content/en/docs/Config/Network/_index.md
- website/content/en/docs/Config/VMType/_index.md
- website/content/en/docs/Config/_index.md
https://deploy-preview-1807--lima-vm.netlify.app/docs/config/
> mv docs/{mount,multi-arch,network,vmtype}.md https://lima-vm.io/docs/config/

- website/content/en/docs/Config/VMType/_index.md
- website/hugo.toml
https://deploy-preview-1823--lima-vm.netlify.app/docs/config/vmtype/
> docs: config/vmtype: add flowchart to choose the best vmType

- pkg/windows/registry_windows.go
Remove write access for the IsVSockPortFree and GetRandomFreeVSockPort functions because Write access to those registry keys requires Administrator privileges, which would otherwise _not_ be required to run limactl start.
> fix: allow non-admin users to run limactl start

- pkg/cidata/cidata.go
- pkg/networks/usernet/config.go
- pkg/networks/usernet/config_test.go
- pkg/networks/usernet/gvproxy.go
- pkg/vz/vm_darwin.go
> Fix vm freeze for invalid leases in user-v2

- .github/workflows/test.yml
> CI: add go-licenses

- website/content/en/docs/faq/colima/_index.md
https://deploy-preview-1837--lima-vm.netlify.app/docs/faq/colima/
> docs/faq: add colima

- website/layouts/partials/footer.html
working on #1839, going to check in GitHub discussion how exactly to run the website locally (haven't been able to successfully yet)
> removed links from website/layouts/partials/footer.html

- pkg/qemu/entitlementutil/entitlementutil.go
The warning message `QEMU binary /Users/<USER>/.colima/_wrapper/<HASH>/bin/qemu-system-x86_64 is not properly signed` is usually negligible for colima, but printed due to:
- abiosoft/colima#796
> Relax "QEMU binary /Users/<USER>/.colima/_wrapper/<HASH>/bin/qemu-system-x86_64 is not properly signed"

- .github/workflows/test.yml
This was a workaround for
- https://github.com/Homebrew/homebrew-core/issues/140244
> CI: remove hack/fix-qemu-signature.sh

- website/content/en/_index.html
- website/data/helpfullinks.yaml
- website/layouts/shortcodes/blocks/helpfullinks.html
Updated _index.html under main content to make the icons corresponding to the necessary links clickable.
> Make icons corresponding to links clickable

- .github/workflows/release.yml
> release.yml: migrate from `hub` to `gh`

- cmd/limactl/delete.go
- cmd/limactl/main.go
- cmd/limactl/protect.go
- cmd/limactl/unprotect.go
- pkg/store/filenames/filenames.go
- pkg/store/instance.go
- website/content/en/docs/dev/Internals/_index.md
> Add `limactl protect <INSTANCE>` to prohibit accidental removal

- pkg/cidata/cidata.TEMPLATE.d/boot/50-alpine-fix.sh
- pkg/networks/usernet/gvproxy.go
> Fix DNS issue with alpine after upgrade

- pkg/wsl2/wsl_driver_windows.go
- website/content/en/docs/Config/Mount/_index.md
- website/content/en/docs/Config/VMType/_index.md
> Revert "wsl2: temporarily remove docs"

- cmd/limactl/start.go
> fix: Ctrl-C does not interrupt create prompt

- pkg/cidata/cidata.TEMPLATE.d/boot/05-rosetta-volume.sh
Fixes #1920
Signed-off-by: T K Chandra Hasan <t.k.chandra.hasan@ibm.com>
> Set secontext for rosetta in selinux supported distros

- .github/workflows/test.yml
Picking this as an issue labeled "good-first-issue" :)
Ref https://github.com/lima-vm/lima/issues/1812
> Don't run tests on docs changes

- pkg/networks/config.go
- pkg/networks/config_test.go
> Fix for default network for user-v2

- .github/dependabot.yml
https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/
> dependabot: enable groups

- pkg/cidata/cidata.TEMPLATE.d/boot/07-etc-environment.sh
> pkg/cidata:  During boot, only terminate user connections when the environment changes 

- pkg/qemu/qemu.go
> qemu: UEFI: fix warning `Unexpected result from downloader.Download()`

- pkg/vz/vz_driver_darwin.go
> Mark TimeZone as a known property for the YAML driver

- cmd/limactl/completion.go
- cmd/limactl/disk.go
Added disk name completion for the following commands:
`limactl disk delete`
`limactl disk unlock`
`limactl disk resize`
> add completion for limactl disk

- examples/apptainer-rootful.yaml
- examples/apptainer.yaml
- examples/buildkit.yaml
- examples/centos-stream-8.yaml
- examples/centos-stream-9.yaml
- examples/default.yaml
- examples/docker-rootful.yaml
- examples/docker.yaml
- examples/experimental/9p.yaml
- examples/experimental/armv7l.yaml
- examples/experimental/riscv64.yaml
- examples/experimental/rke2.yaml
- examples/experimental/u7s.yaml
- examples/experimental/virtiofs-linux.yaml
- examples/experimental/vnc.yaml
- examples/faasd.yaml
- examples/k3s.yaml
- examples/k8s.yaml
- examples/ubuntu-lts.yaml
- examples/ubuntu.yaml
- examples/vmnet.yaml
- pkg/limayaml/defaults.go
https://github.com/containerd/nerdctl/releases/tag/v1.7.3
> nerdctl: update to v1.7.3; templates: update Ubuntu, CentOS Stream

- pkg/vz/vz_driver_darwin.go
> Avoid warning about upgrade with vz driver

- pkg/limayaml/defaults.go
Instance name (`{{.Name}}`) has been allowed in host templates but missing in guest templates
> limayaml: allow `{{.Name}}` in provision scripts

- pkg/cidata/cidata.TEMPLATE.d/boot/11-colorterm-environment.sh
> Support /etc/ssh/sshd_config.d for AcceptEnv

- README.md
The noun documentation can be countable or uncountable.
In more general, commonly used, contexts, the plural form will also be [documentation](https://www.wordhippo.com/what-is/the-meaning-of-the-word/documentation.html).
> README.md: fix grammar issue

- cmd/limactl/list.go
- I believe this should fix the issue where nothing is printed on an unmatched list error caused by PR #2295
- Prints the matching instances, and then exits with 1
- Please let me know if I missed anything
> limactl ls $INSTANCE should exit with non-0 status if $INSTANCE does not exist #1139 #2295

- examples/apptainer.yaml
> apptainer: fix AppArmor incompatibility with Ubuntu 24.04

- website/content/en/docs/dev/Internals/_index.md
https://pkg.go.dev/os#UserCacheDir
> Document the cache directory location

- examples/alpine-image.yaml
> Use UEFI instead of BIOS for alpine-image

- examples/almalinux-9.yaml
> Update almalinux 9 sample to 9.4

- README.md
Lima is now passing the OpenSSF best practices badge: https://www.bestpractices.dev/en/projects/6505
> README.md: add OpenSSF best practices badge

- pkg/cidata/cidata.TEMPLATE.d/boot/07-etc-environment.sh
> Handle missing /etc/environment file in boot

- pkg/cidata/cidata.TEMPLATE.d/boot/40-install-containerd.sh
`containerd-rootless-setuptool.sh uninstall` was called without uninstalling BuildKit
- - -
Cherry-picked from:
- #2178
> cidata: fix upgrading nerdctl

- examples/docker-rootful.yaml
- examples/docker.yaml
- examples/experimental/u7s.yaml
- examples/experimental/vnc.yaml
- examples/k8s.yaml
This PR edits hints in examples.
> docs: remove redundant dot in examples

- pkg/store/fuzz_test.go
Adds the fuzzer from https://github.com/google/oss-fuzz/pull/12193
> add fuzz test for store package

- pkg/downloader/fuzz_test.go
Adds a fuzzer that creates a file and then downloads it.
> add fust test for downloader

- website/content/en/docs/faq/colima/_index.md
Clarify that it is running k3s, not kubeadm
> [docs] Small clarification on Colima Kubernetes

- .github/actions/upload_failure_logs_if_exists/action.yml
- .github/workflows/test.yml
- hack/test-templates.sh
I think `tail "$HOME/.lima/${NAME}"/*.log` is not sufficient.
Thanks,
> test.yml: upload `failure-logs` as an artifact if `test-templates.sh` fails and `failure-logs` exists.

- examples/almalinux-8.yaml
- examples/apptainer-rootful.yaml
- examples/apptainer.yaml
- examples/buildkit.yaml
- examples/centos-stream-9.yaml
- examples/debian-11.yaml
- examples/debian-12.yaml
- examples/default.yaml
- examples/docker-rootful.yaml
- examples/docker.yaml
- examples/experimental/9p.yaml
- examples/experimental/alsa.yaml
- examples/experimental/armv7l.yaml
- examples/experimental/riscv64.yaml
- examples/experimental/rke2.yaml
- examples/experimental/u7s.yaml
- examples/experimental/virtiofs-linux.yaml
- examples/experimental/vnc.yaml
- examples/faasd.yaml
- examples/k3s.yaml
- examples/k8s.yaml
- examples/ubuntu.yaml
- examples/vmnet.yaml
1. [update ubuntu 24.04 release-20240710](https://github.com/lima-vm/lima/commit/1ce07ab62dabb830fc304e9b32c06591e9bc5171)
2. [update centos-stream-9 20240715](https://github.com/lima-vm/lima/commit/1b30788e11ca346a631fbee28f3523be7586c197)
> update images update ubuntu centos-stream-9

- .github/workflows/test.yml
- examples/archlinux.yaml
Revert #2535  #1723 to avoid the 9p issue #2538
Fix #2538
> Revert "Temporarily disable CI on archlinux" 

- Makefile
Closes #2571
Keep in sync with https://github.com/lima-vm/lima/blob/master/.github/workflows/test.yml#L21
We could consider using the same scripts/targets for both, and to mention where to get the tools
> Add ls-lint to the list of linters

- examples/README.md
- examples/opensuse-leap.yaml
- examples/opensuse.yaml
> Rename opensuse to opensuse-leap

- go.mod
- pkg/limayaml/load.go
- pkg/limayaml/load_test.go
- pkg/yqutil/yqutil.go
- pkg/yqutil/yqutil_test.go
Just in case that yqlib starts using another library...
Issue #2597
> Validate yaml with yqlib and not with go-yaml v3

- cmd/limactl/shell.go
- cmd/limactl/show-ssh.go
- pkg/driver/driver.go
- pkg/driverutil/instance.go
- pkg/hostagent/hostagent.go
- pkg/instance/ansible.go
- pkg/instance/create.go
- pkg/instance/delete.go
- pkg/instance/start.go
- pkg/networks/usernet/client.go
- pkg/qemu/qemu_driver.go
- pkg/snapshot/snapshot.go
- pkg/store/instance.go
- pkg/vz/disk.go
- pkg/vz/vm_darwin.go
- pkg/vz/vz_driver_darwin.go
- pkg/wsl2/fs.go
- pkg/wsl2/wsl_driver_windows.go
> instConfig is redundant with inst.Config

- .github/workflows/test.yml
https://github.com/lima-vm/socket_vmnet/compare/v1.1.1...v1.1.5
> CI: SOCKET_VMNET_VERSION: v1.1.5

- cmd/lima-guestagent/main_linux.go
- cmd/limactl/main.go
- pkg/debugutil/debugutil.go
- pkg/usrlocalsharelima/usrlocalsharelima.go
> Fix '"debug build detected" is always printed' issue

- pkg/nativeimgutil/nativeimgutil.go
- pkg/osutil/osutil_unix.go
- pkg/osutil/osutil_windows.go
> osutil: remove Ftruncate

- .github/workflows/scorecard.yml
See https://scorecard.dev
This PR has been generated by https://github.com/marketplace/actions/ossf-scorecard-action; I only added the `workflow_dispatch` trigger. (And I edited the YAML to appease our linters).
> Create OSSF scorecard.yml

- website/.gitignore
- website/package-lock.json
Added package-lock.json file in website
https://github.com/lima-vm/lima/issues/2749
> add package-lock.json file

- pkg/limayaml/defaults.go
Cutting down on the debug log information
> Don't look for vz-identifier on other systems

- .codespellrc
> Don't spell-check go.mod and go.sum

- examples/ubuntu-20.04.yaml
- examples/ubuntu-22.04.yaml
Replaces:
- https://github.com/lima-vm/lima/pull/2433
> templates: add ubuntu-20.04, ubuntu-22.04

- pkg/vz/vz_driver_darwin.go
> Silence `WARN[0001] vmType vz: ignoring [MinimumLimaVersion]`

- pkg/vz/vz_driver_darwin.go
> silence `WARN[0001] vmType vz: ignoring [User]`

- pkg/downloader/downloader.go
Extracting a helper to apply Opt function to options to simplify and clarify downloader.Download(). This remove duplicate loops repeated 4 times in this package.
> Extract options.apply helper

- templates/default.yaml
> Show that guestIP should be specified to ignore ports for forwarding

- pkg/vz/network_darwin.go
> vz: qemuPacketConn: Disallow partial reads

- pkg/networks/usernet/dnshosts/dnshosts_test.go
This PR simplifies `TestExtractZones` by using `slices.IndexFunc` and `slices.SortFunc`.
> Simplify TestExtractZones

- README.md
https://github.com/lima-vm/lima/actions/runs/12021269503/job/33511453471?pr=2894#step:14:43
```console
Issues :-(
> Links
1. [L86] 404 https://www.linuxfoundation.org/trademark-usage/
```
> Fix hyperlinks issue

- website/content/en/docs/examples/gha.md
Test run:
- https://github.com/rootless-containers/usernetes/pull/344
> docs/examples/gha: verify GitHub Attestations

- .github/workflows/test.yml
- website/content/en/docs/config/network.md
https://github.com/lima-vm/socket_vmnet/compare/v1.1.5...v1.2.0
> CI and docs: update socket_vmnet (1.2.0)

- pkg/guestagent/guestagent_linux.go
- pkg/guestagent/kubernetesservice/kubernetesservice.go
- Clarify error handling when creating guest agent
- Improve startup logging to make the status of the guest agent more clear
> Improve guestagent startup error handling and logging

- pkg/osutil/machineid.go
- pkg/sysprof/sysprof_darwin.go
The PR refactors `sysprof.NetworkData` and `osutil.MachineID` by using `sync.OnceValues` instead of `sync.Once`.
Materials: https://victoriametrics.com/blog/go-sync-once/index.html.
> sysprof,osutil: simplify with sync.OnceValues

- pkg/cidata/cidata.TEMPLATE.d/boot/30-install-packages.sh
Previously failing to install sshfs package.
https://github.com/lima-vm/lima/issues/3022#issuecomment-2543160594
> Allow running Enterprise Linux release 10 too

- templates/experimental/opensuse-tumbleweed.yaml
- templates/opensuse-leap.yaml
> template: opensuse: virtiofs is not supported

- website/hugo.toml
```
Change enables search box on the website.
```
Link to issue: https://github.com/lima-vm/lima/issues/3004
> enable search box on website

- cmd/limactl/shell.go
https://github.com/lima-vm/lima/pull/3074#pullrequestreview-2526823387
Closes #3073
> Revert to quiet log level for older ssh versions

- website/hugo.toml
```
change redirects user to the release page on GitHub
```
issue can be found [here](https://github.com/lima-vm/lima/issues/2957)
> redirect user to release page on GitHub

- pkg/limayaml/containerd.yaml
- templates/alpine.yaml
- templates/apptainer-rootful.yaml
- templates/apptainer.yaml
- templates/archlinux.yaml
- templates/buildkit.yaml
- templates/centos-stream-10.yaml
- templates/centos-stream-9.yaml
- templates/debian-12.yaml
- templates/default.yaml
- templates/docker-rootful.yaml
- templates/docker.yaml
- templates/experimental/alsa.yaml
- templates/experimental/rke2.yaml
- templates/experimental/u7s.yaml
- templates/experimental/vnc.yaml
- templates/faasd.yaml
- templates/k3s.yaml
- templates/k8s.yaml
- templates/ubuntu-20.04.yaml
- templates/ubuntu-22.04.yaml
- templates/ubuntu-24.04.yaml
- templates/ubuntu-24.10.yaml
See the individual commits.
Will release v1.0.4 after merging this.
> update nerdctl, templates, and comments

- hack/test-templates.sh
fixes #3301  
added the check for now as suggested for the yq installation on windows
> added the yq check to test-template

- website/content/en/docs/community/subprojects.md
- website/content/en/docs/examples/gha.md
Use https://github.com/lima-vm/lima-actions for simplicity
Fix #3312
> docs/examples/gha: use lima-actions

- pkg/vz/vz_driver_darwin.go
> vz: included Kernel and Initrd as known feilds 

- website/content/en/docs/installation/_index.md
- website/content/en/docs/installation/source.md
> separated binary installation

- .golangci.yml
- cmd/limactl/list.go
- cmd/limactl/prune.go
- pkg/cidata/cidata.go
- pkg/downloader/downloader_test.go
- pkg/guestagent/procnettcp/procnettcp.go
- pkg/hostagent/requirements.go
- pkg/limatmpl/embed_test.go
- pkg/limatmpl/locator.go
- pkg/limayaml/defaults.go
- pkg/limayaml/validate.go
- pkg/lockutil/lockutil_test.go
- pkg/networks/validate.go
- pkg/qemu/qemu_driver.go
- pkg/reflectutil/reflectutil.go
- pkg/vz/network_darwin_test.go
Simplify code by running the command:
```
go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...
```
Read more about `modernize`: https://github.com/golang/tools/releases/tag/gopls%2Fv0.18.0
> refactor: Simplify code with gopls modernize

- pkg/hostagent/dns/dns.go
When IPv6 is disabled, the hostAgent enters a code path that introduces a 1-second sleep whenever it receives an
`AAAA` DNS query. This delay can cause the DNS query to timeout, triggering a retry loop on the client side. Docker, for example, retries up to 10 times at 1-second intervals—resulting in a significant delay before an image is pulled.
A suggested workaround is to remove the sleep, which was originally introduced to address a specific issue that now appears to be outdated or no longer relevant.
[Unexpected A record DNS response](https://github.com/rancher-sandbox/rancher-desktop/issues/3447#issuecomment-1330876897)
> Fix slow image pull caused by delayed DNS response

- cmd/lima-guestagent/daemon_linux.go
- cmd/lima-guestagent/install_systemd_linux.go
- cmd/lima-guestagent/main_linux.go
- cmd/limactl/copy.go
- cmd/limactl/debug.go
- cmd/limactl/delete.go
- cmd/limactl/disk.go
- cmd/limactl/editflags/editflags.go
- cmd/limactl/hostagent.go
- cmd/limactl/list.go
- cmd/limactl/main.go
- cmd/limactl/restart.go
- cmd/limactl/shell.go
- cmd/limactl/show-ssh.go
- cmd/limactl/snapshot.go
- cmd/limactl/start.go
- cmd/limactl/stop.go
- cmd/limactl/template.go
- cmd/limactl/usernet.go
Hi team, I've fixed some CLI-related sentence casing in this commit. I've tested the codebase before pushing and everything seems to work fine.
> Capitalize Command & Command Flag Descriptions (for consistency and clarity)

- pkg/cidata/cidata.TEMPLATE.d/boot/30-install-packages.sh
> oraclelinux: fix virtiofs support

- .golangci.yml
- pkg/limayaml/defaults_test.go
https://golangci-lint.run/usage/linters/#usetesting
> Enable usetesting linter

- templates/_images/archlinux.yaml
- templates/_images/centos-stream-10.yaml
- templates/_images/centos-stream-9.yaml
- templates/_images/debian-11.yaml
- templates/_images/debian-12.yaml
- templates/_images/oraclelinux-8.yaml
- templates/_images/oraclelinux-9.yaml
- templates/_images/ubuntu-20.04.yaml
- templates/_images/ubuntu-22.04.yaml
- templates/_images/ubuntu-24.04.yaml
- templates/_images/ubuntu-24.10.yaml
- templates/_images/ubuntu-25.04.yaml
CentOS-Stream-GenericCloud-*-20250317 seems deleted
> templates: update

- website/content/en/docs/installation/_index.md
> website: add DragonFlyBSD

- cmd/limactl/disk.go
- pkg/qemu/imgutil/imgutil.go
- pkg/qemu/qemu.go
> chore: move CreateDataDisk and ResizeDataDisk to util

- .github/workflows/test.yml
> CI: cross-compile GOOS=netbsd,dragonfly

- cmd/limactl/disk.go
- pkg/nativeimgutil/nativeimgutil.go
- pkg/qemu/imgutil/imgutil.go
As a "good first issue", fixing https://github.com/lima-vm/lima/issues/3517
> decoupling imgutils from filenams

- pkg/store/disk.go
fixes https://github.com/lima-vm/lima/issues/3497
> removing qemu fallback for inspectDiskSize

- templates/_images/oraclelinux-8.yaml
Thanks to @plexilcrf for the info
- #3522
> templates: oraclelinux-8: known to work on M1

- .github/workflows/release.yml
- .github/workflows/test.yml
> CI: set GOTOOLCHAIN=local to prevent auto update of Go

- cmd/limactl/list.go
> Always return an error when a requested instance is not found

- pkg/cidata/cidata.TEMPLATE.d/boot/01-alpine-ash-as-bash.sh
> fix(cidata): do not overwrite bash in alpine vm

- pkg/cidata/cidata.go
- pkg/hostagent/hostagent.go
- pkg/instance/hostname/hostname.go
- pkg/instance/hostname/hostname_test.go
- pkg/limayaml/defaults.go
- pkg/sshutil/format.go
- pkg/store/instance.go
https://github.com/lima-vm/lima/pull/3578#discussion_r2107430960
> Change package name of `instance/hostname` from `instance` to `hostname`

- cmd/limactl/editflags/editflags.go
An alias of `--set ".mounts = null"`
> editflags: add `--mount-none`

- cmd/limactl/start.go
> Embed templates selected from the user interface

- README.md
```
change links contributing guide in README to improve DCO discoverability
```
> add contributing link to readme

- cmd/limactl/start.go
Corresponds to the examples in `limactl --help`
> limactl (create|start) --help: indent examples

- README.md
> README.md: add meeting information

- go.mod
- go.sum
- hack/test-templates.sh
- hack/test-templates/test-misc.yaml
Fix #3845, #3308
Re-enable tests disabled by #3308 in test-misc.yaml and test-templates.sh.
> Use https://github.com/diskfs/go-diskfs/pull/296

- website/content/en/docs/community/governance.md
Ref https://github.com/lima-vm/lima/issues/3795#issuecomment-3221889108
> Document GitHub teams and repo access rules

- pkg/driverutil/vm.go
> driverutil: allow external driver stderr

- Makefile
Fixes https://github.com/lima-vm/lima/pull/3744#issuecomment-3290200398
> Fix: `make uninstall` should remove external drivers

- cmd/limactl/template.go
Ref https://github.com/lima-vm/lima/issues/3712#issuecomment-3364303120
> Don't hide template subcommand anymore but mark it EXPERIMENTAL

- pkg/driver/qemu/qemu_driver.go
This change separates `checkBinarySignature()` from `validateConfig()` to prevent calling them from `FillConfig()`. fixes #4142
> pkg/driver/qemu: Avoid calling `checkBinarySignature()` from `FillConfig()`.

- .github/workflows/test.yml
- hack/test-templates.sh
The resource constraint should be set by the caller via `$LIMACTL_CREATE_ARGS`.
> hack/test-templates.sh: remove `--cpus 1 --memory 1`
