README.md
`lima` also requires `coreutils` to be installed, without it you run into the following problem:
```
$ ./bin/lima
./bin/lima: line 4: realpath: command not found
```
=> mention coreutils requirement in README (for realpath command)

README.md
Tests on multiple MacOS 10.15.7 and 11.3.1 machines showed that when this entitlement is added gatekeeper prevents qemu to start (error "kill -9"). I'm not entirely sure but I believe there was a breaking change from 10.15.6 to 10.15.7 and [Apple docs](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_hypervisor) are incorrect.
See discussion in #4 
Closes #4
=> Docs: Discourage use of com.apple.vm.hypervisor on macOS >=10.15.7

pkg/qemu/qemu.go
Without `highmem=off` in `-machine` flag QEMU exits with error "qemu-system-aarch64: VCPU supports less PA bits (36) than requested by the memory map (40)".
=> Make it working on Apple Silicon

pkg/limayaml/defaults.go
As described in [template yaml](https://github.com/AkihiroSuda/lima/blob/605e06273d6b423b5ba97a22a781e64b52fabf90/pkg/limayaml/default.TEMPLATE.yaml#L3), default in `arch` field means host architecture, but `resolveArch` function returns opposite value.
=> Fix default arch resolve function

README.md, docs/internal.md, pkg/limayaml/default.TEMPLATE.yaml, pkg/limayaml/defaults.go, pkg/limayaml/limayaml.go, pkg/qemu/qemu.go, pkg/start/start.go
As of QEMU v5.2, enabling video display has negative impact due to macOS App Nap: https://gitlab.com/qemu-project/qemu/-/issues/334
Close #29
=> disable video display by default

README.md, cmd/lima
- `coreutils` is no longer needed
- QEMU no longer needs to be signed
=> Simplify installation steps

examples/k3s.yaml, pkg/cidata/cidata.go, pkg/cidata/template.go, pkg/cidata/user-data.TEMPLATE, pkg/hostagent/hostagent.go, pkg/hostagent/requirements.go, pkg/limayaml/default.TEMPLATE.yaml, pkg/limayaml/defaults.go, pkg/limayaml/limayaml.go, pkg/limayaml/validate.go
Fixes #33 
In addition this PR implements a `bare-vm` setting that disables installation of optional requirements (`containerd` and `nerdctl`), and also skips installation of `sshfs` if there are no directories to mount.
Example use to provision kubernetes via `k3s` (although not in rootless mode):
```console
$ cat k3s.yaml
images:
- location: "~/Downloads/hirsute-server-cloudimg-amd64.img"
arch: "x86_64"
mounts: []
ssh:
localPort: 60022
bare-vm: true
provision:
system: |
#!/bin/sh
curl -sfL https://get.k3s.io | sh -
$ limactl start --tty=false k3s.yaml
[...]
INFO[0032] READY. Run `lima bash` to open the shell.
INFO[0032] Forwarding "/run/user/501/lima-guestagent.sock" (guest) to "/Users/jan/.lima/k3s/ga.sock" (host)
INFO[0051] Forwarding TCP port 6444
INFO[0051] Forwarding TCP port 6443 …
```
=> Implement system and user provisioning scripts

cmd/limactl/shell.go
Changes to the previous implementation are:
* If there are no volume mounts then there is no fallback to the host `$HOME` directory (because we know it isn't mounted, so no need to display an additional error).
* If the `--workdir` does not exist in the guest, we fallback to the host `$PWD` first before trying the host `$HOME` (because it is less surprising to stay in the current directory than to switch to one that is different from the requested one).
No error message when `--workdir` is not specified, and only a single error message when the requested workdir does not exist:
```console
$ limactl shell k3s bash
jan@lima-default:~$ pwd
/home/jan.linux
jan@lima-k3s:~$ exit
$ limactl shell --workdir /does-not-exist k3s bash
bash: line 1: cd: /does-not-exist: No such file or directory …
```
=> Update logic for shell workdir

cmd/limactl/main.go, cmd/limactl/prune.go, docs/internal.md, go.mod, go.sum, pkg/cidata/cidata.go, pkg/cidata/user-data.TEMPLATE, pkg/downloader/downloader.go, pkg/qemu/qemu.go
The `~/Library/Caches/lima/download/by-url-sha256/<SHA256_OF_URL>` directory contains the following files:
- `url`: raw url text, without "\n"
- `data`: data
=> add HTTP cache (~/Library/Caches/lima)

pkg/cidata/user-data.TEMPLATE
Make sure `/etc/containerd` exists before writing `/etc/containerd/config.toml`.
=> Fix containerd.system=true provisioning

.github/workflows/test.yml, examples/alpine.yaml, hack/test-example.sh, pkg/cidata/user-data.TEMPLATE, pkg/hostagent/requirements.go, pkg/iso9660util/iso9660util.go, pkg/qemu/qemu.go
Requires Alpine image with cloud-init, but configures lima-guestagent service with openrc and pretends /bin/ash can stand in for /bin/bash.
Does not work with containerd; not sure where to put the OpenRC scripts for it (maybe nerdctl?).
When booting from a LiveCD image there is no point in generating a `diffDisk` because the OS is running from RAM, not from the disk.
In that case just add `diffDisk` as an independent data volume and move directories that should be persisted on there. Currently: `/home`, `/usr/local`, `/etc/containerd`, and `/var/lib/containerd`.
This `data-volume` logic is currently only enabled for Alpine because it hasn't been tested anywhere else yet.
Additional, if the configured disk size is 0, no `diffDisk` will be allocated and changes will be written back to the …
=> Add support for Alpine guest OS

.github/workflows/test.yml, README.md
v4.6.0 is broken: https://gitlab.freedesktop.org/slirp/libslirp/-/issues/48
=> CI: explicitly install libslirp v4.5.0

cmd/limactl/start.go, pkg/store/store.go
The `limactl start` command now verifies that the combination of LimaDir, instance name, and longest socket name is less than 104 characters, and refuses to create the instance otherwise.
This is intended for applications that want to use lima internally to manage Linux VMs, and don't want to mix those with the VMs managed by the user directly (e.g. [Rancher Desktop](https://github.com/rancher-sandbox/rancher-desktop)).
=> Implement LIMA_HOME to override ~/.lima location

pkg/cidata/user-data.TEMPLATE
Fixes #66 
Normally this would be done by the openrc script for containerd, e.g. https://github.com/alpinelinux/aports/blob/master/community/containerd/containerd.initd#L22-L24
Signed-off-by: Jan Dubois <jan.dubois@suse.com>
=> Make sure /sys/fs/cgroup is mounted on Alpine for container support

pkg/hostagent/hostagent.go, pkg/sshutil/sshutil.go
`ssh-keygen -R` will exit with a non-0 status and the hostagent would abort. If the file doesn't exist, then there isn't anything to do.
=> Don't try to remove host keys when ~/.ssh/known_hosts doesn't exist

hack/lima-and-qemu.pl
Installing qemu via homebrew installs 846MB of stuff under `/usr/local/Cellar`, 571MB of which are the `qemu` cellar alone.
This is clearly excessive for bundling `lima` with an app that simply wants to deploy VMs.
The attached script uses dtrace to observe which files are actually opened by `lima` and `qemu`, and then collects just those. It collects the corresponding symlinks and also modifies all Mach-O binaries to reference dylibs relative to the path of the executable, so the files can be relocated anywhere (the `/usr/local` prefix is stripped from all filenames).
There are still hard-coded paths to things under /usr/local inside the binaries, but testing shows that lima works with the bundled files as-is on a freshly installed Catalina VM (from memory, so may contain typos): …
=> Extract minimal set of lima and qemu files to install on a clean machine

docs/internal.md, go.mod, go.sum, pkg/hostagent/hostagent.go, pkg/qemu/qemu.go, pkg/qemu/qemu_test.go
Passing args is also possible (only for debugging purpose), e.g., "QEMU_SYSTEM_X86_64=/opt/qemu/bin/qemu-system-x86_64 -snapshot" .
Fix #27 
Fix #14
=> allow overriding qemu binary ($QEMU_SYSTEM_X86_64, $QEMU_SYSTEM_AARCH64)

docs/internal.md, pkg/cidata/cidata.go, pkg/sshutil/sshutil.go, pkg/sshutil/sshutil_test.go, pkg/store/filenames/filenames.go, pkg/store/store.go
By default lima uses the public keys from `~/.ssh/*.pub`.
This change makes it try `$LIME_HOME/_config/user.pub` first and only fall back on the `~/.ssh/*.pub` keys when that one does not exist. It will create the key under `$LIMA_HOME/_config` if there aren't any public keys under `~/.ssh`.
Fixes #78
=> Use user identify from $LIMA_HOME/_config/user

.github/workflows/test.yml, examples/opensuse.yaml, pkg/cidata/cidata.TEMPLATE.d/boot/30-install-packages.sh, pkg/cidata/cidata.TEMPLATE.d/boot/40-install-containerd.sh
Unfortunately I couldn't find a corresponding image for aarch64.
Also containerd still failing:
```console
jan@lima-opensuse:/Users/jan> nerdctl pull ghcr.io/stargz-containers/nginx:1.19-alpine-org
ghcr.io/stargz-containers/nginx:1.19-alpine-org:                                  resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:d942e5263869b00ed3174fb76573165dc89e391bfafa43e9134a9c6e0bf0ec87:    done           |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:4fe11ac2b8ee14157911dd2029b6e30b7aed3888f4549e733aa51930a4af52af: done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:72ab4137bd85aae7970407cbf4ba98ec0a7cb9d302e93a38bb665ba5fddf6f5d:   downloading    |--------------------------------------|    0.0 B/8.0 KiB
elapsed: 1.0 s …
```
=> Add openSUSE example config (using JeOS image for OpenStack).

cmd/limactl/copy.go, cmd/limactl/main.go, hack/test-example.sh, pkg/sshutil/sshutil.go
This is a wrapper around `scp`. User doesn't have to lookup / specify the port number, and doesn't have to prefix remote names with `127.0.0.1:`; a single `:` is enough. And the connection goes through the ControlPath.
Example:
```
limactl cp default :/etc/os-release .
```
=> Add copy/cp/scp command

README.md
I've removed the ssh related FAQs that should no longer be relevant because the code deals with them correctly now. Not sure if you may want to keep them in the FAQ for a while though, for users of earlier lima versions.
=> README updates: add openSUSE, remove outdated FAQs

pkg/cidata/cidata.TEMPLATE.d/boot/05-persistent-data-volume.sh
Although lima doesn't store the host key, it is wrong to change it on every reboot.
=> Move /etc/ssh to persistent data-volume

pkg/cidata/cidata.TEMPLATE.d/boot/10-alpine-prep.sh
`rc-service reload` will fail if the service is not already running, terminating the script early.
=> Don't reload sshd service if it hasn't started yet

.cirrus.yml, .github/workflows/test.yml
Fix #94 
- - -
- `default.yaml` is still tested on macOS instances of GHA
- Other yamls are tested on Linux instances of Cirrus. macOS instances of Cirrus cannot be used due to lack of support for nested VMs.
Unlike GHA, Cirrus allows restarting an individual failed test.
=> CI: add .cirrus.yml

cmd/limactl/copy.go, cmd/limactl/shell.go, pkg/cidata/cidata.go, pkg/hostagent/hostagent.go, pkg/limayaml/default.yaml, pkg/limayaml/defaults.go, pkg/limayaml/limayaml.go, pkg/sshutil/sshutil.go, pkg/sshutil/sshutil_test.go
`ssh.loadDotSSHPubKeys` (boolean) specifies whether to load `~/.ssh/*.pub` in addition to `$LIMA_HOME/_config/user`.
The default value remains true.
- - -
I'll release v0.5.0 after merging this and https://github.com/AkihiroSuda/lima/pull/106
=> ssh: allow `ssh.loadDotSSHPubKeys = false`

docs/internal.md, examples/alpine.yaml, examples/archlinux.yaml, examples/debian.yaml, examples/fedora.yaml, go.mod, go.sum, pkg/cidata/cidata.go, pkg/downloader/downloader.go, pkg/limayaml/limayaml.go, pkg/limayaml/validate.go, pkg/qemu/qemu.go
Also removes dependency on `curl` binary
=> Support digest validation

pkg/sshutil/sshutil.go
This change is from debugging a setup issue with lima 0.4.0 by @mook-as.
It was no longer required with 0.5.0, but it shouldn't hurt, and might be useful to avoid other conflicts.
=> Always disregard ~/.ssh/config; only use specified identity file

README.md, cmd/limactl/copy.go
It fails if there is a public key without a corresponding private key in `~/.ssh`. `useDotSSHPubKeys` should not be needed for the copy command except when using it on legacy instances. Document how to make those instances compatible.
=> Don't useDotSSHPubKeys for limactl copy command

pkg/cidata/cidata.TEMPLATE.d/boot/05-persistent-data-volume.sh
This makes the relocation more transparent to apps and users because symlinks are sometimes treated differently.
E.g.
```console
$ l shell alpine
lima-alpine:/Users/jan$ cd
lima-alpine:/mnt/data/home/jan.linux$
```
becomes
```console
$ l shell alpine
lima-alpine:/Users/jan$ cd
lima-alpine:~$
```
=> Use bind mounts instead of symlinks to move directories to data volume

pkg/guestagent/api/client/client.go
Otherwise an `omitempty` field may retain the value of the previous event.
Fixes #121
=> Make sure the event struct is cleared for each new event

pkg/cidata/cidata.TEMPLATE.d/boot/05-persistent-data-volume.sh
Instead of adding e.g. `/var/lib/buildkit` in a provisioning script, it makes more sense to move all of `/var/lib` to `/mnt/data/var/lib`.
Similarly buildkit seems to create big subdirectories under `/tmp` that look like chroots, so lets move that to the data volume as well to prevent buildkit from running out of space.
=> Move all of `/var/lib` to the persistent data volume

.cirrus.yml, hack/test-example.sh, hack/test-port-forwarding.pl, pkg/guestagent/api/api.go, pkg/guestagent/guestagent_linux.go, pkg/hostagent/hostagent.go, pkg/hostagent/port.go, pkg/limayaml/default.yaml, pkg/limayaml/defaults.go, pkg/limayaml/limayaml.go, pkg/limayaml/validate.go
This allows to expose e.g. an ingress port outside of the local host while still forwarding other ports only to localhost.
Example:
```yaml
allInterfaces:
- port: 443
- port: 4000
until: 4999
```
I'm not quite sure how this will interact with #45, but I think/hope it will be independent (the filtering of incoming connections would be done via `iptables` inside the guest?).
I'm also not really happy about the `allInterfaces` key name, but couldn't come up with anything better.
=> Allow forwarding of specified port ranges to all interfaces

hack/test-example.sh
Regarding #119, if `lima` gets renamed, then `lime` would be my preferred choice (after not changing it at all). 😄
=> Oops, I did it again

hack/test-example.sh
Each new `trap ... EXIT` command simply replaces the previous trap handler with the new one, so only the very last one will be executed.
Side-question: why do we create all the temp directories and files in the `$HOME` directory? Is `/tmp` not writable? Can't we use `mktemp`?
=> trap handlers don't stack; there is only one per signal

Makefile
Ensuring that `$(DESTDIR)/$(PREFIX)` is a canonical name referring to an existing directory (via `$(realpath ...)`) on the `install` and `uninstall` make targets.
```console
make install # -> installs in /usr/local
PREFIX=/usr/local/ make install # -> installs in /usr/local
DESTDIR=/tmp/ PREFIX=/ciao/ make install # -> installs in /tmp/ciao (assuming it already exists)
DESTDIR=/tmp/ PREFIX=ciao make install # -> installs in /tmp/ciao (assuming it already exists)
DESTDIR=/tmp/ PREFIX=ciao/ make install # -> installs in /tmp/ciao (assuming it already exists)
DESTDIR=/tmp/ PREFIX=/ciao/ make install # -> installs in /tmp/ciao (assuming it already exists)
DESTDIR=/tmp PREFIX=/ciao/ make install # -> installs in /tmp/ciao (assuming it already exists)
```
As you can see the goal is to make the …
=> fix: support for staged installs (DESTDIR prefixed)

cmd/limactl/start.go, pkg/cidata/cidata.TEMPLATE.d/network-config, pkg/cidata/cidata.go, pkg/cidata/template.go, pkg/limayaml/default.yaml, pkg/limayaml/defaults.go, pkg/limayaml/limayaml.go, pkg/limayaml/load.go, pkg/limayaml/template_test.go, pkg/limayaml/validate.go, pkg/qemu/qemu.go, pkg/start/start.go, pkg/store/store.go
=> Add networking options for vde_vmnet support

pkg/cidata/cidata.go, pkg/limayaml/defaults.go, pkg/limayaml/validate.go, pkg/qemu/qemu.go, pkg/qemu/qemuconst/qemuconst.go
Not really happy about the `qemuconst` package, but `limayaml` importing `qemu` would create a circular dependency.
Signed-off-by: Jan Dubois <jan.dubois@suse.com>
=> Add validation to network.vde[*].name fields

pkg/limayaml/validate.go
Not sure what happened, but somehow the format strings got mutilated during editing...
=> Fix NIC name validation format string corruption

.github/workflows/test.yml, README.md, docs/internal.md, docs/network.md, examples/vmnet.yaml, pkg/limayaml/default.yaml, pkg/limayaml/defaults.go, pkg/limayaml/limayaml.go, pkg/limayaml/validate.go, pkg/osutil/machineid.go, pkg/osutil/machineid_test.go, pkg/qemu/qemu.go
=> Put machineID to the MAC address hasher + update docs + misc

pkg/cidata/cidata.TEMPLATE.d/boot/05-persistent-data-volume.sh
Similar to #126
Current motivation: Renaming interfaces via `ip link set XXX name YYY` takes about 5 seconds per interface that we shouldn't have to spend again when an instance is stopped and restarted (yes, it's a micro-optimization 😄).
cloud-init will save the proper config in e.g. `/etc/netplan/50-cloud-init.yaml` or `/etc/udev/rules.d/70-persistent-net.rules`, so devices should come up with the correct names automatically.
=> Persist all of /etc on the data volume

hack/lima-and-qemu.pl
All dylib references in the binaries and libs are updated to use `@executable_path/..` to locate libs. In macOS Monterey (Public Beta) this is resolved not relative to the symlink, but relative to the symlink target.
To create a distro that works on Catalina/Big Sur *and* Monterey, the symlinks in the `bin` directory are resolved before packaging.
Symlinks still need to be stored for at least /usr/local/share/qemu so that qemu will still be able to find its data files.
Ref https://github.com/rancher-sandbox/rancher-desktop/issues/518
=> Resolve /usr/local/bin symlinks in hacks/lima-and-qemu

pkg/hostagent/hostagent.go, pkg/sshutil/sshutil.go
As we are dealing with temporary SSH host keys, we should not pollute the users's known hosts file with ephemeral data.  Additionally, this avoids issues where the user has an invalid known hosts file, as in https://github.com/rancher-sandbox/rancher-desktop/issues/504.
=> SSH: Set UserKnownHostsFile to /dev/null

pkg/qemu/qemu.go
> Backing file specified without backing format
> Detected format of qcow2.
=> qemu-img 6.1.0 no longer supports using -b without -F

pkg/qemu/imgutil/imgutil.go, pkg/qemu/qemu.go
Follow-up to #174 `qemu-img 6.1.0 no longer supports using -b without -F`
=> pkg/qemu: detect basedisk format

hack/lima-and-qemu.pl
For qemu 6.0.0 this was included in the opensnoop log, but with qemu 6.1.0 all the data files seem to be referenced purely relative to the executable.
=> Make sure /usr/local/share/qemu symlink is captured

.github/workflows/test.yml
Also run `brew upgrade`, just so everything is fresh. Collect timings, as we may drop `brew upgrade` again if it takes significant time.
=> Run `brew update` to make sure we always get the latest dependencies

pkg/sshutil/sshutil.go
Ignore .pub files in $HOME/.ssh without a matching private key to avoid failing `limactl start` when SSH certificates with a common suffix are present
Fixes #182
=> Ignore .pub files in $HOME/.ssh without a matching private key

cmd/limactl/shell.go
Because the lima wrapper turns `lima start foo` into `limactl shell default start foo` and the instance name should not
be part of the suggestion "Perhaps you meant `limactl start foo`".
Fixes #185
=> Fix `lima (start|stop|shell)` suggestion to remove instance name

pkg/cidata/cidata.TEMPLATE.d/boot.sh
There are 2 issues:
* a typo (note the double `}}`) made the waiting loop run forever:
```
until [ -e "/run/user/${LIMA_CIDATA_UID}}/systemd/private" ]; do sleep 3; done
```
* the user scripts are owned by root with mode 700 on /mnt/lima_cidata/... so not accessible by the regular user
This commit copies them into the home directory (and deletes them after execution)
Fixes #192
=> Make sure user provisioning scripts can be executed

cmd/limactl/copy.go, pkg/sshutil/sshutil.go
This lets us use `ControlPath` with the connection, so that if a small number of copies run in parallel we can reuse the connection, rather than failing when too many connections are in flight.  Note that this only works if there's a single remote host; if the copy involves multiple hosts (`limactl copy one:/some/path two:/some/path`), the syntax does not allow for separate configuration, so we have to fall back to the old way without a `ControlPath`.
Having too many copies in parallel will still hit any limits imposed by `MaxSessions` (default 10), at which point `scp` falls back to not using the control connection (and may hit `MaxStartups` instead).
=> copy: use SSHArgs if copying to a single remote host.

pkg/cidata/cidata.TEMPLATE.d/lima.env, pkg/cidata/cidata.go, pkg/cidata/template.go, pkg/limayaml/default.yaml, pkg/limayaml/limayaml.go
In many corporate environments proxy environment variables `HTTPS_PROXY,HTTP_PROXY,NO_PROXY` may need to be supplied to allow access to the internet. These changes would allow users too append any additional environment variables they may want at VM start.
=> Allow users to define custom environment variables to be loaded on VM start

pkg/cidata/cidata.TEMPLATE.d/network-config, pkg/cidata/cidata.go, pkg/cidata/template.go, pkg/osutil/dns_darwin.go, pkg/osutil/dns_others.go, pkg/osutil/osutil_others.go, pkg/sysprof/network_darwin.go, pkg/sysprof/sysprof_darwin.go
qemu user-mode networking is forwarding DNS to just a single DNS entry from the host. So if that entry does not resolve
the query, there is no fallback.
Fixes #150 (I hope)
Please review the code updating the DNS entries in the guest. The direct updates to `/etc/resolv.conf` are probably useless because the file will still be regenerated after cloud-init is done. I've included code to configure `systemd-resolved`, and `udhcpc` (used by Alpine). Any other mechanisms needing support?
The `sysprof` code is expected to be used to provide default proxy information as well (see https://github.com/lima-vm/lima/issues/189#issuecomment-911972759)
=> Pass DNS addresses from en0 interface to guest instance

pkg/limayaml/default.yaml, pkg/limayaml/limayaml.go
The syntax and the behavior of this field is still under discussion (PR #200), so this field is treated as experimental in the next upcoming release (v0.6.3).
Probably we can move this out of experimental in v0.6.4.
=> yaml: mark "Env" experimental for now

cmd/limactl/copy.go, pkg/cidata/cidata.go, pkg/limayaml/validate.go, pkg/osutil/user.go, pkg/sshutil/sshutil.go
At least some companies set local users via directory services and choose the email address as the user name. The '@' character is not valid in Linux usernames.
Fixes #191
=> Use "lima" username if the local user is not a valid Linux name

pkg/cidata/cidata.go, pkg/limayaml/default.yaml, pkg/limayaml/limayaml.go
In some situations (e.g. VPN) the user may need to explicitly set the DNS addresses; even the fallback to the "en0" settings
does not work.
This cannot be done in a provisioning script because they run after the boot scripts, but working DNS is required to install
additional dependencies.
=> Provide explicit DNS override

examples/alpine.yaml, pkg/cidata/cidata.TEMPLATE.d/user-data, pkg/sshutil/sshutil.go
It seems that some ~/.ssh/*.pub files are public SSL keys, so add some minimal validation before using them as authorized_keys.
Ref https://github.com/lima-vm/lima/issues/104#issuecomment-914030614
=> Ignore public keys that are not in ssh format

README.md, examples/README.md, examples/docker.yaml, examples/podman.yaml, examples/singularity.yaml
Docker, Podman, Singularity, or whatever can be used instead of the default containerd/nerdctl .
LXD can be used too, of course, but there is no `lxd.yaml`, because LXD is included in the default Ubuntu image.
Example usage:
```
$ limactl start ./docker.yaml
$ limactl shell docker docker run -it --rm -v $HOME:$HOME alpine
```
```
$ limactl start ./podman.yaml
$ limactl shell podman podman run -it --rm -v $HOME:$HOME:ro docker.io/library/alpine
```
```
$ limactl start ./singularity.yaml
$ limactl shell singularity singularity run -u -B $HOME:$HOME docker://alpine
```
- - -
`docker` CLI on macOS can connect to `dockerd` inside the guest VM as well: `DOCKER_HOST=ssh://127.0.0.1:60006 docker run -it --rm -v $HOME:$HOME alpine` .
This requires `NoHostAuthenticationForLocalhost yes` in …
=> examples: add {docker,podman,singularity}.yaml

pkg/cidata/cidata.TEMPLATE.d/user-data, pkg/cidata/cidata.go, pkg/cidata/template.go, pkg/qemu/qemuconst/qemuconst.go
This has no effect on instances managed by systemd, but is necessary on e.g. Alpine.
=> Add manage_resolv_conf to cloud-init

README.md, pkg/qemu/qemu.go
`-cpu host` seemed to cause kernel panic with QEMU 5.2 on Intel Mac, but seems to work well with QEMU 6.1 now
The behavior can be rolled back by specifying an env var like `QEMU_SYSTEM_X86_64=qemu-system-x86_64 -cpu Haswell-v4` or `QEMU_SYSTEM_AARCH64=qemu-system-aarch64 -cpu cortex-a72` .
=> qemu: use `-cpu host` by default

pkg/cidata/cidata.TEMPLATE.d/boot.sh
I thought I had tested them before, but they don't work right now, and I can't see how they would have worked before with this check in place, so 🤷 .
Not really happy with the explicit check for Alpine, but it matches the condition we have in `25-guestagent-base.sh`.
=> Fix user provisioning scripts for Alpine

pkg/cidata/cidata.TEMPLATE.d/boot/25-guestagent-base.sh
Because chown does not work if the name includes a dot, like "firstname.lastname".
See also https://github.com/lima-vm/alpine-lima/pull/13
Fixes https://github.com/rancher-sandbox/rancher-desktop/issues/605
=> Use numeric uid/gid with chown

pkg/osutil/user.go
This PR expands on #214.
The `useradd` utility uses a more restrictive pattern than the containerd `identifiers.Validate()` function: https://github.com/shadow-maint/shadow/blob/26bbee8/libmisc/chkname.c#L51-L78
Also a fully numeric username seems to break systemd/cloud-init, as `/run/user/$UID/systemd/private` is never created.
Note that this PR will also disallow the `firstname.lastname` usernames.
Fixes #235
=> Map usernames not allowed by useradd to the fallbackUser "lima"

pkg/hostagent/mount.go, pkg/limayaml/default.yaml
limactl start by default uses `-o allow_root` to mount macbook host directories into lima host.
```
zhao@lima-default:~$ ps aux | grep sshfs
zhao        1505  0.2  0.0 597028  3752 ?        Ssl  03:18   0:00 sshfs :/Users/zhao /Users/zhao -o slave -o allow_root
zhao        1523  0.0  0.0 162148  3060 ?        Ssl  03:18   0:00 sshfs :/tmp/lima /tmp/lima -o slave -o allow_root
zhao        2678  0.0  0.0   8392   920 pts/1    S+   03:21   0:00 grep --color=auto sshfs
````
When creating some containers that runs applications using user other than `root` - for example, Apache2 running inside our dev-docker container with `www-data` user, and use mounted folders as the DocumentRoot, it complains about the missing permission
```
[Thu Sep 16 03:24:39.080127 2021] [core:error] [pid 61] …
```
=> Switch sshfs mount options `-o allow_root` to `-o allow_other`

pkg/cidata/cidata.go
https://github.com/containerd/nerdctl/releases/tag/v0.11.2
---
I'll release Lima v0.6.4 after merging this
=> nerdctl: update to v0.11.2

cmd/lima-guestagent/daemon_linux.go, cmd/lima-guestagent/install_systemd_linux.go, cmd/lima-guestagent/lima-guestagent.TEMPLATE.service, cmd/lima-guestagent/main_linux.go, docs/internal.md, pkg/cidata/cidata.TEMPLATE.d/boot/25-guestagent-base.sh, pkg/guestagent/guestagent_linux.go, pkg/guestagent/iptables/iptables.go, pkg/guestagent/iptables/iptables_test.go, pkg/hostagent/hostagent.go, pkg/hostagent/requirements.go
A couple changes were made to make this possible including:
- Adding iptables package to read the ports exposed by portmap
CNI plugin. This was done so that 1 call to iptables is all
that is needed on each run.
- Move the lima-guestagent to run as root. This is needed for
permission to use iptables.
Note, this implementation only includes ipv4 support. Does not work for ipv6.
Closes #140 
Note, this is my first pass. Happy to make changes as needed.
=> Enable sudo nerdctl run to expose ports to localhost

hack/test-example.sh, pkg/networks/networks.go
Fixes #260
Also removes unused `networks.LimaScheme` constant.
=> Don't use dockerhub to avoid hitting rate limits in CI

pkg/cidata/cidata.TEMPLATE.d/boot/40-install-containerd.sh
- There's a broken brackets in `40-install-containerd.sh`, which makes containerd-setup process to be always executed
=> Fix broken brackets

README.md
`brew install lima` should now work on ARM, as the `hvf: Implement Apple Silicon Support`
patch set was applied to the Homebrew package of QEMU yesterday.
https://github.com/Homebrew/homebrew-core/commit/5e8eb5476928526f5ccb00fb03a260e22e82652c
The patch set is not merged into the QEMU upstream yet, but will be probably merged soon.
http://patchwork.ozlabs.org/project/qemu-devel/list/?series=262664&order=date
Thanks to @estesp for the info.
=> README.md: QEMU no longer needs to be patched for ARM

pkg/qemu/qemu.go
I've noticed that there are deprecation warnings when using the `--debug` parameter while installing.
---
This is my first contribution to an open source project, so please bear with me.
=> Remove deprecation warning in debug

pkg/cidata/cidata.TEMPLATE.d/meta-data, pkg/cidata/cidata.go, pkg/cidata/template.go
That way cloud-init will do all the first-boot processing again to apply e.g. updated network configuration.
Fixes #270
=> Change instance id on every start

pkg/cidata/cidata.go, pkg/cidata/template.go, pkg/limayaml/default.yaml, pkg/limayaml/limayaml.go, pkg/osutil/dns_darwin.go, pkg/osutil/dns_others.go, pkg/sysprof/network_darwin.go
Implement the changes suggested in https://github.com/lima-vm/lima/issues/189#issuecomment-911972759.
`env.*` settings from `lima.yaml` will override system settings.
Process environment during instance creation override all.
Fixes https://github.com/lima-vm/lima/issues/189#issuecomment-911972759
=> Setup proxy environment variables from system settings

cmd/limactl/start.go
=> Implement starting instances from a HTTP URL

pkg/cidata/cidata.TEMPLATE.d/boot.sh
Before trying to append new things to it
Think I only had `/etc/profile` around ?
So it failed the boot.sh shell script...
=> Make sure that environment file exists

Makefile
So "make install" failed on Ubuntu (and Debian)
`/bin/sh -> dash`
See https://github.com/lima-vm/lima/issues/291#issuecomment-933782381
=> Make scripts use bourne shell and not bash

README.md, cmd/lima-guestagent/daemon_linux.go, go.mod, go.sum, pkg/guestagent/guestagent_linux.go
iptables is scanned only when NETFILTER_CFG audit event was observed in the last minute.
Previously, iptables was scanned every 3 seconds.
`/proc/net/tcp` is still scanned every 3 seconds.
Fix #258
=> guestagent: watch NETFILTER_CFG audit events to reduce polling

cmd/limactl/info.go, cmd/limactl/main.go, pkg/cidata/cidata.go, pkg/limayaml/default.yaml, pkg/limayaml/defaults.go, pkg/limayaml/limayaml.go, pkg/limayaml/validate.go
e.g.,
```yaml
containerd:
system: false
user: true
archives:
- location: "~/Downloads/nerdctl-full-X.Y.Z-linux-amd64.tar.gz"
arch: "x86_64"
digest: "sha256:..."
```
The default archive URL can be inspected with `limactl info`
```console
$ limactl info
{
"version": "v0.6.4-63-g8dfd9d8",
"defaultTemplate": {
"arch": "x86_64",
"images": [
{
"location": "~/Downloads/hirsute-server-cloudimg-amd64.img",
"arch": "x86_64"
},
{
"location": "~/Downloads/hirsute-server-cloudimg-arm64.img",
"arch": "aarch64"
},
{
"location": "https://cloud-images.ubuntu.com/hirsute/current/hirsute-server-cloudimg-amd64.img",
"arch": "x86_64"
},
{
"location": "https://cloud-images.ubuntu.com/hirsute/current/hirsute-server-cloudimg-arm64.img",
"arch": "aarch64"
}
],
"cpus": 4,
"memory": "4GiB",
"disk": "100GiB", …
```
=> yaml: support overriding the location of `nerdctl-full-X.Y.Z-linux-ARCH.tar.gz`

examples/archlinux.yaml, examples/debian.yaml, pkg/limayaml/defaults.go
https://github.com/containerd/nerdctl/releases/tag/v0.12.1
=> update nerdctl (v0.12.1), archlinux, debian

examples/docker.yaml, examples/podman.yaml, pkg/hostagent/hostagent.go, pkg/hostagent/port.go, pkg/hostagent/port_darwin.go, pkg/hostagent/port_others.go, pkg/limayaml/default.yaml, pkg/limayaml/defaults.go, pkg/limayaml/limayaml.go, pkg/limayaml/validate.go, pkg/store/filenames/filenames.go
This is an alternative to #367. It doesn't parse `/proc/net/unix` at all, but just sets up any configured socket forwards when the guestagent is started, and tears them down when the hostagent exits.
This is now my preferred implementation.
```console
$ limactl start --tty=false examples/docker.yaml
[...]
$ DOCKER_HOST=unix://$HOME/docker.sock docker info | grep -E 'Root|System'
Operating System: Ubuntu Impish Indri (development branch)
Docker Root Dir: /home/jan.linux/.local/share/docker
WARNING: Running in rootless-mode without cgroups. To enable cgroups in rootless-mode, you need to boot the system in cgroup v2 mode.
```
Fixes #221
=> Implement unix socket forwarding

examples/fedora.yaml, examples/singularity.yaml
This version no longer requires `legacyBIOS: true`.
=> examples/{fedora,singularity}.yaml: update Fedora to 35

README.md, docs/multi-arch.md, pkg/limayaml/defaults.go
Key features: Multi-platform mode, `nerdctl image encrypt`, Kubernetes-aware `nerdctl ps`, zsh completion
https://github.com/containerd/nerdctl/releases/tag/v0.13.0
I'll release Lima v0.7.3 after merging this.
=> nerdctl 0.13 ; add `./docs-multi-arch.md`

pkg/sshutil/sshutil.go
This fixes command complaints on clients using ssh v8.0, for instance, CentOS 8.4.
If you check the ChangeLog from [openssh release v8.1p1](https://mirror.fsrv.services/pub/OpenBSD/OpenSSH/portable/openssh-8.1p1.tar.gz) you will see the `Ciphers` syntax change is added there.
=> Chipers '^' syntax was added in v8.1 instead of v8.0

pkg/sshutil/sshutil.go, pkg/sshutil/sshutil_test.go
I use [Secretive](https://github.com/maxgoedjen/secretive) to manage SSH keys, and it defaults to `ecdsa-sha2-nistp256` algorithm. 
After following the instruction about [putting public key in your ~/.ssh/ directory](https://github.com/maxgoedjen/secretive/blob/main/FAQ.md#how-do-i-tell-ssh-to-use-a-specific-key), `limactl start` give these output
```
WARN[0000] [hostagent] public key "/Users/enihsyou/.ssh/id_rsa.pub" doesn't seem to be in ssh format 
WARN[0000] [hostagent] public key "/Users/enihsyou/.ssh/secretive.pub" doesn't seem to be in ssh format 
```
Those OpenSSH public key format should be picked up, so I learned from what [golang.org/x/crypto/ssh.ParsePublicKey](https://github.com/golang/crypto/blob/089bfa5675191fd96a44247682f76ebca03d7916/ssh/keys.go#L265) do to make a soft …
=> read ecdsa public keys to ssh-authorized-keys

examples/k8s.yaml, examples/nomad.yaml
Make k8s and nomad more similar to k3s
=> Remove default mounts for orchestrators

examples/podman.yaml
It seems like podman has issues using runc with cgroups v2.
So use crun instead, which is the podman default (with v2).
```go
if conf.Engine.OCIRuntime == "" {
conf.Engine.OCIRuntime = "runc"
// If we're running on cgroups v2, default to using crun.
if onCgroupsv2, _ := cgroups.IsCgroup2UnifiedMode(); onCgroupsv2 {
conf.Engine.OCIRuntime = "crun"
}
}
```
Closes #398
=> Use crun instead of runc for podman example

cmd/limactl/info.go
This is useful because the directory will have all symlinks resolved, so can be used to determine the path to a relative hostSocket.
=> Add LIMA_HOME to `limactl info`

README.md
GitHub's web UI provides a button you can click to copy the code
example.
I did that this morning but was surprised by an error from the leading
`$`.
By removing the leading `$`, users can copy it and have the command work
seamlessly.
=> docs: ensure install command just works

cmd/limactl/copy.go, pkg/sshutil/sshutil.go
This commit does not make use of URIs in scp command, this way lima stays compatible with legacy openssh clients (older than v8.0)
Signed-off-by: David Cassany <dcassany@suse.com>
=> Adapt scp source and target arguments for old openssh

Makefile
This is just an optional local step, to help avoid getting errors in CI later by checking locally first.
Closes #416
=> Run golangci-lint as part of lint target

cmd/limactl/list.go
=> Implement custom go format for list command

.github/workflows/test.yml, examples/archlinux.yaml, examples/debian.yaml, pkg/cidata/cidata.TEMPLATE.d/boot/40-install-containerd.sh, pkg/limayaml/defaults.go
https://github.com/containerd/nerdctl/releases/tag/v0.14.0
This release supports IPFS, but Lima does not install IPFS by default
=> nerdctl: update to v0.14.0; install bash completion; update {archlinux,debian}.yaml

examples/alpine.yaml
Also switches `qemu-aarch64` from Alpine repo to `tonistiigi/binfmt` to include additional patches, and install `qemu-x86_64` in the `aarch64` ISO.
=> Bump Alpine from 3.13.5 → 3.14.3

cmd/limactl/list.go
```console
$ limactl ls --list-fields
Arch
CPUs
Dir
Disk
Errors
HostAgentPID
Memory
Name
Networks
QemuPID
SSHLocalPort
Status
```
=> limactl --list-fields should list them in sort order

cmd/limactl/list.go, examples/docker.yaml, examples/podman.yaml, pkg/limayaml/default.yaml, pkg/limayaml/defaults.go, pkg/limayaml/validate.go, pkg/store/store.go
Based on the suggestion in https://github.com/lima-vm/lima/pull/324#issuecomment-942611305.
Update examples/docker.yaml to show how this can be used to construct the instance-specific path of forwarded sockets.
```console
$ export DOCKER_HOST=$(limactl list docker --format 'unix://{{.LimaHome}}/{{.Name}}/sock/docker')
$ docker info
```
When the port forwards don't specify an absolute path:
```yaml
portForwards:
- guestSocket: "/run/user/{{.UID}}/docker.sock"
hostSocket: docker
```
=> Add `IdentityFile` and `LimaHome` fields to `limactl list` format

docs/internal.md, pkg/cidata/cidata.TEMPLATE.d/boot/08-shell-prompt.sh, pkg/cidata/cidata.TEMPLATE.d/lima.env
=> Change the default prompt color from green to lime

Makefile
Might as well catch those locally instead
Seem to be getting the same GitHub warnings over and over, probably would be a good idea to check it locally first...
I am not sure if there is a better way to share tests, the other YAML looked pretty specific (including custom "actions")
Just don't want to waste test resources, on whitespace and typos.
=> Add make target for running more checks

README.md, examples/README.md, examples/rocky.yaml
CentOS 8 is going to reach EOL soon, so replace CentOS with Rocky.
I didn't choose CentOS 8 Stream, because it's not stable as the legacy CentOS 8, and yet it's not progressive as Fedora.
=> examples: centos.yaml (8.4) -> rocky.yaml (8.5)

examples/podman.yaml
- The mounting of home works OK now with crun
- The name of the instance is podman not docker
- Need to use --remote on Linux until podman v4
- Make the usage hints shorter and less scary
=> Update and simplify the podman example

cmd/limactl/list.go, examples/docker.yaml, examples/podman.yaml, pkg/limayaml/default.yaml, pkg/limayaml/defaults.go
`Dir` was already supported by `limactl list`, so the `InstanceDir` is redundant. It was never part of a release, so can be removed.
For `hostSocket` this commit renames `InstanceDir` to `Dir`, as again there never was a release supporting `InstanceDir` either.
Updated docker and podman examples to match.
=> Replace `InstanceDir` with `Dir`

README.md
I see `Help wanted` on README.
I was interested in `Test on ARM Mac`, so I accessed it, but closed (solved?)
I deleted it because I thought it was not good for the solved issue to remain.
=> Delete closed issue link on help wanted section

examples/docker.yaml, examples/podman.yaml
They use new templating variables that don't exist in older releases.
Ref https://github.com/lima-vm/lima/pull/462#pullrequestreview-826003326
=> Fix required version for examples/{docker,podman}.yaml

pkg/osutil/dns_darwin.go, pkg/sysprof/network_darwin.go
It is not clear how/why this can happen, but we have seen at least 2 reports from users where a missing port was encoded as an empty string, and not as the number 0. It is unclear if on those systems non-0 ports would be encoded as strings or numbers, so this commit will handle both.
Fixes #403
=> Allow Proxy ports to be marshalled as strings

go.mod, go.sum, pkg/cidata/cidata.go, pkg/hostagent/hostagent.go, pkg/limayaml/default.yaml, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go, pkg/limayaml/load.go, pkg/limayaml/validate.go, pkg/qemu/qemu.go, pkg/start/start.go, pkg/store/filenames/filenames.go, pkg/store/instance.go
Stored inside the `_config` directory, they provide defaults for all instances stored under the same `LIMA_HOME`. Settings from `override.yaml` take precedence over the instance settings themselves:
```console
$ cat ~/.lima/_config/override.yaml
mounts:
- location: "~"
writable: true
- location: /Volumes/ThunderBlade
writable: true
networks:
- lima: shared
```
This make the home mount writable, adds a second mount point (because I have symlinks that point to an SSD array), and adds a vmnet IP address to *every* instance I start, without me having to modify the `examples/*.yaml` file when I create the instance.
The settings could have been in `_config/default.yaml` too, except making `~` writable wouldn't work because we make it explicitly readonly in our sample configs.
This mechanism …
=> Implement support for global default.yaml and override.yaml configs

cmd/limactl/shell.go, pkg/cidata/cidata.TEMPLATE.d/boot/11-colorterm-environment.sh
If the variable is set on the host, forward it.
Typical value if set would be COLORTERM=truecolor
Closes #434
=> Add COLORTERM to the lima shell environment

pkg/qemu/qemu.go
Update to use a more friendly version USB that works with aarch64
Notes:
https://qemu-project.gitlab.io/qemu/system/devices/usb.html
```
XHCI controller support
QEMU has XHCI host adapter support. The XHCI hardware design is much more virtualization-friendly when compared to EHCI and UHCI, thus XHCI emulation uses less resources (especially CPU). So if your guest supports XHCI (which should be the case for any operating system released around 2010 or later) we recommend using 
```
Signed-off-by: Jason W. Ehrlich <jwehrlich@outlook.com>
=> XHCI over EHCI for better performance as well as aarch64 support

pkg/qemu/qemu.go
This change will use qemu64 cpu for better emulation
and add some extra parameters like tcg accel and
force multi threading where multiple host threads will
be used for vcpus according to qemu documentation.
Added few more extra parameters which are used by
UTM for better emulation of x86_64
=> Fix #471: Improve x86_64 emulation on arm64 platform

pkg/hostagent/mount.go, pkg/limayaml/default.yaml, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go
This update will allow for symbolic links to be followed in mounts in sshfs.
=> Enabled symbolic link following in mounts

pkg/cidata/cidata.go
Previously this replacement was only applied to values from the current process environment. Now it also applies to system proxy settings, and values from the `env` section of `lima.yaml`.
=> Replace localhost in proxy settings with gateway address

examples/alpine.yaml, examples/archlinux.yaml, examples/debian.yaml, examples/docker.yaml, examples/fedora.yaml, examples/opensuse.yaml, examples/podman.yaml, examples/rocky.yaml, examples/singularity.yaml, examples/ubuntu.yaml, examples/vmnet.yaml, pkg/limayaml/default.yaml
Setting the fields to `null` instead makes them overridable via the `_config/default.yaml` mechanism.
For example, I want to make the home directory writable by default. Right now the only mechanism is:
```console
$ cat ~/.lima/_config/override.yaml
mounts:
- location: "~"
writable: true
```
But that means it is now impossible to make the home directory read-only in a specific VM; `override.yaml` always takes precedence. With the changes in this PR, the setting above can be moved to `default.yaml`, and can still be overridden by individual VMs.
=> Don't include default settings in example configs

Makefile
This patch removes $(DEST)/bin/nerdctl only when it is a symlink to nerdctl.lima.
=> remove $(DEST)/bin/nerdctl only when it is a symlink to nerdctl.lima

examples/docker.yaml, examples/podman.yaml, examples/singularity.yaml
lima will automatically pick an unused port.
Fixes #511
=> Don't set localPort in example configs

examples/k8s.yaml
Makes it easier to troubleshoot, should the "pull" fail.
Also makes the total cluster startup time more accurate.
Closes #521 
----
```console
anders@lima-k8s:~$ sudo nerdctl -n k8s.io images
REPOSITORY                            TAG                                                                 IMAGE ID        CREATED        PLATFORM       SIZE
k8s.gcr.io/coredns/coredns            v1.8.6                                                              5b6ec0d6de9b    3 hours ago    linux/amd64    45.1 MiB
k8s.gcr.io/coredns/coredns            <none>                                                              5b6ec0d6de9b    3 hours ago    linux/amd64    45.1 MiB
k8s.gcr.io/etcd                       3.5.1-0                                                             64b9ea357325    3 …
```
=> Download the needed images before kubeadm init

examples/k3s.yaml, examples/k8s.yaml
A bit of mismatch between k3s and k8s, and needs better documentation...
Make it easier to set up user config, and make `sudo kubectl` work as well.
i.e. running directly on the guest, is _supposed_ to require sudo
running remotely from the host, is configured to **not** use sudo
----
k3s, when not using `sudo`
```
WARN[0000] Unable to read /etc/rancher/k3s/k3s.yaml, please start server with --write-kubeconfig-mode to modify kube config permissions 
error: error loading config file "/etc/rancher/k3s/k3s.yaml": open /etc/rancher/k3s/k3s.yaml: permission denied
```
k8s, without $KUBECONFIG
```
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
=> Running kubectl requires using sudo kubectl

docs/network.md, pkg/networks/commands_test.go, pkg/networks/networks.go, pkg/networks/networks.yaml
The "staff" group only includes local accounts whereas "everyone" also includes accounts from directory services.
See also https://github.com/rancher-sandbox/rancher-desktop/issues/1152
=> Use "everyone" group instead of "staff"

examples/k8s.yaml
Need to use "sudo kubectl" now, to get the config...
It was hanging forever, trying to run `kubectl version`:
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
The config was moved to be root-only, in a5427ddca0f87cf60235400feeac514782f57b80
`/root/.kube/config`
Add some descriptions, instead of just "user probe".
```
INFO[0028] [hostagent] Waiting for the optional requirement 1 of 5: "systemd must be available" 
INFO[0028] [hostagent] Waiting for the optional …
```
=> Fix the probe for kubernetes example

examples/k3s.yaml, examples/k8s.yaml
Currently this information is hidden in the YAML file.
Show "actionable" output, similar to docker and podman.
Instead of: https://github.com/lima-vm/lima/pull/516
See: https://github.com/lima-vm/lima/issues/514#issuecomment-1008290440
=> Add message on how to run kubectl remotely

pkg/guestagent/guestagent_linux.go, pkg/guestagent/timesync/timesync_linux.go
Addresses #355
Running qemu guest agent alone doesn't solve the problem. With that approach, there must be an actor on the host side which catches wakeup events and executes RPC calls on the guest agent socket. As it stands, lima doesn't have any permanently running process to relay wake up events.
This PR offers different approach. It turns out that hardware clock device (`/dev/rtc0`) forwarded into a guest by QEMU always contains correct host time. The PR adds a loop into lima guest agent. That loop periodically checks the difference between hw clock time and system time. If the diff turns out to be over certain limit (hardcoded 5 seconds for now), the loop launches time sync from hw clock to system time.
=> Add hwclock sync loop to the guestagent

pkg/hostagent/mount.go
* abiosoft/colima#99
sshfs caching can cause asynchronous behaviors that aren't very happy, as discussed in https://stackoverflow.com/questions/3671350/any-way-to-eliminate-time-lag-with-sshfs
This adds the `cache=no` option to sshfs mounts to prevent this issue
In my case, a [ddev](https://github.com/drud/ddev) test was adding a bunch of files to a mounted directory before starting a container that bind-mounted them. On the way up, it tried to access those files inside the container and got interesting behaviors where the files were listable, but not yet readable. SO
```
file /mnt/ddev_config/.homeadditions/.composer/auth.json
/mnt/ddev_config/.homeadditions/.composer/auth.json: regular file, no read permission
```
but
```
cat /mnt/ddev_config/.homeadditions/.composer/auth.json
cat: …
```
=> Don't cache sshfs directory, fixes abiosoft/colima#99

cmd/limactl/debug.go, pkg/cidata/cidata.go, pkg/hostagent/dns/dns.go, pkg/hostagent/hostagent.go, pkg/limayaml/default.yaml, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go, pkg/limayaml/validate.go
They don't work over the SLIRP interface, and sometimes don't even work over a bridged vmnet interface.
See also https://github.com/rancher-sandbox/rancher-desktop/issues/1193
This PR deprecates the `useHostResolver` setting and replaces it with `hostResolver.enabled`. The old setting can still be used, but if the new property is set, any old setting in the same file is being ignored. Generating proper warnings gets pretty complex when the interaction between `default.yaml`, `lima.yaml`, and `override.yaml` have to be considered.
It could be argued that `HostResolver.LookupIPv6` should default to `true` for compatibility with previous releases. However, given that it seems to be broken in some setups, disabling IPv6 by default seems like a safer choice to me.
Also includes one bug fix for …
=> HostResolver shouldn't return IPv6 addresses by default

pkg/limayaml/defaults.go
https://github.com/containerd/nerdctl/releases/tag/v0.16.0
=> nerdctl: update to v0.16.0

pkg/hostagent/mount.go, pkg/limayaml/default.yaml, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go
Requested at https://github.com/lima-vm/lima/pull/556#issuecomment-1016111354, replaces #556.
=> Make sshfs caching configurable

.github/ISSUE_TEMPLATE/config.yml, README.md
Rancher Users slack has `#lima` channel, colocated with `#rancher-desktop` channel (Lima is not Rancher's product)
- New account: https://slack.rancher.io/
- Login: https://rancher-users.slack.com/
=> Add the Slack link

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yaml
https://github.com/lima-vm/lima/issues/new/choose was only showing the Slack link
Fix #582
=> Fix .github/ISSUE_TEMPLATE

examples/docker.yaml, pkg/start/start.go
- Commit 1: `start.ShowMessage: remove the logrus INFO header, for ease of copypasting`
- Commit 2: `examples/docker.yaml: recommend CLI context, not DOCKER_HOST env var`
Example output:
```console
$ limactl start ./examples/docker.yaml 
? Creating an instance "docker" Proceed with the default configuration
INFO[0001] Attempting to download the image from "https://cloud-images.ubuntu.com/impish/current/impish-server-cloudimg-amd64.img"  digest=
INFO[0002] Using cache "/Users/suda/Library/Caches/lima/download/by-url-sha256/ac74da77a6828e35de7edaa06fdbb33d12ef97cce2726550017e3c1066c88fb1/data" 
INFO[0003] [hostagent] Starting QEMU (hint: to watch the boot progress, see "/Users/suda/.lima/docker/serial.log") 
INFO[0003] SSH Local Port: 58833                        
INFO[0003] [hostagent] …
```
=> start.ShowMessage: remove the logrus INFO header, for ease of copypasting

README.md, cmd/limactl/edit.go, cmd/limactl/main.go, cmd/limactl/start.go
Signed-off-by: ye.sijun <junnplus@gmail.com>
Fixes: https://github.com/lima-vm/lima/issues/190
=> Add edit command

pkg/limayaml/default.yaml, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go
This was changed to `false` in lima 0.8.1:
* https://github.com/lima-vm/lima/pull/538
It has generated multiple reports of breaking PHP package manager, unit tests, and file system access itself:
* https://github.com/lima-vm/lima/pull/556
* https://github.com/abiosoft/colima/issues/129
* https://github.com/rancher-sandbox/rancher-desktop/issues/1349
Given that the use cases that triggered the change in #538 were observed in automated environment / CI, and that the PHP breakages happens to people using Lima for interactive development, I think the default should be reverted.
Closes #600
=> Change default for `mounts.sshfs.cache` to `true`

pkg/limayaml/defaults.go
Fixes several `nerdctl login` regressions: https://github.com/containerd/nerdctl/releases/tag/v0.16.1
- - -
**Note**: Upgrading `lima` does not automatically upgrade `nerdctl` in the existing instances.
To upgrade `nerdctl`, recreate a new Lima instance, or replace `/usr/local/bin/nerdctl` binaries in the existing instance manually:
- https://github.com/containerd/nerdctl/releases/download/v0.16.1/nerdctl-0.16.1-linux-amd64.tar.gz (Intel)
- https://github.com/containerd/nerdctl/releases/download/v0.16.1/nerdctl-0.16.1-linux-arm64.tar.gz (ARM)
=> nerdctl: update to v0.16.1 (Fixes several `nerdctl login` regressions)

README.ja.md, README.md
This PR includes:
- Translated README (ja_JP)
With this translated README, Japanese language users will easily access Lima.
--------------------------------------------------
Signed-off-by: KOSHIKAWA Kenichi <reishoku.misc ~~@~~ pm.me>
=> Add Japanese translation of README

README.ja.md, README.md, examples/README.md, examples/almalinux.yaml
This PR contains:
- example YAML files of AlmaLinux VM
I've confirmed on my machine that AlmaLinux works with Lima.
----------------------------
Signed-off-by: KOSHIKAWA Kenichi <reishoku.misc ~~@~~ pm.me>
=> examples: Add AlmaLinux to Lima 

cmd/limactl/shell.go, hack/test-example.sh
Addresses https://github.com/lima-vm/lima/issues/632.
I haven't tested very thoroughly, and may be making some incorrect assumptions about how shellescape works, but I can confirm that this at least fixes the `lima bash -c "$(echo -e '\n\techo balls\n')"` example for me.
=> Fix SSH command escaping

.cirrus.yml, examples/README.md
The "Tier 1" yamls are regularly tested on the CI. Other yamls are tested only occasionally and manually.
The following yamls are in the "Tier 1" category:
- default.yaml
- alpine.yaml
- archlinux.yaml
- debian.yaml
- fedora.yaml
- opensuse.yaml
- vmnet.yaml
=> examples: split the examples to "Tier 1" and others

README.md
Add debugging guide to help Rancher Desktop users:
```
LIMA_HOME="$HOME/Library/Application Support/rancher-desktop/lima" "/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl" shell 0
```
Note that the path may differ in a future version of Rancher Desktop.
=> README.md: add debugging guide for Rancher Desktop users

examples/podman.yaml
Sync the podman example, with the docker example.
Copy the example changes that were sneaked into:
* #595
commit 1e45f784168ec9615f195bb57a1213065d47aeff
Note: using the environment variables still _works_ just fine, so they are left in the comments.
Also using the new podman example, instead of running a docker example which was confusing.
https://en.wikipedia.org/wiki/Let%27s_Call_the_Whole_Thing_Off
🎶 "You like crun, I like runc. You say buildah, I say builder. ..." 
----
```
------
docker context create lima --docker "host=unix:///home/anders/.lima/docker/sock/docker.sock"
docker context use lima
------
```
```console
$ docker context list
NAME      DESCRIPTION …
```
=> podman: use connection instead of CONTAINER_HOST

pkg/limayaml/default.yaml, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go, pkg/limayaml/validate.go, pkg/qemu/qemu.go, pkg/store/instance.go
closes: https://github.com/lima-vm/lima/issues/592
=> add cpuType for specify cpu

cmd/limactl/start.go
Improvements:
* Don't warn about empty files
* Don't show an extra empty line at the end of the file
* Don't show empty lines with trailing whitespace as "# \n"
It was really the trailing whitespace on empty lines that made me write this, as they show up in bright red in my editor. 😄
=> Cleanup default and override warning in `limactl edit`

pkg/limayaml/default.yaml, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go, pkg/limayaml/validate.go, pkg/qemu/qemu.go, pkg/store/instance.go
That way a template lima.yaml can specify alternate cpu types for multiple archs. Also makes it possible to specify defaults and overrides for cpu type globally.
Fixes #647
=> Make cpuType a map instead of a single value

pkg/limayaml/defaults.go
https://github.com/containerd/nerdctl/releases/tag/v0.17.0
=> nerdctl: update to v0.17.0

hack/test-port-forwarding.pl, pkg/hostagent/port.go, pkg/limayaml/default.yaml, pkg/limayaml/defaults.go, pkg/limayaml/limayaml.go, pkg/limayaml/validate.go
When `guestIPMustBeZero` is set the rule will only match if the bind is against literal `0.0.0.0` and not any other interface.
To forward any ports bound to `0.0.0.0` in the guest to `0.0.0.0` on the host, but any other ports bound to `127.0.0.1` only to localhost on the host use these rules:
```yaml
portForwards:
- guestPortRange: [1, 65535]
guestIPMustBeZero: true
hostIP: "0.0.0.0"
- guestPortRange: [1, 65535]
guestIP: "127.0.0.1"
hostIP: "127.0.0.1"
```
Fixes #658
=> Add portForwards.guestIPMustBeZero property

cmd/limactl/debug.go, examples/docker.yaml, pkg/cidata/cidata.TEMPLATE.d/boot/06-etc-hosts.sh, pkg/hostagent/dns/dns.go, pkg/hostagent/hostagent.go, pkg/limayaml/default.yaml, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go
This is an alternative to adding static names to `/etc/hosts` on the **host**, to make them available inside containers running in the guest. In addition this change allows creating aliases to `host.lima.internal` to point to the host gateway from inside the guest.
Manual testing with `examples/docker.yaml` with these changes:
```yaml
hostResolver:
hosts:
host.docker.internal: host.lima.internal
cname.docker.internal: host.docker.internal
guest.internal: 127.1.1.1
```
Testing inside an Alpine container running on Docker:
```console
$ docker context create lima --docker "host=unix:///Users/jan/.lima/docker/sock/docker.sock"
$ docker context use lima
$ docker run -it --rm alpine
/ # nslookup host.docker.internal
Server:		10.0.2.3
Address:	10.0.2.3:53
Non-authoritative answer: …
```
=> Allow adding static names to hostresolver

pkg/store/store.go
Only treat directories in limadir as instances.
This is my local limadir, where I stored custom `docker.yaml` and `podman.yaml`:
```bash
$ ls -1 ~/.lima
_config
docker
docker.yaml
podman.yaml
```
Here the `limactl ls` command behaves unexpected and treats these files as instances:
```bash
$ limactl list
WARN[0000] instance "docker.yaml" has errors             errors="[open /Users/jwhb/.lima/docker.yaml/lima.yaml: not a directory]"
WARN[0000] instance "podman.yaml" has errors             errors="[open /Users/jwhb/.lima/podman.yaml/lima.yaml: not a directory]"
NAME           STATUS     SSH                ARCH      CPUS    MEMORY    DISK      DIR
docker         Running    127.0.0.1:57265    x86_64    4       4GiB      100GiB    /Users/jwhb/.lima/docker
docker.yaml               127.0.0.1:0 …
```
=> Fix `limactl ls` treating files in limadir as instances

.cirrus.yml, .github/workflows/test.yml, hack/test-example.sh, hack/test-port-forwarding.pl, pkg/guestagent/iptables/iptables.go, pkg/guestagent/iptables/iptables_test.go
The current logic pretends it only applies to `127.0.0.1`, which means the new `guestIPMustBeZero` rule does not detect it properly.
This is a problem with `nerdctl` and `containerd` on Alpine. It works "by accident" on Ubuntu because the port was also bound to `[::]`, which had an entry in `/proc/net/tcp6`.
This issue does not affect moby because moby doesn't rely on `iptables` rules but has proper entries in `/proc/net/tcp`.
=> iptables rule without an ip range applies to all interfaces

.github/workflows/test.yml
It is different from the other examples because it doesn't use systemd and cloud-init, and also boots from an ISO and uses a separate data volume. So it makes sense to test it on both Linux and macOS.
=> Add Alpine to the macOS test matrix

README.md
Adding a note as I and others have thought something is buggy with networking due to testing with `ping`.
https://github.com/abiosoft/colima/issues/140#issuecomment-1040900537
=> Document ping doesn't work due to SLIRP

hack/test-port-forwarding.pl
=> Use system_profiler fallback if hostname address cannot be determined

docs/internal.md, pkg/cidata/cidata.TEMPLATE.d/boot.sh, pkg/cidata/cidata.TEMPLATE.d/boot/20-rootless-base.sh, pkg/cidata/cidata.TEMPLATE.d/boot/40-install-containerd.sh, pkg/cidata/cidata.TEMPLATE.d/util/compare_version.sh
The real overlayfs can be safely used on kernel >= 5.13.
Instances created with older releases of Lima will continue to use fuse-overlayfs.
Fix #383
=> nerdctl: use fuse-overlayfs only when kernel < 5.13

pkg/cidata/cidata.TEMPLATE.d/boot/40-install-containerd.sh, pkg/limayaml/defaults.go
When the timestamp of `/mnt/lima-cidata/nerdctl-full.tgz:bin/nerdctl` is newer than
`/usr/local/bin/nerdctl`, containerd/nerdctl is automatically upgraded.
Drawback: increases boot time by 4-5 seconds.
Fix #303
- - -
Also bumps up the default nerdctl version to 0.17.1: https://github.com/containerd/nerdctl/releases/tag/v0.17.1
=> cidata: automatically upgrade existing containerd/nerdctl ; nerdctl: update to v0.17.1

examples/README.md, examples/oraclelinux.yaml, pkg/cidata/cidata.TEMPLATE.d/boot/30-install-packages.sh
Oracle's yum repos are fairly slow for me so this sometimes times out. More problematically, the containerd install portion doesn't work on ol8 and I haven't quite tracked the problem down yet.
=> Add support for oracle linux 8.

pkg/qemu/qemu.go
The HVF patch has been already merged in the upstream
=> aarch64: remove outdated hint

pkg/cidata/cidata.TEMPLATE.d/boot/30-install-packages.sh
Repo flag will turn on a repo like enablerepo, but also limits the dnf
action to only use the repos specified by the repo flags. This is
necessary for Oracle Linux due to excessively slow metadata updates
causing vm start to timeout.
Signed-off-by: Chris Perelstein <chris.perelstein@gmail.com>
=> Use repo instead of enablerepo for Oracle Linux.

pkg/qemu/qemu.go
- QEMU >= 7.0 requires highmem=off NOT to be set, otherwise fails with "Addressing limited to 32 bits, but memory exceeds it by 1073741824 bytes"
- QEMU <  7.0 requires highmem=off to be set, otherwise fails with "VCPU supports less PA bits (36) than requested by the memory map (40)"
See #680 and #24
Fix #680
=> aarch64: unset highmem=off for QEMU >= 7.0

examples/buildkit.yaml, examples/default.yaml, examples/docker.yaml, examples/faasd.yaml, examples/k3s.yaml, examples/k8s.yaml, examples/nomad.yaml, examples/podman.yaml, examples/ubuntu-lts.yaml, examples/ubuntu.yaml, examples/vmnet.yaml, pkg/start/start.go
Ubuntu kernel 5.13.0-35.40 (5.4.0-103.117 for 20.04 LTS) is broken for ARM:
`EFI stub: ERROR: FIRMWARE BUG: kernel image not aligned on 64k boundary`
Until the issue gets resolved, it is highly recommended to run
`sudo apt-mark hold linux-image-$(uname -r)` to avoid upgrading the kernel.
See issue #712
=> Ubuntu: skip kernel 5.13.0-35.40 (5.4.0-103.117 for 20.04 LTS)

README.md, examples/buildkit.yaml, examples/default.yaml, examples/docker.yaml, examples/faasd.yaml, examples/k3s.yaml, examples/k8s.yaml, examples/nomad.yaml, examples/podman.yaml, examples/ubuntu-lts.yaml, examples/ubuntu.yaml, examples/vmnet.yaml, pkg/qemu/qemu.go, pkg/start/start.go
Homebrew's QEMU 6.2.0_1 contains the following commits to run recent Linux guests:
- qemu/qemu@ad99f64f `hvf: arm: Use macros for sysreg shift/masking`
- qemu/qemu@7f6c295c `hvf: arm: Handle unknown ID registers as RES0`
These commits are planned to be included in the upstream QEMU 7.0.0 (ETA: April 2022).
See Homebrew/homebrew-core#96743 for the further information.
=> Recommend QEMU 6.2.0_1 on M1 macOS

pkg/hostagent/dns/dns.go
A "correct" answer would be to set `handled = true` and return a NODATA response.
Unfortunately some older resolvers use a slow random source to set the transaction id.
This creates a problem on M1 computers, which are too fast for that implementation:
Both the A and AAAA queries might end up with the same id. Returning NODATA for AAAA is faster, so would arrive first, and be treated as the response to the A query.
To avoid this, we will treat an AAAA query as an A query when IPv6 has been disabled.
This way it is either a valid response for an A query, or the A records will be discarded by a genuine AAAA query, resulting in the desired NODATA response.
Packet capture with the old implementation:
```
1   0.000000 192.168.5.15 → 192.168.5.2  DNS 81 Standard query 0x0edd A …
```
=> Hostresolver: Treat AAAA queries as A queries when IPv6 is disabled

examples/archlinux.yaml
I've forked the official [`arch-boxes`](https://gitlab.archlinux.org/archlinux/arch-boxes/) project and modified it to create aarch64-friendly cloud-init images.
The full diff can be found here: https://github.com/mcginty/arch-boxes/compare/bc74609...v20220323
High-level changes:
* Use Arch Linux ARM repo and signing keys
* Add EFI support via `systemd-boot`
* Patch `cloud-init` package to build on Arch Linux ARM
I've tested this by running:
```
limactl start https://raw.githubusercontent.com/mcginty/lima/archlinux-aarch64/examples/archlinux.yaml
```
and the system spins up as expected, `limactl shell` connecting normally.
=> Arch Linux aarch64 image

pkg/cidata/cidata.TEMPLATE.d/boot/40-install-containerd.sh, pkg/limayaml/defaults.go
BuildKit daemon is now configured to use containerd worker, not OCI worker for efficiency and for supporting using local base images
https://github.com/containerd/nerdctl/blob/v0.18.0/docs/build.md#setting-up-buildkit-with-containerd-worker
=> nerdctl: update to v0.18.0; configure BuildKit with containerd worker

cmd/limactl/shell.go
This PR let lima uses the default shell set in Linux.
By using
```bash
chsh -s $(which zsh) $USER
```
The user can set default shell to zsh, and with this PR, lima will regard this setting and use the default shell by reading `/etc/passwd`.
=> regard linux default shell

cmd/limactl/shell.go
This allows to use a predictable shell for scripting, and also provides a way to recover an instance when the user shell has
been misconfigured:
```console
$ limactl shell --shell /bin/ash alpine uname -a
Linux lima-alpine 5.10.93-0-virt #1-Alpine SMP Thu, 27 Jan 2022 09:34:38 +0000 x86_64 Linux
```
This is a followup to https://github.com/lima-vm/lima/pull/775#pullrequestreview-932678689
I'm not happy about the repetition of the word "shell" in `limactl shell --shell /bin/sh ...`, but it still seems like the most appropriate name for the option.
<hr>
This part has been split off into #780
Also adds `LIMA_SHELL` support to the `lima` command:
```console
$ export LIMA_INSTANCE=alpine
$ lima sudo apk add fish
[...]
$ export LIMA_SHELL=/usr/bin/fish
$ lima
Welcome to fish, the friendly …
```
=> Add --shell option to limactl shell

cmd/lima, docs/internal.md
```console
$ export LIMA_INSTANCE=alpine
$ lima sudo apk add fish
[...]
$ export LIMA_SHELL=/usr/bin/fish
$ lima
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
jan@lima-alpine /U/jan>
```
Split off from #779.
=> Add LIMA_SHELL env var to lima command

examples/default.yaml, examples/experimental/9p.yaml, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go
=> 9p: use `fscache` by default for RO mounts

.github/workflows/test.yml
CI was failing due to the recent breaking change of git: https://github.com/git/git/commit/8959555cee7ec045958f9b6dd62e541affb7e7d9
> Cloning into 'vde_vmnet'...
> HEAD is now at a4b489e Merge pull request #40 from AkihiroSuda/dev
> git submodule update --init
> fatal: unsafe repository ('/Users/runner/work/lima/lima/vde_vmnet' is owned by someone else)
> To add an exception for this directory, call:
>
> 	git config --global --add safe.directory /Users/runner/work/lima/lima/vde_vmnet
> make: *** [install.vde-2] Error 128
=> CI: fix 'fatal: unsafe repository ('/Users/runner/work/lima/lima/vde_vmnet' is owned by someone else)'

examples/default.yaml, pkg/cidata/cidata.TEMPLATE.d/user-data, pkg/cidata/cidata.go, pkg/cidata/template.go, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go
=> Add trusted CA certificate support

examples/k8s.yaml
Make sure to pass an explicit cri socket for containerd.
Make sure to add the unix:// schema to the socket path.
Issue #792
By explicitly choosing containerd, it shouldn't try docker.
=> Fix the cri-socket in the k8s example

examples/k8s.yaml
The kubernetes installer (kubeadm) requires the other
packages, so look for it being installed instead...
It has dependencies on both kubectl and kubelet, as well
as cri-tools (crictl) and kubernetes-cni (/opt/cni/bin)
=> Look for kubeadm instead of kubectl for k8s

cmd/limactl/start.go, go.mod, go.sum
e.g., `limactl start template://deprecated/centos-7` creates an instance named `centos-7`
Fix #785
=> limactl start: support subdirectories

pkg/qemu/qemu.go
Closes #795
Closes #713
Adjust the memory to be <= 3 GiB, only when all the following conditions are met:
- Host OS   <  macOS 12.4
- Host Arch == arm64
- Accel     == hvf
- QEMU      >= 7.0
This adjustment is required for avoiding host kernel panic. The issue was fixed in macOS 12.4 Beta 1.
See https://gitlab.com/qemu-project/qemu/-/issues/903#note_911000975
- - -
- Hardware (e.g., `MacBookPro 2021, M1 Pro`): ...
- macOS Version (e.g., `12.3.1`): ...
- Test matrix:
| Guest memory       | 2 GiB | 4 GiB | 8 GiB |
| ------------------ | ----- | ----- | ----- |
| QEMU 6.2.0_1        | ...       | ...       | ...       |
| QEMU 7.0.0            | ...       | ...       | ...       |
QEMU 7.0.0 can be installed by running `brew install --build-from-source ./qemu.rb` with `qemu.rb` from …
=> [Test wanted] qemu: adjust the memory size for workarounding M1 panic

examples/k8s.yaml
See https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/
```
NAME       STATUS   ROLES                  AGE     VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE           KERNEL-VERSION      CONTAINER-RUNTIME
lima-k8s   Ready    control-plane,master   2m32s   v1.23.6   192.168.5.15   <none>        Ubuntu 22.04 LTS   5.15.0-25-generic   containerd://1.6.2
```
Closes #817
=> Set the kubelet cgroup driver to systemd (v2)

examples/k8s.yaml
Ubuntu LTS version was bumped from 20.04 to 22.04
Remove comment, since it is now same as "default"
=> Remove misleading stale comment about version

examples/k3s.yaml, examples/k8s.yaml
Easier to select multiple lines, without the "$ " prompt.
Separate the commands by dashes instead, like in docker.
----
Improves the output of PR #838 
```
default
<no message>
docker
------
docker context create lima --docker "host=unix:///home/anders/.lima/docker/sock/docker.sock"
docker context use lima
------
k8s
To run `kubectl` on the host (assumes kubectl is installed), run the following commands:
------
mkdir -p "/home/anders/.lima/k8s/conf"
export KUBECONFIG="/home/anders/.lima/k8s/conf/kubeconfig.yaml"
limactl shell k8s sudo cat /etc/kubernetes/admin.conf >$KUBECONFIG
kubectl ...
------
```
=> Use the new format of message for easy copy/paste

pkg/store/instance.go
This is necessary to be able to delete instances that fail YAML validation (e.g. because they have been created using a different branch).
I ran into this when I created a `riscv64` instance with the PR branch and tried to delete it with the `master` branch version:
```console
$ l --debug delete -f riscv64
DEBU[0000] Mixing "/Users/jan/.lima/_config/default.yaml" into "/Users/jan/.lima/riscv64/lima.yaml"
DEBU[0000] Mixing "/Users/jan/.lima/_config/override.yaml" into "/Users/jan/.lima/riscv64/lima.yaml"
INFO[0000] The QEMU process seems already stopped
INFO[0000] The host agent process seems already stopped
INFO[0000] Removing *.pid *.sock under ""
ERRO[0000] open : no such file or directory
INFO[0000] Deleted "riscv64" ("")
DEBU[0000] Mixing "/Users/jan/.lima/_config/default.yaml" into …
```
=> Make sure inst.Dir is set when store.Inspect returns no error

pkg/cidata/cidata.TEMPLATE.d/boot/05-persistent-data-volume.sh
With 9p and cloud-init, the mounts happen before the provisioning scripts execute. So by the time we move `/tmp` to `/mnt/data/tmp` the `/tmp/lima` directory is already mounted, blocking the move.
=> Unmount mount points under /tmp before moving to persistent volume

examples/k8s.yaml
This caused any pods not in kube-system to go
"pending" while looking for a worker node...
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#control-plane-node-isolation
=> The node taint was renamed with k8s 1.24

examples/default.yaml, pkg/hostagent/hostagent.go, pkg/hostagent/port_darwin.go, pkg/hostagent/port_others.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go, pkg/limayaml/validate.go
By default, the portForwards will be forwarded
from local (host) to remote (guest). Flag: `-L`
With reverse, the portForwards will be forwarded
from remote (guest) to local (host). Flag: `-R`
Only implemented for unix sockets at the moment.
I kept the confusing wording, of the logging entries.
Issue #834
Tested by forwarding a memcached socket from the host.
`memcached -s mc.sock`
```yaml
portForwards:
- guestSocket: "/tmp/mc.sock"
hostSocket: "{{.Home}}/mc.sock"
reverse: true
```
`lima sudo apt install -y libmemcached-tools`
`lima MEMCACHED_SERVERS=/tmp/mc.sock memcping`
----
ssh says:
`-L local_socket:remote_socket`
Specifies that connections to the given TCP port or Unix socket on the local (client) host are to be forwarded to the given host and port, or Unix socket, on the remote …
=> Enable reverse forwarding of portForwards

Makefile, cmd/docker.lima, cmd/podman.lima
These will call the clients, without having to clobber the global configuration.
~~You only need to run the **first** command from the "message", not the second:~~
<details>
<pre>
INFO[0128] Message from the instance "docker":          
------
docker context create lima --docker "host=unix:///home/anders/.lima/docker/sock/docker.sock"
docker context use lima
------
</pre>
<pre>
INFO[0018] Message from the instance "podman":          
To run `podman` on the host (assumes podman-remote is installed), run the following commands:
------
podman system connection add lima "unix:///home/anders/.lima/podman/sock/podman.sock"
podman system connection default lima
podman --remote run …
=> Add client wrappers for docker and podman, similar to nerdctl wrapper

pkg/limayaml/defaults.go
https://github.com/containerd/nerdctl/releases/tag/v0.20.0
This release adds the nerdctl builder debug command for interactive debugging of Dockerfile (https://github.com/containerd/nerdctl/pull/1049, thanks to @ktock).
See https://github.com/containerd/nerdctl/blob/v0.20.0/docs/builder-debug.md
=> nerdctl: update to v0.20.0

examples/almalinux.yaml, examples/alpine.yaml, examples/archlinux.yaml, examples/rocky.yaml
AlmaLinux 8.6 works well but Rocky Linux 8.6 (20220515) seems broken (https://bugs.rockylinux.org/view.php?id=102). Even lacks sudo.
Oracle Linux 8.6 images are not available yet: https://yum.oracle.com/oracle-linux-templates.html
=> templates: update alpine, archlinux, almalinux (but skip updating rocky)

pkg/cidata/cidata.TEMPLATE.d/boot/05-persistent-data-volume.sh
Conceptually `/root` is just `/home/root`, and we already persist `/home`, so wiping `/root` on each reboot doesn't make sense, as it can store config data from rootful nerdctl etc (and the shell history of the root user).
=> [alpine] Persist /root on data volume at /mnt/data/root

pkg/cidata/cidata.TEMPLATE.d/boot/20-rootless-base.sh
I've added .zshrc to the list of shell rc files where the default `CONTAINERD_SNAPSHOTTER` gets set. I've tested this and it fixes #862. This is my first PR in the project, so apologies if I've missed any steps.
=> Set required Containerd env vars in model zshrc - fixes #862

examples/default.yaml, pkg/cidata/cidata.TEMPLATE.d/lima.env, pkg/cidata/cidata.TEMPLATE.d/user-data, pkg/cidata/cidata.go, pkg/cidata/template.go, pkg/cidata/template_test.go, pkg/hostagent/mount.go, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go, pkg/qemu/qemu.go
Closes #659
Tested with both sshfs and 9p and confirmed that the mounts were configured in the location specified by `mounts[*].mountPoint`. 
eg:
```
mounts:
- location: "~/Movies"
mountPoint: "/movies"
```
=> Support configuring mount locations within guests

examples/podman.yaml
Ubuntu 22.04 provides podman 3.4.4 which is not compatible with podman 4 client that is provided by brew on macOS.
=> Use Fedora 36 to get podman 4

examples/singularity.yaml
The example doesn't work anymore, since kernel modules are not installed by default in new fedora (36):
`FATAL:   container creation failed: mount /proc/self/fd/3->/var/singularity/mnt/session/rootfs error: while mounting image /proc/self/fd/3: squashfs filesystem seems not enabled and/or supported by your kernel`
Make sure to install the kernel-modules version of the _current_ kernel-core, not for the latest available kernel.
----
```console
[anders@lima-singularity lima]$ sudo modprobe -v squashfs
insmod /lib/modules/5.17.5-300.fc36.x86_64/kernel/fs/squashfs/squashfs.ko.xz 
[anders@lima-singularity lima]$ singularity run docker://alpine
INFO:    Using cached SIF image
Singularity> 
```
=> Need squashfs kernel module installed for singularity

pkg/cidata/cidata.TEMPLATE.d/boot.sh, pkg/cidata/cidata.TEMPLATE.d/boot/11-colorterm-environment.sh, pkg/cidata/cidata.TEMPLATE.d/boot/25-guestagent-base.sh
Alpine doesn't use openrc-init (it uses busybox init) and has deleted it from the package in 3.16:
https://gitlab.alpinelinux.org/alpine/aports/-/commit/7a4d6d22cdb4696e93b3a0fce91e851c4db5366e
=> Check for /sbin/openrc-run instead of /sbin/openrc-init

examples/faasd.yaml
Fixes #880
Currently, the `faasd` template gets stuck while trying to run the `provision` script. This PR solves this issue by changing the `provision` mode from `system` to `user`.
The current script has an explanation on the usage in the header, as comments. I added a message at the end, based on those header comments.
Tested locally:
```
limactl start faasd.yaml
? Creating an instance "faasd" Proceed with the current configuration
INFO[0001] Attempting to download the image from "https://cloud-images.ubuntu.com/releases/22.04/release-20220420/ubuntu-22.04-server-cloudimg-amd64.img"  digest="sha256:de5e632e17b8965f2baf4ea6d2b824788e154d9a65df4fd419ec4019898e15cd"
INFO[0003] Using cache "/Users/corsair/Library/Caches/lima/download/by-url-sha256/62c871f6f494814b9c6555e6ac74e1e81c35ba6f12be …
```
=> Fassd template fix

examples/README.md, examples/experimental/apptainer.yaml
The new version is not yet available for fedora or centos,
but it will be available from EPEL after the 1.1.0 release.
https://github.com/apptainer/apptainer/releases/tag/v1.0.2
=> Add example for apptainer running on rocky

cmd/limactl/copy.go, cmd/limactl/shell.go, cmd/limactl/show_ssh.go, examples/default.yaml, pkg/hostagent/hostagent.go, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go, pkg/sshutil/sshutil.go
This allows people who have XQuartz installed to easily install and run X11 applications inside lima.
This is a nicer replacement for https://github.com/lima-vm/lima/pull/875 - it adds two new settings to the `ssh` section of the template - `forwardX11` and `forwardX11Trusted` correspond to the similarly-named ssh options, like `forwardAgent` does.
=> Allow forwarding X11 to VM

docs/internal.md, pkg/cidata/cidata.TEMPLATE.d/lima.env, pkg/cidata/cidata.go, pkg/cidata/template.go
This can be used by provisioning scripts to locate the mount point of the user's home directory. We can't just use `/Users/$LIMA_CIDATA_USER` because we don't know if the host is Linux or macOS, so it could be `/home/$LIMA_CIDATA_USER` or something completely custom. Also `$LIMA_CIDATA_USER` is the username inside the guest and might be set to `lima` if the username on the macOS host is not a valid Linux username.
Example usage to configure client certs for the docker daemon:
```shell
ln -s $LIMA_CIDATA_HOME_MOUNTPOINT/.docker/certs.d /etc/docker/certs.d
```
=> Add LIMA_CIDATA_HOSTHOME_MOUNTPOINT

pkg/sshutil/sshutil_others.go
Fixes build on platforms other than darwin and linux.
For instance: `GOOS=netbsd`, `GOOS=freebsd`
Issue #892
=> Remove nonexisting err from AES detection warning

pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go
This should be matching the qemu getAccel() values
Specifically, no acceleration on FreeBSD right now
Issue #892
=> Only use cpuType=host for OS with accel available

examples/archlinux.yaml
geo.mirror.pkgbuild.com is a GeoDNS mirror that points to sponsored mirrors.
This avoids the usage of Arch's infrastructure (mirror.pkgbuild.com) for large downloads.
See https://gitlab.archlinux.org/archlinux/infrastructure/-/merge_requests/522 for details.
=> examples: use the geo.mirror.pkgbuild.com mirror for Arch Linux

pkg/store/instance.go
There is no reason to let the user deal with template expansion when we can do this automatically after loading. This is especially useful in `limactl list` output:
```console
$ limactl ls -f '{{.Message}}' docker
------
docker context create lima --docker "host=unix:///Users/jan/.lima/docker/sock/docker.sock"
docker context use lima
------
```
See also https://github.com/lima-vm/lima/pull/838#issuecomment-1122020716
=> Always expand inst.Message field in store.Inspect

examples/README.md, examples/centos-stream.yaml, examples/experimental/centos-stream-9.yaml, pkg/cidata/cidata.TEMPLATE.d/boot/30-install-packages.sh
CentOS (Linux), downstream of RHEL:
https://centos.org/centos-linux/
CentOS Stream, upstream of RHEL:
https://centos.org/centos-stream/
---
This is a more tested variant of PR #856
* #856
Adressing some comments from Issue #342
* #342
Both distributions have the same CentOS identifier:
```
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
```
```
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
```
But Stream is always testing the _next_ Linux version.
=> Add examples for CentOS Linux and CentOS Stream both

cmd/limactl/show_ssh.go
Some ssh option are quoted because their arguments may contain spaces. These quotes must be passed to ssh and not removed by the shell, so this command can work:
```console
sh -c $(limactl show-ssh $INSTANCE)
```
Example output:
```console
ssh -o 'IdentityFile="/Users/jan/Library/Application Support/rancher-desktop/lima/_config/user"' ...
```
Without the extra single quotes, the `sh -c` command above fails with:
```
command-line line 0: garbage at end of line; "Support/rancher-desktop/lima/_config/user".
```
=> Protect quotes in show-ssh output

pkg/cidata/cidata.TEMPLATE.d/boot/05-persistent-data-volume.sh
Otherwise the data configured by cloud-init/lima-init may get lost if the instance is forcibly stopped (e.g. via `limactl stop -f`).
Example: `$HOME/.ssh/authorized_hosts` is lost (size 0):
Even though cloud-init/lima-init will re-create the file on next boot, the new version will be shadowed by the `/mnt/data/home/$USER.linux/.ssh` directory that will be mounted on top and the instance will remain
inaccessible.
=> Force sync after moving persistent directories to data volume

examples/alpine.yaml, examples/archlinux.yaml, pkg/limayaml/defaults.go
https://github.com/containerd/nerdctl/releases/tag/v0.21.0
TODO
- https://github.com/lima-vm/alpine-lima/pull/70
=> templates: update Arch Linux to 20220615.61815 ; nerdctl: update to v0.21.0

pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go
Instead use -cpu max, for everything available.
Affects NetBSD (NVMM) and Windows (WHPX)
Follow-up from #894
=> Not all OS with -accel has -cpu host option

pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go
On platforms that have an accelerator but `-cpu host` is not available fallbacks to `-cpu max` that enables all features supported by the accelerator in the current host.
This was noticed on NetBSD. What actually happened is that in `qemu.Cmdline()` if nothing adjust the CPU we will ends up with:
https://github.com/lima-vm/lima/blob/64106744775bf0e321e6a301f38c829ea5002557/pkg/qemu/qemu.go#L372
where `-accel` is currently hardcoded to `tcg` later in:
https://github.com/lima-vm/lima/blob/64106744775bf0e321e6a301f38c829ea5002557/pkg/qemu/qemu.go#L379.
And so no host accelerator is used in such case.
=> Fallbacks to `-cpu max` on native arch platforms that have an accelerator but do not support `-cpu host`

cmd/limactl/stop.go, pkg/networks/reconcile/reconcile.go, pkg/networks/validate.go, pkg/osutil/osutil_others.go, pkg/osutil/osutil_windows.go
Makes it easier to add windows portability
Compiles now, but probably doesn't work...
Issue #909
=> Gather all syscall use in the osutil helper

Makefile
It needs to be called `limactl.exe`, or it will silently fail exec.
Also replaced the examples symlink with yet another copy.
=> Add exe extension to the limactl binary on windows

pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/qemu/qemu.go
Doesn't work now, after adding 017a56ca10f0a867c73d2b06547302787ffddabc
Also needs to avoid falling back on tcg
----
Tested on Windows 10 (Pro), x64 (Intel)
Using Alpine Linux, and Alpine-Lima
=> whpx: Don't use -cpu max, add kernel-irqchip=off

examples/docker.yaml
The docker template suggests creating and using a context called "lima" each time a new VM is created. This, however, ends up with the following issue:
```bash
docker context create lima --docker "host=unix:///Users/jkremser/.lima/kep/sock/docker.sock"
context "lima" already exists
```
Instead, it would be nice to incorporate the name of the VM into the name of the context so that there is 1:1 relation and the previously mentioned issue is fixed. The output of the suggested commands looks like:
```
------
docker context create lima-kep --docker "host=unix:///Users/ab017z6/.lima/kep/sock/docker.sock"
docker context use lima-kep
------
```
If the `"name"` argument is not …
=> Suggest creating and using new docker context for each vm

examples/podman.yaml
Allows having more than one instance using podman.
Similar to change applied for the docker context.
Compare:
* https://github.com/lima-vm/lima/pull/935
Trying to keep docker and podman reasonably similar...
=> podman: Use different connections for different instances

cmd/limactl/main.go, cmd/limactl/shell.go, cmd/limactl/start.go, pkg/downloader/downloader.go
This enables terminal in shell and colored logs/download.
The interactive template selection is not implemented yet.
Issue #936
=> Add partial support for cygwin terminal on windows

pkg/cidata/template.go, pkg/hostagent/dns/dns_test.go, pkg/limayaml/defaults.go, pkg/limayaml/validate.go, pkg/networks/commands.go, pkg/networks/commands_darwin_test.go, pkg/networks/commands_test.go
After merging the other code fixes.
Only unit tests, not functional tests...
-----
```
--- FAIL: TestTemplate (0.00s)
template_test.go:26: assertion failed: error is not nil: field mounts[0] must be absolute, got "/Users/dummy"
--- FAIL: TestTemplate9p (0.00s)
template_test.go:54: assertion failed: error is not nil: field mounts[0] must be absolute, got "/Users/dummy"
FAIL
FAIL	github.com/lima-vm/lima/pkg/cidata	1.177s
--- FAIL: TestTXTRecords (0.07s)
--- FAIL: TestTXTRecords/test_TXT_records (0.07s)
dns_test.go:60: assertion failed: regex_check is false
FAIL
FAIL	github.com/lima-vm/lima/pkg/hostagent/dns	1.229s
--- FAIL: TestFillDefault (0.01s)
defaults_test.go:212: assertion failed: 
--- &y
+++ &expect
&limayaml.LimaYAML{
... // 12 identical fields
Containerd: {System: &false, User: …
```
=> Fix test failures on windows, mostly paths

pkg/osutil/user.go, pkg/osutil/user_test.go
Here is what it looks like with Wine, added a unit test:
```
time="2022-06-26T22:55:19+02:00" level=warning msg="local user \"UBUNTU\\\\anders\" is not a valid Linux username (must match \"^[a-z_][a-z0-9_-]*$\"); using \"lima\" username instead"
time="2022-06-26T22:55:19+02:00" level=warning msg="local uid \"S-1-5-21-0-0-0-1000\" is not a valid Linux uid (must be integer); using 4266656744 uid instead"
time="2022-06-26T22:55:19+02:00" level=warning msg="local gid \"S-1-5-21-0-0-0-513\" is not a valid Linux gid (must be integer); using 4266656257 gid instead"
time="2022-06-26T22:55:19+02:00" level=warning msg="local home \"C:\\\\users\\\\anders\" is not a valid Linux path (must match \"^[/a-zA-Z0-9_-]+$\"); using \"/c/users/anders\" home instead"
```
Closes #928
* #928
=> Add more fallbacks for LimaUser uid/gid/home

Makefile
Not building these by default, until it is more stable.
The zip is for windows-without-msys, i.e. no tar...
=> Add artifacts for windows (x86_64) target

pkg/qemu/qemu.go
I am working on a project where we need to forward devices into the qemu guest OS. ARM guests already get a USB hub, unfortunately, x86 doesn't. It would be great to add to each x86 vm an xhci usb hub as well. (All other usb related work can then happen through qmp/hmp (at some point it might be cool to have an easy way to find the path of the colima qmp socket, but for now we can just build the path on our own).
=> add usb hub to each vm

pkg/hostagent/dns/dns.go
I have made an error in my previous changes by always assigning the UDP port to the address, this fixes the issue along with a correct log message. 
Signed-off-by: Nino Kodabande <nkodabande@suse.com>
=> Assign appropriate port based on the network

examples/alpine.yaml, examples/archlinux.yaml, examples/buildkit.yaml, examples/debian.yaml, examples/default.yaml, examples/docker.yaml, examples/experimental/9p.yaml, examples/experimental/apptainer.yaml, examples/experimental/centos-stream-9.yaml, examples/experimental/riscv64.yaml, examples/faasd.yaml, examples/k3s.yaml, examples/k8s.yaml, examples/ubuntu.yaml, examples/vmnet.yaml, pkg/limayaml/defaults.go
https://github.com/containerd/nerdctl/releases/tag/v0.22.0
TODO
- https://github.com/lima-vm/alpine-lima/pull/75
=> templates: update archlinux, debian, ubuntu, centos-stream-9, apptainer, alpine; update nerdctl (0.22.0)

cmd/lima
The paths in the command are for the Linux virtual machine,
so we want remote unix paths instead of local windows paths.
Otherwise you get strange results from `lima`, such as:
`cat: 'C:/msys64/etc/os-release': No such file or directory`
----
See https://www.msys2.org/docs/filesystem-paths/#automatic-unix-windows-path-conversion
=> Avoid translating paths in MSYS2 shell wrapper

go.mod, go.sum, pkg/sshutil/sshutil_windows_amd64.go, pkg/sshutil/sshutil_windows_arm64.go
Avoids annoying warning about detection failed
=> Add AES detection for Windows using cpuid

.github/workflows/test.yml
Lima v0.8.0 no longer starts up with the default template as Ubuntu 21.10 reached EOL
Fix #991
=> CI: upgrading test: set the old ver to 0.10.0

.github/workflows/test.yml
This will only run the unit tests, not any integration tests.
For that, a real Windows machine (with Hyper-V) is needed...
=> Add github test for windows using wine

examples/default.yaml
Useful for writing cross-platform yaml files:
Platform | DisplayType
--- | ---
Darwin | cocoa
Linux | gtk
Windows | sdl
But is not a new display type, or anything...
=> Document the default option for video.display

examples/alpine.yaml, examples/archlinux.yaml, pkg/limayaml/defaults.go
https://github.com/containerd/nerdctl/releases/tag/v0.22.1
https://github.com/containerd/nerdctl/releases/tag/v0.22.2
=> nerdctl: update to v0.22.2 ; templates: update archlinux, alpine-lima

examples/experimental/opensuse-tumbleweed.yaml, pkg/cidata/cidata.TEMPLATE.d/boot/30-install-packages.sh
This merge request is related to the issue #1011 and is aiming at being able to user OpenSuse with the current script approach to package manager detection
=> Add aarch64 opensuse tumbleweed

examples/k8s.yaml
Kubernetes requires some changes to the default containerd
configuration, for the cgroup driver and the sandbox image.
Update documentation links, to show what is prerequisites
and container runtime configuration and what is `kubeadm`.
Closes #1036
----
Reviewer Note:
The documentation for CRI and CNI has been decoupled from the Kubernetes installation documentation,
so it can be a bit hard to find. Updated the comments, to make it more obvious what steps come from where...
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/
=> Set the sandbox_image for the k8s example

examples/k8s.yaml
The manifest for 0.19 was broken again, wrong images.
~~Might as well use the latest, same as with kubeadm ?~~
Closes #1034 
EDIT: Using specified version again, instead of "master"
=> Use the latest and greatest flannel CNI for k8s

examples/alpine.yaml, examples/archlinux.yaml, examples/buildkit.yaml, examples/debian.yaml, examples/default.yaml, examples/docker-rootful.yaml, examples/docker.yaml, examples/experimental/9p.yaml, examples/experimental/riscv64.yaml, examples/faasd.yaml, examples/k3s.yaml, examples/k8s.yaml, examples/ubuntu.yaml, examples/vmnet.yaml, pkg/limayaml/defaults.go
https://github.com/containerd/nerdctl/releases/tag/v0.23.0
=> Update nerdctl (0.23.0), Arch Linux, Debian, Ubuntu, Alpine

.github/workflows/test.yml, README.md, docs/network.md, examples/default.yaml, examples/vmnet.yaml, hack/test-example.sh, pkg/hostagent/hostagent.go, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go, pkg/limayaml/validate.go, pkg/networks/commands.go, pkg/networks/commands_darwin_test.go, pkg/networks/commands_test.go, pkg/networks/config.go, pkg/networks/networks.go, pkg/networks/networks.yaml, pkg/networks/reconcile/reconcile.go, pkg/networks/sudoers.go, pkg/networks/validate.go, pkg/qemu/qemu.go
socket_vmnet is similar to vde_vmnet but does not depend on VDE.
https://github.com/lima-vm/socket_vmnet
See `docs/network.md` for how to create `networks.yaml` with `socketVMNet`.
When both `socketVMNet` and `vdeVMNet` (deprecated) are present in the YAML, `socketVMNet` is chosen.
- - -
Mode                 | Shared (NAT) | Bridged
---------------|--------------|----------
socket_vmnet | 0.66 Gbps      | 1.23 Gbps
vde_vmnet      | 0.27 Gbps      | 0.31 Gbps
Tested on MacBook Pro 2020 (Intel), macOS 12
Lima commit 8db31e8087272da1c848d5d6d23f680004ad7d45 , socket_vmnet v1.0.0-alpha.0, vde_vmnet v0.6.0
Known issue: the throughput of the Shared (NAT) interface can be slower when both the Shared (NAT) and the Bridged interfaces are configured
=> vmnet: Support socket_vmnet; deprecate vde_vmnet

pkg/hostagent/hostagent.go
Unfortunately I could not determine what triggered this error, but I've run into it while testing Rancher Desktop with socket_vmnet, and qemu failed because it had a `-netdev` option without `id` in the value (there was no value at all).
I've not been able to reproduce it again since I fixed the error reporting.
=> Return error when template expansion fails

.github/ISSUE_TEMPLATE/config.yml, README.ja.md, README.md
`#lima` channel in the CNCF Slack
- New account: https://slack.cncf.io/
- Login: https://cloud-native.slack.com/
=> README.md: #lima channel is now hosted on CNCF Slack

examples/README.md, examples/podman-rootful.yaml
For completeness, when compared with docker-rootful
There is no "podman" group, so use `sudo podman`
----
Note: podman is daemonless, so shell doesn't use sock
If you really wanted to, you could add a `--remote` flag...
=> templates: add podman-rootful

examples/experimental/apptainer.yaml
Now has support for rootless containers (user namespaces)
https://github.com/apptainer/apptainer/releases/tag/v1.1.0
Add support for aarch64
Currently only from EPEL
=> templates: update apptainer to 1.1.0

examples/default.yaml, pkg/cidata/cidata.TEMPLATE.d/user-data, pkg/cidata/cidata.go, pkg/cidata/template.go, pkg/limayaml/limayaml.go, pkg/limayaml/validate.go
Allows users to customize their early boot workflow by specifying `bootCmds`. These commands are run by `cloud-init-local.service`, which runs before `cloud-init.service` (which only starts after the network is up), and allow users to disable services (as in the example) or run other commands early on in the boot process. [More info here](https://cloudinit.readthedocs.io/en/latest/topics/examples.html#run-commands-on-first-boot).
Resolves one of the proposals in #1093
=> add "boot" provisioning script mode

pkg/qemu/qemu.go
This would enable trimming of QEMU virtual disks, by adding the `discard=on` argument to `-drive` flag for `basedisk` or `diffdisk`. As a result, running `fstrim -a` in the guest would reduce the disk space consumed by QEMU disks (`basedisk` or `diffdisk`), and reduce the disk usage of Lima guests.
Current behavior: there's no easy way to reduce the disk usage of `diffdisk`, and running `fstrim -a` in the guest has no effect.
Resolves #356
=> Enable trimming QEMU disks

examples/alpine.yaml
This will be needed to grow the filesystem when the size of the attached data volume is increased. See https://github.com/lima-vm/lima/issues/1103
=> Bump lima-alpine to 0.2.22 to include resize2fs

examples/apptainer-rootful.yaml, examples/apptainer.yaml
It has some issues with it being mounted as "nodev", so revert to using a normal file system for $TMPDIR.
```console
$ limactl shell singularity singularity run -u -B $HOME:$HOME docker://alpine
INFO:    Converting OCI blobs to SIF format
WARNING: 'nodev' mount option set on /tmp, it could be a source of failure during build process
INFO:    Starting build...
Getting image source signatures
Copying blob 213ec9aee27d done  
Copying config 29f453b10b done  
Writing manifest to image destination
Storing signatures
2022/10/02 07:18:41  info unpack layer: sha256:213ec9aee27d8be045c6a92b7eac22c9a64b44558193775a1a7f626352392b49
2022/10/02 07:18:41  warn xattr{etc/shadow} ignoring ENOTSUP on setxattr "user.rootlesscontainers"
2022/10/02 07:18:41  warn …
```
=> For apptainer, move TMPDIR away from tmpfs

Makefile, cmd/apptainer.lima
Now that Apptainer has been moved from experimental, and accepted as LF project, it might be time for a wrapper ?
There is no client for `apptainer`, similar to `nerdctl`.
So use a small shell wrapper, to run "lima apptainer".
This is so that the user can follow the documentation, without having to write an extra `lima ` prefix before every command:
https://apptainer.org/docs/user/main/quick_start.html
We might still have to document the read-only home.
```
FATAL:   While performing build: while creating SIF: while creating container: open /home/anders/lima/alpine.sif: read-only file system
```
---
This is different from the situation for docker and podman.
Since they already have client binaries, available for Mac.
=> Add wrapper for running apptainer on Mac

pkg/hostagent/dns/dns.go, pkg/hostagent/dns/dns_test.go, pkg/hostagent/hostagent.go, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go
This change ensures that user-defined host names are converted correctly to unambiguous domain names. Regardless if the user declares them as fully qualified or not we always convert them to fully qualified. 
Addresses: https://github.com/rancher-sandbox/rancher-desktop/issues/3163
Signed-off-by: Nino Kodabande <nkodabande@suse.com>
=> Convert built-in hosts to unambiguous domain names

docs/mount.md, examples/default.yaml, pkg/limayaml/defaults.go
The `mapped-xattr` model is known to be incompatible with symlinks: https://gitlab.com/qemu-project/qemu/-/issues/173
The `none` model is obviously incompatible with chown, but this is fine, as the reverse-sshfs does not support chown either.
See issue #971
=> 9p: change the default `securityModel` from `mapped-xattr` to `none`

README.ja.md, README.md, examples/archlinux.yaml, examples/buildkit.yaml, examples/debian.yaml, examples/default.yaml, examples/docker-rootful.yaml, examples/docker.yaml, examples/experimental/9p.yaml, examples/experimental/riscv64.yaml, examples/faasd.yaml, examples/k3s.yaml, examples/k8s.yaml, examples/ubuntu-lts.yaml, examples/ubuntu.yaml, examples/vmnet.yaml, hack/test-example.sh, pkg/limayaml/defaults.go
Docker is still pinned to 22.04, as 22.10 is missing in https://download.docker.com/linux/ubuntu/dists/
- - -
nerdctl v1.0.0: https://github.com/containerd/nerdctl/releases/tag/v1.0.0
=> templates: update Ubuntu, Arch, Debian; update nerdctl to v1.0.0

.github/workflows/test.yml
It looks like the runners have an older version of lima already installed via brew. We don't want/need that, as it can confuse our testing.
Also it currently seems to break upgrading, which looks like a brew issue:
```
==> Upgrading lima
0.12.0 -> 0.13.0
==> Pouring lima--0.13.0.monterey.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/apptainer.lima
Target /usr/local/bin/apptainer.lima
already exists. You may want to remove it:
rm '/usr/local/bin/apptainer.lima'
To force the link and overwrite all conflicting files:
brew link --overwrite lima
To list all files that would be deleted:
brew link --overwrite --dry-run lima
Possible conflicting files are:
/usr/local/bin/apptainer.lima …
```
=> Remove brew installation of lima

pkg/qemu/qemu.go
Fix #1135 (`-device ramfb: ramfb device requires fw_cfg with DMA`)
=> qemu: do not use `-device ramfb` for RISC-V

pkg/networks/reconcile/reconcile.go
Currently, when running an instance with a `socket_vmnet` network configured, if you try the following:
```
limactl stop default && limactl start default
```
you may notice that the `limactl start default` command consistently fails. In my testing, this is because the `pkill` command is issued, but the `socket_vmnet` process hasn't actually stoped yet.
This is what the hostagent logs look like on my system:
```
{"level":"fatal","msg":"template: :1:21: executing \"\" at \u003cfd_connect \"/private/var/run/$NETWORK_NAME/socket_vmnet.$NETWORK_NAME\"\u003e: error calling fd_connect: fd_connect: dial unix /private/var/run/$NETWORK_NAME/socket_vmnet.$NETWORK_NAME: connect: connection refused","time":"2022-10-31T18:31:21-04:00"}
```
Either waiting a few seconds between the stop and start …
=> pkg/networks: wait for daemon to stop after killing

cmd/limactl/start.go, pkg/start/start.go
Allows configuring the duration to wait for the "running" event from the host agent before timing out.
Closes #418
=> feat: configurable start timeout

cmd/limactl/shell.go
If the `SSH` environment variable is set, `limactl shell` will consider this as an alias for the `ssh` command to execute, instead of looking up a `ssh` executable in the PATH.
The provided command can be anything that is CLI-compatible with the OpenSSH client, such as a shell script that passes all provided arguments to `ssh`.
Closes #1131 
---
Demo
```sh
export SSH='kitty +kitten ssh'
```
```sh
go run ./cmd/limactl/ shell my-vm
```
```console
$ ps ww
16004 s000  S+     0:00.07 kitty +kitten ssh -F /dev/null -o IdentityFile="/Users/acotten/.lima/_config/user" -o IdentityFile="/Users/acotten/.ssh/id_ed25519" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no …
```
=> feat(shell): allow configuring ssh alias

pkg/vz/vm_darwin.go
Fixes the issue mentioned here
https://github.com/lima-vm/alpine-lima/issues/94
The reason is, 04-persistent-data-volume.sh bind the first available disk as data volume. Since cidata was first available and it was already mounted. the script was failing. Due to disk name mismatch (lsblk say vda for cidata, but /proc/mounts give disk/by-label/lima-cidata as name)
Keeping cidata as last disk similar to qemu fixes this issue.
=> fix alpine data-volume issue

examples/k8s.yaml
Kubeadm doesn't really support using flannel anymore, so could still change to a simpler plugin.
* #718
But I don't really want to bother with anything heavy like calico or cilium, for this single-node cluster.
=> Bump k8s flannel version from 0.20.0 to 0.20.1

cmd/limactl/stop.go, docs/internal.md, pkg/qemu/qemu.go, pkg/qemu/qemu_driver.go, pkg/store/filenames/filenames.go, pkg/store/instance.go, pkg/vz/vm_darwin.go
This PR resolves this discussion
https://github.com/lima-vm/lima/pull/1147#discussion_r1022460455
=> support for driver specific pid files

pkg/cidata/cidata.TEMPLATE.d/boot/08-shell-prompt.sh
The current script was assuming that "default" is Ubuntu LTS...
But now it is possible to mix and match names and templates.
Closes #1086
=> Don't try to patch the prompt on other systems

.github/workflows/test.yml
macOS 10.15 will be fully unsupported by 12/1/22
- https://github.com/actions/runner-images/issues/5583
Follow-up to:
- #1175
=> CI: remove catalina (macOS 10.15)

pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go, pkg/limayaml/validate.go
- `network`: deprecated in Lima v0.7.0 (Oct 2021), in favor of `networks`: https://github.com/lima-vm/lima/commit/07e68230e70b21108d2db3ca5e0efd0e43842fbd
- `useHostResolver`: deprecated in Lima v0.8.1 (Jan 2022), in favor of `hostResolver.enabled`: https://github.com/lima-vm/lima/commit/eaeee31b0496174363c55da732c855ae21e9ad97
The deprecated support for VDE is not removed in this commit.
- - -
Split from https://github.com/lima-vm/lima/pull/1069/commits
=> pkg/limayaml: remove deprecated `network` and `useHostResolver`

examples/experimental/opensuse-tumbleweed.yaml
JeOS was renamed to Minimal-VM
- https://github.com/openSUSE/get-o-o/pull/123
Fix https://github.com/lima-vm/lima/issues/1193
=> opensuse-tumbleweed: JeOS -> Minimal-VM

cmd/limactl/disk.go, cmd/limactl/list.go
e.g,
```console
$ limactl ls
NAME       STATUS     SSH            VMTYPE    ARCH      CPUS    MEMORY    DISK      DIR
default    Stopped    127.0.0.1:0    qemu       x86_64    4       4GiB      100GiB    /Users/suda/.lima/default
vz         Stopped    127.0.0.1:0    vz         x86_64    4       4GiB      100GiB    /Users/suda/.lima/vz
```
=> limactl list: add "VMTYPE" column

.github/workflows/test.yml, docs/network.md, docs/vmtype.md, examples/experimental/vz.yaml, examples/vmnet.yaml, pkg/limayaml/limayaml.go, pkg/limayaml/validate.go, pkg/vz/vm_darwin.go
Introduces a new YAML property `.[]networks.vzNAT` for enabling `VZNATNetworkDeviceAttachment`. No root privilege is needed.
`.[]networks.lima` is reserved for future support of `socket_vmnet` for VZ.
Fix #1161
Replaces #1206
=> vz: support `.[]networks.vzNAT` networking

cmd/limactl/disk.go, pkg/store/disk.go
Addresses some follow-up comments from https://github.com/lima-vm/lima/pull/1065.
Signed-off-by: Sam Berning <bernings@amazon.com>
=> limactl: allow passing disks as args to `disk ls`

docs/network.md, examples/vmnet.yaml, pkg/networks/config.go, pkg/networks/networks.TEMPLATE.yaml, pkg/networks/sudoers.go, pkg/networks/validate.go
On Homebrew environments, socket_vmnet is installed on:
- `/usr/local/opt/socket_vmnet/Cellar/<VERSION>/bin/socket_vmnet` (Intel)
- `/opt/homebrew/opt/socket_vmnet/Cellar/<VERSION>/bin/socket_vmnet` (ARM)
The binary is usually owned by a non-root admin user. (i.e., the homebrew user).
The group is typically set to "admin".
https://github.com/Homebrew/homebrew-core/commit/636ac0700e011b23c3e41cc4176b30e01a3af5ae
=> vmnet: support detecting Homebrew's socket_vmnet path

pkg/cidata/cidata.TEMPLATE.d/boot/04-persistent-data-volume.sh
Both `cloud-utils-growpart` (for `growpart`) and `e2fsprogs-extra` (for `resize2fs`) have only been recently added to alpine-lima.
Running an existing VM based on an older Alpine ISO will then fail the boot script calling utilities that have not been installed.
Untested, but I believe this
fixes #1242
=> Check if growpart is installed before calling it

.github/workflows/test.yml, examples/archlinux.yaml
=>  templates: update Arch Linux to 20221215.111177  ; CI: remove `brew upgrade` for avoiding issue 1256

cmd/limactl/start.go
Fixes #1247 
Some comments:
* if `--tty` is not provided and the template is read from stdin, then it defaults to `--tty=false`
* if `--tty=true` as a CLI flag and the template is read from stdin, return an error
* if `--name` as a CLI flag is not provided and the template is read from stdin, return an error
* uses `-` as the indicator for stdin, inline with what most Unix-style programs do
=> add support for reading template from stdin

pkg/vz/vm_darwin.go
=> vz: remove spice

pkg/vz/vm_darwin.go
**Reason**
The default disk attachment has a very poor disk performance (mainly when accessed via mmap).
From macOS 12 we have option to set cache and sync mode. Using VZDiskImageSynchronizationModeFsync provides a better performance and best-effort consistency as well.
https://developer.apple.com/documentation/virtualization/vzdiskimagesynchronizationmode/vzdiskimagesynchronizationmodefsync?language=objc
**Some results**
Commands
```
#for mmap test
fio --filename=PATH_TO_FILE --direct=1 --rw=randrw --bs=32k --ioengine=mmap --iodepth=256 --runtime=120 --numjobs=4 --time_based --group_reporting --name=iops-test-job --eta-newline=1 --size=1G
#for sync test
fio --filename=PATH_TO_FILE --direct=1 --rw=randrw --bs=32k --ioengine=sync --iodepth=256 --runtime=120 --numjobs=4 --time_based …
```
=> improve vm disk performance with VZDiskImageSynchronizationModeFsync

docs/network.md, examples/vmnet.yaml, pkg/vz/network_darwin.go, pkg/vz/vm_darwin.go, pkg/vz/vz_driver_darwin.go
The support for socket_vmnet is provided as mentioned over here
https://github.com/lima-vm/socket_vmnet/issues/13#issuecomment-1366410910
_Note:_
This is done so that we can easily support QEMU based network stack in vz as well. This might have a reduced performance due to pipe of dgram <-> unix socket connection
=> support socket_vmnet for vz driver

pkg/hostagent/dns/dns.go
Previously we were replying with A response for AAAA queries which was causing an error in some clients e.g nginx. The new approach waits for 1 second and then replies with NODATA. This approach allows for more semantic reply even when a client uses the same Transaction ID for both A and AAAA questions.
This PR is meant to address the issue that was reported on Rancher Desktop here: https://github.com/rancher-sandbox/rancher-desktop/issues/3447
Signed-off-by: Nino Kodabande <nkodabande@suse.com>
=> Return NODATA for IPv6 AAAA question types

pkg/downloader/downloader.go, pkg/downloader/downloader_test.go
Fixes #1217
Signed-off-by: Pris Nasrat <pnasrat@gmail.com>
=> Fix file URLs with digest

pkg/hostagent/dns/dns.go
Currently, we are leaving the response writer open for both connected sockets (TCP) and non-connected sockets (UPD), this change closes the response writer accordingly.
This change is meant to address the user-reported issue on Lima: https://github.com/lima-vm/lima/issues/1285
Signed-off-by: Nino Kodabande <nkodabande@suse.com>
=> Closes the responseWriter after serving the Answer

cmd/limactl/main.go, pkg/osutil/rosetta_darwin.go, pkg/osutil/rosetta_others.go
This PR closes #740, reports error if `limactl` is being rosetta translated. Implementation based on https://developer.apple.com/forums/thread/652667?answerId=618217022&page=1#622923022.
=> feat: report error when running under rosetta

pkg/vz/vz_driver_darwin.go
fixes #1313
**Why this change ?**
lima hostagent is terminating before the vm is fully stopped. Due to this there were disk corruptions.
This PR adds support for waiting for the state change to complete before closing hostagent
=> fix unclean stop for vz driver

.github/workflows/test.yml
The hyperlink checker was often failing:
```
> White listed:
1. [L052] 200 https://xbarapp.com/
2. [L100]  http://127.0.0.1:8080 Failed to open TCP connection to 127.0.0.1:8080 (Connection refused - connect(2) for "127.0.0.1" port 8080)
3. [L129] 404 https://github.com/lima-vm/lima/releases/download/$
Issues :-(
> Links
1. [L128] 403 https://api.github.com/repos/lima-vm/lima/releases/latest
```
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
=> CI: hyperlink check: allow 403 https://api.github.com

pkg/store/instance.go
This functionality was lost in 75594fa:
```console
$ limactl ls -f '{{.LimaHome}}' default
FATA[0000] template: format:1:2: executing "format" at <.LimaHome>: can't evaluate field LimaHome in type *store.Instance
```
=> Add global fields to instance data before executing template

pkg/downloader/downloader.go, pkg/downloader/downloader_test.go
The progressbar was messing with the test output.
This confused some test tools into thinking it failed.
```
=== RUN   TestDownloadRemote
=== RUN   TestDownloadRemote/without_cache
=== RUN   TestDownloadRemote/without_cache/without_digest
7.68 KiB (?%) ? p/s=== RUN   TestDownloadRemote/without_cache/with_digest
7.68 KiB (?%) ? p/s
7.68 KiB (?%) ? p/s=== RUN   TestDownloadRemote/with_cache
7.68 KiB (?%) ? p/s=== RUN   TestDownloadRemote/caching-only_mode
7.68 KiB (?%) ? p/s--- PASS: TestDownloadRemote (0.21s)
--- PASS: TestDownloadRemote/without_cache (0.16s)
--- PASS: TestDownloadRemote/without_cache/without_digest (0.11s)
--- PASS: TestDownloadRemote/without_cache/with_digest (0.05s)
--- PASS: TestDownloadRemote/with_cache (0.03s)
--- PASS: TestDownloadRemote/caching-only_mode (0.02s) …
```
=> Hide download progress when running tests

pkg/qemu/qemu.go
fixes #1328 
Not sure on why happening only in M1. Changing the -cdrom to -device as mentioned in https://lists.gnu.org/archive/html/qemu-discuss/2014-04/msg00052.html fixes this issue
=> Fix QEMU issue on binding multiple disks in M1

README.md, cmd/limactl/show_ssh.go, docs/internal.md, pkg/hostagent/hostagent.go, pkg/store/filenames/filenames.go, pkg/store/instance.go
```console
$ limactl ls --format='{{.SSHConfigFile}}' default
/Users/example/.lima/default/ssh.config
```
=> Write `~/.lima/<INSTANCE>/ssh.config`

cmd/limactl/list.go, pkg/store/instance.go, pkg/textutil/textutil.go, pkg/textutil/textutil_test.go
Makes it possible to show messages using a format string like:
{{.Name}}{{printf "\n"}}{{.Message | indent 2 | trim "\n"}}
Without having to add a command like `message` or a flag like `--message`.
Sample output:
```console
$ limactl ls -f '{{.Name}}{{printf "\n"}}{{.Message | indent 2 | trim "\n"}}'
k3d
To run `kubectl` on the host (assumes kubectl is installed), run the following commands:
------
mkdir -p "/home/anders/.lima/k3d/conf"
export KUBECONFIG="/home/anders/.lima/k3d/conf/kubeconfig.yaml"
limactl shell k3d sh -c 'cat ~/.kube/config' >$KUBECONFIG
kubectl ...
------
------
export DOCKER_HOST="unix:///home/anders/.lima/k3d/sock/docker.sock"
docker ...
------
kind
To run `kubectl` on the host …
```
=> Add template functions for list/inspect message

hack/test-example.sh
This happens frequently with CI on archlinux, and the failure is likely related to some error during boot script processing.
=> Show cloud-init-output.log when "nerdctl info" fails

examples/default.yaml, examples/k3s.yaml, examples/k8s.yaml, pkg/hostagent/hostagent.go, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go, pkg/limayaml/validate.go
* Refactor PortForward guest/host processing
* Add possibility to copy ConfigFile to host
Issue #1300
=> Add possibility to copy ConfigFile to host

Makefile, cmd/kubectl.lima
Will connect to a running "k3s" or "k8s" instance.
Similar to other wrappers, but uses conf not sock.
Issue #1300
Needs PR #1301 in order to create the "conf" files
=> Add kubectl kubernetes client wrapper

cmd/limactl/list.go, pkg/store/instance.go, pkg/store/instance_test.go
* Hide identical columns in the list command
If all the instances have the same type or arch,
then don't display the column - unless requested.
* Hide the directory column on narrow terminal
If the terminal width does not fit all the list
columns, then hide "dir" column - unless requested.
before
```
NAME    STATUS     SSH            VMTYPE    ARCH      CPUS    MEMORY    DISK   
DIR
k8s     Stopped    127.0.0.1:0    qemu      x86_64    4       4GiB      100GiB  
~/.lima/k8s
```
after
```
NAME    STATUS     SSH            CPUS    MEMORY    DISK      DIR
k8s     Stopped    127.0.0.1:0    4       4GiB      100GiB    ~/.lima/k8s
```
```
NAME    STATUS     SSH            VMTYPE    ARCH      CPUS    MEMORY    DISK
k8s     Stopped    127.0.0.1:0    qemu      x86_64    4       4GiB      100GiB …
```
=> Hide columns in the list command

examples/default.yaml, pkg/hostagent/hostagent.go
This PR resolves the issue https://github.com/rancher-sandbox/rancher-desktop/issues/3042 and relates to the comment https://github.com/rancher-sandbox/rancher-desktop/issues/3488. 
This change ensures the ssh agent socket can be mounted into containers without having to determine the location first. The location will be in a static location /run/host-services/ssh-auth.sock. This is the same location as Docker Desktop uses.
Signed-off-by: Ryan Currah <ryan@currah.ca>
=> improvement(hostagent): link ssh agent socket to predetermined location

docs/experimental.md, docs/internal.md, examples/default.yaml, go.mod, go.sum, pkg/driver/driver.go, pkg/hostagent/hostagent.go, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go, pkg/qemu/qemu.go, pkg/qemu/qemu_driver.go, pkg/store/filenames/filenames.go
The other display options open a window always, while the
vnc is more "on demand" by using a separate vnc viewer.
Add localhost and password support for some minimal security.
The password is generated, and is stored as an instance file.
Closes #1003
=> Add VNC video display including password

README.md, cmd/limactl/start.go, docs/experimental.md, go.mod, go.sum, pkg/yqutil/yqutil.go, pkg/yqutil/yqutil_test.go
Allows modifying the yaml template "inplace" for a single instance,
if you don't want to change the default or override for all instances.
This is similar to running `yq` on the template, from the command-line.
Except it does it on a temporary file, and for all different kinds of templates.
```console
$ yq < examples/default.yaml > default.yaml
$
```
Currently it removes empty lines, some quirk with the yaml parser used.
It also seems to change the indentation on some comments (only), but OK:
```console
$ diff -B -w examples/default.yaml default.yaml
$
```
This can be used as a general fallback, similar to `jq`, for modifying templates.
Instead of adding the usual `--cpus` `--memory` `--arch`, or other parameters ?
----
See <https://github.com/mikefarah/yq> for details
* #545
`limactl …
=> Add builtin yq support to lima start command

examples/alpine.yaml
Updates binfmt handler to qemu 7.0 and fixes a bug that was preventing mounts of path names containing spaces.
=> Bump alpine-lima from 0.2.26 → 0.2.27

cmd/limactl/hostagent.go, pkg/hostagent/dns/dns.go
Local server names/addresses are often considered confidential and should not by default be logged. Their loglevel has been lowered to TRACE.
The host agent code now switches to TRACE level logging when the instance is started via `limactl --debug start ...`.
Fixes #1367
=> Don't log DNS queries by default

examples/k8s.yaml
The default for image-endpoint is to use runtime-endpoint.
So it is not needed, to set both of them to the same value.
----
```
--image-endpoint value, -i value    Endpoint of CRI image manager service (default: uses 'runtime-endpoint' setting) [$IMAGE_SERVICE_ENDPOINT]
--runtime-endpoint value, -r value  Endpoint of CRI container runtime service (default: uses in order the first successful one of [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock unix:///var/run/cri-dockerd.sock]). Default is now deprecated and the endpoint should be set instead. [$CONTAINER_RUNTIME_ENDPOINT]
```
=> k8s: Remove redundant crictl.yaml config line

examples/archlinux.yaml, examples/buildkit.yaml, examples/centos-stream-9.yaml, examples/debian.yaml, examples/default.yaml, examples/docker-rootful.yaml, examples/docker.yaml, examples/experimental/9p.yaml, examples/experimental/opensuse-tumbleweed.yaml, examples/experimental/riscv64.yaml, examples/faasd.yaml, examples/k3s.yaml, examples/k8s.yaml, examples/rocky-8.yaml, examples/rocky-9.yaml, examples/ubuntu-lts.yaml, examples/ubuntu.yaml, examples/vmnet.yaml, pkg/limayaml/defaults.go
https://github.com/containerd/nerdctl/releases/tag/v1.2.1
https://github.com/containerd/nerdctl/releases/tag/v1.2.0
containerd <= v1.6.16 creates `/etc/cni` with permission 0700 when running in the rootful mode.
This causes an error like `open /etc/cni/tuning/allowlist.conf: permission denied` for CNI tuning plugin >= v1.2.0 when running in the rootless mode.
Run `lima sudo chmod 0755 /etc/cni` to dismiss this error.
=> update nerdctl (1.2.1) and templates

cmd/limactl/copy.go, cmd/limactl/debug.go, cmd/limactl/delete.go, cmd/limactl/disk.go, cmd/limactl/edit.go, cmd/limactl/factory-reset.go, cmd/limactl/hostagent.go, cmd/limactl/info.go, cmd/limactl/list.go, cmd/limactl/main.go, cmd/limactl/prune.go, cmd/limactl/shell.go, cmd/limactl/show_ssh.go, cmd/limactl/start.go, cmd/limactl/stop.go, cmd/limactl/sudoers.go, cmd/limactl/validate.go
This PR closes #1211, show more user friendly error message on argument error. The output is similar to nerdctl and docker cli.
It looks like below:
=> feat: more friendly cli error message

pkg/guestagent/kubernetesservice/kubernetesservice.go
This is a normal state when not running kubernetes.
Fixes #1394
=> Silence kubernetes service watcher failing to find kubeconfig

pkg/qemu/imgutil/imgutil.go
Avoids errors about the disk being in use by the running qemu.
Older versions of qemu default to read-write mode for images.
Closes #1392
=> Run qemu-img info in shared mode for GetInfo

pkg/cidata/cidata.go, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go, pkg/vz/vm_darwin.go
Allow Rosetta fields to be overridden by making them pointers and setting default values based the same way they are set for other config options.
=> feat: allow rosetta fields to be overridden

pkg/downloader/downloader.go, pkg/fileutils/download.go, pkg/qemu/qemu.go, pkg/start/start.go, pkg/vz/disk.go
When downloading a file, show a one-line description of what is being downloaded...
This is useful when hiding the log, so that the user knows what the progress is about.
* https://github.com/lima-vm/lima/issues/1311#issuecomment-1399269734
Refactor the code (fileutils), to not have a special case for the nerdctl archive download.
```
Downloading the image (ubuntu-22.10-server-cloudimg-amd64.img)
697.56 MiB / 697.56 MiB [----------------------------------] 100.00% 15.95 MiB/s
Downloading the nerdctl archive (nerdctl-full-1.2.1-linux-amd64.tar.gz)
230.56 MiB / 230.56 MiB [-----------------------------------] 100.00% 2.75 MiB/s
Starting "default"
Waiting 1 / 8 [--->________________________]  "ssh" (essential 1/5)                                 
Waiting 2 / 8 [------>_____________________] …
```
=> Show a user-readable description of the download

pkg/store/instance_test.go
Turns out that "aarch64" is one character longer than "x86_64".
In the future, we might want to have a special tablewriter mod.
----
Fixes tests breaking:
GOARCH=amd64 gotestsum ./...
DONE 77 tests, 4 skipped in 0.645s
GOARCH=arm64 gotestsum ./...
DONE 77 tests, 4 skipped, 2 failures in 1.233s
Might want to add a cross-platform test target, to catch these ?
=> Adjust table test for longer architectures

pkg/limayaml/defaults_test.go
The tests were assuming that all non-X8664 is RISCV64
Also shows a lack of testing, on the RISC-V platform.
=> Tests fail on RISCV64 due to hardcoded AARCH64

cmd/limactl/edit.go, docs/experimental.md
Also add` --tty` parameter, similar to the start command, for avoiding user interaction asking whether to start it.
```console
$ limactl edit --tty=false --set ".cpus = 2" default
INFO[0000] Instance "default" configuration edited      
$ limactl edit --tty=false --set ".cpus = 2" default
INFO[0000] Aborting, no changes made to the instance  
```
Follow-up to:
* #1359
=> Add builtin yq support to limactl edit command

README.md, cmd/limactl/disk.go, docs/internal.md, pkg/qemu/qemu.go, pkg/vz/vm_darwin.go, pkg/vz/vz_driver_darwin.go
This PR adds support for using the additional disks feature with Virtualization.framework. I noticed it was missing, so I figured I'd add it.
Considerations:
- [Virtualization.framework can only mount RAW disk images](https://developer.apple.com/documentation/virtualization/vzdiskimagestoragedeviceattachment). The additional disk feature [currently creates QCOW2 images](https://github.com/lima-vm/lima/blob/5a9bca3d09481ed7109b14f8d3f0074816731f43/pkg/qemu/qemu.go#L115). Since QEMU can support RAW images, is it ok to change the additional disk feature to create RAW images by default?
- This change already included in this diff, but I can remove it
- Should Lima automatically convert QCOW2 disks to RAW before trying to mount a QCOW2 additional with `vmType: vz`? There's already [precedent …
=> feat: mount additional disks when using vz

pkg/downloader/downloader.go, pkg/downloader/downloader_test.go, pkg/fileutils/download.go, pkg/qemu/qemu.go, pkg/start/start.go, pkg/vz/disk.go
Fork an external program, rather than linking everything.
(like https://github.com/mholt/archiver)
Keep some files compressed, such as the nerdctl-full tgz.
Closes #809
=> Support compressed image files with os/exec

cmd/limactl/shell.go
Everything after the instance name is sent to the shell.
Updated usage:
```
$ limactl shell --help
Execute shell in Lima
...
Usage:
limactl shell [flags] INSTANCE [COMMAND...]
```
Ref: https://github.com/lima-vm/lima/discussions/586#discussioncomment-5477505
=> limactl shell flags MUST come before the instance name

pkg/limayaml/defaults.go
https://github.com/containerd/nerdctl/releases/tag/v1.3.0
=> Update nerdctl to 1.3.0

examples/experimental/opensuse-tumbleweed.yaml
This reverts commit 7430e5c08195a1362563045b278dfa9e4137012d.
=> Revert "templates: opensuse-tumbleweed: remove aarch64 image due to 404"

pkg/qemu/imgutil/imgutil.go, pkg/vz/disk.go, pkg/vz/vm_darwin.go
Closes: #1438 
Refactored disk conversion functions to be more explicit and used new `imgutil.ConvertToRaw` function in VZ driver, like suggested in https://github.com/lima-vm/lima/pull/1405#discussion_r1148315941.
=> refactor: vz disk conversion

pkg/cidata/cidata.TEMPLATE.d/boot/04-persistent-data-volume.sh
Added packages must be reinstalled on each boot because Alpine runs from an ISO. Setting up the package cache avoid having to re-download the packages each time.
=> Setup apk cache on persistent volume

cmd/limactl/main.go
For a normal run, with downloads already cached, this will only output the message (if any)
=> Enable silent log-level for hiding INFO messages

examples/experimental/opensuse-tumbleweed.yaml, examples/opensuse.yaml
download.opensuse.org is inaccessible from Japan (500 Internal Server Error) https://bugzilla.opensuse.org/show_bug.cgi?id=1210240
=> templates: openSUSE: fall back to provo-mirror.opensuse.org

pkg/limayaml/defaults.go
https://github.com/containerd/nerdctl/releases/tag/v1.3.1
=> nerdctl: update to v1.3.1

pkg/fileutils/download.go, pkg/qemu/qemu.go, pkg/start/start.go, pkg/vz/disk.go
Example:
```yaml
images:
- location: "https://example.com/dummy-x86_64"
arch: "x86_64"
- location: "https://example.com/dummy-aarch64"
arch: "aarch64"
```
Before:
```console
$ limactl start dummy
INFO[0000] Using the existing instance "dummy"
INFO[0000] Attempting to download the image              arch=x86_64 digest= location="https://example.com/dummy-x86_64"
FATA[0000] failed to download the image, attempted 2 candidates, errors=[failed to download "https://example.com/dummy-x86_64": expected HTTP status 200, got 404 Not Found unsupported arch: "aarch64"]
```
After:
```console
$ limactl start dummy
INFO[0000] Using the existing instance "dummy"
INFO[0000] Attempting to download the image              arch=x86_64 digest= location="https://example.com/dummy-x86_64"
FATA[0000] failed to …
```
=> Improve the "failed to download" error message

examples/default.yaml, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/qemu/qemu.go
https://stackoverflow.com/a/72863744/5167443
Workaround for #1485
=> qemu: disable pdpe1gb on Intel Mac

pkg/vz/vm_darwin.go, pkg/vz/vz_driver_darwin.go
=> vz: fix mu

go.mod, pkg/limayaml/load.go, pkg/limayaml/load_test.go
The goccy library doesn't catch all the errors, that other libraries such as the one used by "yq" does.
So check the yaml with both of them.
Now catches things such as missing `script:` line:
`FATA[0000] failed to load YAML file "examples/distrobox.yaml": failed to unmarshal YAML (main file "/home/anders/lima/examples/distrobox.yaml"): yaml: line 12: did not find expected key`
Closes #1503
=> Make sure that yaml is valid with gopkg.in/yaml.v3 as well

MAINTAINERS.md
Security issues can be now reported through https://github.com/lima-vm/lima/security/advisories/new
- https://github.com/lima-vm/.github/pull/6
=> MAINTAINERS.md: use GHSA for reporting security issues

examples/default.yaml, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go, pkg/qemu/qemu.go
Tested with `mikmod` and https://modarchive.org/, seems to work fine (used ALSA)
Only tricky part was that the kernel module was in `linux-modules-extra`, then `alsa`
```console
anders@lima-default:~$ sudo aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Intel [HDA Intel], device 0: Generic Analog [Generic Analog]
Subdevices: 1/1
Subdevice #0: subdevice #0
```
Closes #1526
=> Add audio device to limayaml and qemu

examples/default.yaml, pkg/vz/vm_darwin.go, pkg/vz/vz_driver_darwin.go
Fixes #1531 
Had to do some setup to configure audio. Steps are as follows,
- Install `linux-image-extra-virtual` to enable virtio-snd
- Restart the VM
- Run `aplay -l` to verify if device is shown
- Install `alsa-utils`
- Run `usermod -a -G audio <user>`
- Restart the vm
- Run `nano ~/.asoundrc and add the following
```
pcm.!default {
type hw
card 1
}
ctl.!default {
type hw
card 1
}
```
- Run `speaker-test -t wav` and verify audio working
_Note: These are the steps worked for me, there might be some simplified steps to configure as well._
=> Support audio device for vz driver

Makefile, cmd/limactl/genman.go, cmd/limactl/main.go, go.mod, go.sum
The "limactl.1" and subcommands are being dynamically generated.
There is one manual page for each subcommand, e.g. limactl-start
----
https://github.com/spf13/cobra/blob/main/doc/man_docs.md
There is also `help2man --no-info`, for individual commands
=> Include manpages for lima and limactl commands

pkg/qemu/qemu.go, pkg/qemu/qemu_test.go
This is mostly to give better error messages, when failing.
The old error would just say that it exited unexpectedly...
Closes #1534
=> Check qemu version in hostagent so not too old

pkg/networks/usernet/UDPFileConn.go, pkg/networks/usernet/gvproxy.go, pkg/vz/vm_darwin.go
This should hopefully fix the network freeze when using vz driver
https://github.com/lima-vm/lima/issues/1200#issuecomment-1327740698
I didn't add fix issue id's mainly to try and see if this really fixes or not.
**What is happening, why this change ?**
When we use file.FD(), whenever the file gets closed or garbage collected (finaliser closing file) the FD give before becomes invalid.
In our case, we use file.FD() for both client and server connections. Since these are DGRAM connection, if we try to read on a closed FD we won't get any error instead it get stuck indefinitely. This could be the reason for the freeze of vz network 
Before this change, i verified that that file getting garbage collected in ~2mins. So logically FD would become invalid at some point.
=> Fix unstable vz driver network issue

pkg/limayaml/defaults.go
https://github.com/containerd/nerdctl/releases/tag/v1.4.0
=> nerdctl: update to v1.4.0

examples/alpine.yaml
(Alpine 3.16 works on 13.1+; Alpine 3.17 also requires 13.3+)
=> Alpine 3.18 on VZ requires macOS 13.3+

docs/experimental.md, examples/default.yaml, pkg/limayaml/validate.go
The design is still subject to change:
- #1536
=> Mark `audio.device` experimental

examples/k8s.yaml
the url to get gpg key for kubernetes is moved
cloud-init-out.log
```
Err:4 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
Reading package lists...
W: GPG error: https://packages.cloud.google.com/apt kubernetes-xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
E: The repository 'https://apt.kubernetes.io/ kubernetes-xenial InRelease' is not signed.
```
referring to https://github.com/kubernetes/k8s.io/pull/4837
testes it on both of intel & m1 mac
=> [examples/k8s.yaml] the url to get gpg key for kubernetes is moved

examples/alpine.yaml, pkg/cidata/cidata.TEMPLATE.d/boot/05-rosetta-volume.sh
The alpine-lima changes make sure that the `binfmt` filesystem is mounted before the bootscripts are executed, so Rosetta can be registered.
Similarly, they ensure that the `qemu-binfmt` service is started before `lima-init`, so the qemu handler can be uninstalled when Rosetta is enabled.
=> Bump alpine to 0.2.30 and fix Rosetta support

Makefile, cmd/limactl/genman.go
We were showing the link to the examples and the documentation, to the build folder...
It is supposed to link to the files in the installed end result, that is to the install prefix.
man _output/share/man/man1/limactl.1
`See also example YAMLs: /usr/local/share/doc/lima/examples`
man _output/share/man/man1/limactl-sudoers.1
`See /usr/local/share/doc/lima/docs/network.md for the usage.`
=> Remove the output directory from the manpages

cmd/limactl/hostagent.go, pkg/driver/driver.go, pkg/hostagent/hostagent.go, pkg/start/start.go, pkg/vz/vm_darwin.go, pkg/vz/vz_driver_darwin.go
=> Support for display with vz driver

examples/centos-stream-9.yaml
The images from lima 0.15.1 were already 404
=> Add fallback for the centos-stream image

examples/debian.yaml
This saves download time and disk space, by not including
drivers for physical hardware but only for virtual cloud.
https://cloud.debian.org/images/cloud/
> _generic_: Should run in any environment using cloud-init, for e.g. OpenStack, DigitalOcean and also on bare metal.
> _genericcloud_: Similar to generic. Should run in any virtualised environment. Is smaller than `generic` by excluding drivers for physical hardware.
Add fallback URLs, similar to the others.
=> Use debian genericcloud instead of generic images

docs/experimental.md, docs/mount.md, examples/README.md, examples/experimental/virtiofs-linux.yaml, hack/test-example.sh, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go, pkg/limayaml/validate.go, pkg/qemu/qemu.go, pkg/qemu/qemu_driver.go, pkg/store/filenames/filenames.go
This adds support for using virtiofs to mount filesystems on Linux hosts, via QEMU's vhost-user-fs-pci device + the Rust implementation of virtiofsd. In a simple "benchmark" running sha256sum on a copy of the Windows 11 ARM64 VHDK (because it's a large file I randomly had lying around):
- reverse-sshfs took ~21s
- 9p took ~13-15s
- virtiofs took ~6-7s
(For comparison, running it directly on the host system took ~5s.)
This is marked as "experimental" because it has undergone testing by...me and relies on additional tools installed other than just QEMU.
Unfortunately, this does *not* include support for DAX, because that's not merged into upstream QEMU yet, making it rather difficult to test.
Ref. #20.
=> qemu: Add virtiofs support on Linux

Makefile, docs/experimental.md, docs/internal.md, examples/README.md, examples/default.yaml, examples/experimental/armv7l.yaml, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go, pkg/limayaml/validate.go, pkg/qemu/qemu.go
Closes: #1622
The name was selected to match `uname` output, like with all the other Lima architectures.
Note that armv5 and armv6 are **not** supported, only armv7 (container architecture: `linux/arm/v7`)
This architecture is expected to be emulated, there is no arm32 hardware with CPU virt support - afaik.
=> Add support for armv7l architecture

pkg/osutil/dns_darwin.go
The proxyURL method always returns wrong URL format.
For example: before the repair, input parameters "127.0.0.1" and "8090" to the proxyURL method, and the output URL result will be "[http://127.0.0.1]:8090". But the expected result should be "http://127.0.0.1:8090", unexpectedly there are two extra square brackets. 
This bug eventually caused lima to be unable to use the network proxy configuration of the MacOS.
The reason for this bug is that the proxyURL method calls JoinHostPort to distinguish splicing of IPv4 or IPv6 addresses. The JoinHostPort method distinguishes by judging whether the host parameter contains a ":" string. However, in the proxyURL method, the prefix "http://" is added to the host in advance, so that the host parameter passed into JoinHostPort always has a ":" …
=> Fix unable to use the network proxy configuration of the MacOS(10.15)

.github/workflows/release.yml, cmd/apptainer.lima, cmd/docker.lima, cmd/kubectl.lima, cmd/limactl/completion.go, cmd/limactl/copy.go, cmd/limactl/list.go, cmd/limactl/main.go, cmd/limactl/shell.go, cmd/limactl/show_ssh.go, cmd/limactl/start.go, cmd/podman.lima, hack/test-example.sh
`limactl create` is similar to `limactl start` but it does not start the created instance, and it does not accept an existing instance name as an argument.
Now it is discouraged (not deprecated) to use `limactl start` for creating new instances.
Discouraged form:
```
limactl start --name=foo template://docker
```
Recommended form:
```
limactl create --name=foo template://docker
limactl start foo
```
=> limactl: add `limactl create` command

README.md
It is possible to use Lima, instead of Podman Machine, to run Podman, or Docker, or Kubernetes (for running with containerd).
How is documented in the Podman Desktop documentation, but as long as the instance is running it will appear automatically.
https://podman-desktop.io/docs/Installation/creating-a-lima-instance-with-podman-desktop
I don't want to link directly to the sub-page, since they have a tendency to break their URLs.
=> Add Podman Desktop to the list of Lima adopters

examples/apptainer-rootful.yaml, examples/apptainer.yaml
Fedora stopped updating their apptainer packages, and the Apptainer project introduced an official PPA for Ubuntu LTS.
https://packages.fedoraproject.org/pkgs/apptainer/apptainer/
https://apptainer.org/news/official-ppa-20230206/
The installation instructions are here: https://apptainer.org/docs/admin/latest/installation.html#install-ubuntu-packages
```console
$ apptainer.lima --version
apptainer version 1.2.0
```
https://apptainer.org/news/apptainer-1-2-0-20230718
=> Move apptainer examples to ubuntu ppa

hack/test-example.sh
The snapshot tests are too flaky, especially with the archlinux template
=> CI: mostly disable snapshot tests

examples/default.yaml, pkg/cidata/cidata.TEMPLATE.d/boot/25-guestagent-base.sh, pkg/cidata/cidata.TEMPLATE.d/boot/40-install-containerd.sh, pkg/cidata/cidata.TEMPLATE.d/lima.env, pkg/cidata/cidata.go, pkg/cidata/template.go, pkg/hostagent/requirements.go, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go
If /usr/local is read-only, you can override the prefix to use something like /opt instead. But it is assumed that /etc is always read-write...
Closes #1654
----
For some reason /opt/bin was not in the PATH of the check, even if it is the PATH of the actual user later on.
Workaround was to check with `test -x` in addition to `command -v`, to see if `nerdctl` has been installed yet.
=> Allow changing prefix for the installations

pkg/cidata/cidata.TEMPLATE.d/boot/09-host-dns-setup.sh
This PR updates the behavior of the host DNS configuration script to avoid hiccups on VM restarts (or rather stop/start attempts).
The issue is that when hostagent starts up, it picks a random free port for UDP/TCP which is then reflected in the guest's nat table in append mode. If there was a previous rule to route the DNS traffic on a (now potentially invalid) port, the DNS requests will time out.
This changeset moves the host DNS rules to a dedicated chain to be able to update them seamless on restart and when hostagent ports change.
=> Update DNS set up script to use a dedicated chain 

examples/almalinux-8.yaml, examples/almalinux-9.yaml
It seems the centos-stream images are **not** being updated...
centos-stream-release-8.6-1.el8.noarch
centos-stream-release-9.0-21.el9.noarch
So better to use almalinux distribution, for testing EL8 and EL9.
almalinux-release-8.8-1.el8.x86_64
almalinux-release-9.2-1.el9.x86_64
----
They have rebased to CentOS Stream now:
https://almalinux.org/blog/future-of-almalinux/
So this is now "Next"*, rather that "Current"
\* as in "[EPEL-Next](https://docs.fedoraproject.org/en-US/epel/epel-about-next/)" vs. EPEL (for RHEL and [Rocky](https://rockylinux.org/news/2023-06-22-press-release/))
=> Add fallback for the almalinux images

examples/k3s.yaml
We only need to install k3s once on first boot.
=> Don't repeatedly download get.k3s.io

cmd/limactl/disk.go, cmd/limactl/stop.go, examples/default.yaml, pkg/cidata/cidata.TEMPLATE.d/boot/05-lima-disks.sh, pkg/cidata/cidata.TEMPLATE.d/lima.env, pkg/cidata/cidata.go, pkg/cidata/template.go, pkg/hostagent/hostagent.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go, pkg/limayaml/load.go, pkg/limayaml/load_test.go, pkg/qemu/qemu.go, pkg/vz/vm_darwin.go
Default to a simple string with name, just like before.
```yaml
additionalDisks:
- "disk"
```
But also allow skipping the partitioning and formatting.
```yaml
additionalDisks:
- name: "disk"
format: true
fsType: "ext4"
```
----
Example 1)
Like when running something like [ceph](https://ceph.io), which uses LVM.
It requires the entire disk device to be "raw", unformatted:
```yaml
additionalDisks:
- name: "disk"
format: false
```
https://docs.ceph.com/en/latest/cephadm/install/
> A storage device is considered available if all of the following conditions are met:
>
> * The device must have no partitions.
> * The device must not have any LVM state.
> * The device must not be mounted.
> * The device must not contain a file system.
> * The device must not contain a Ceph BlueStore OSD.
> * The …
=> Allow leaving additional disks unformatted

examples/experimental/rke2.yaml
[RKE2 V1.27.3](https://github.com/rancher/rke2/releases/tag/v1.27.3%2Brke2r1) has added support for the arm64 architecture, so there is one more way to deploy K8S on Apple Silicon. The `INSTALL_RKE2_CHANNEL=latest` indicates that the latest `v1.27.x` is installed instead of the stable `v1.25.x`. And I think `k8s-rke2.yaml` should be in `examples/experimental` before `v1.27.x` becomes a stable channel.
```shell
env | grep "http_proxy\|https_proxy\|no_proxy" >> /etc/default/rke2-server
sed -i "s/http_proxy/CONTAINERD_HTTP_PROXY/g" /etc/default/rke2-server
sed -i "s/https_proxy/CONTAINERD_HTTPS_PROXY/g" /etc/default/rke2-server
sed -i "s/no_proxy/CONTAINERD_NO_PROXY/g" /etc/default/rke2-server
```
To avoid service unavailability due to `no_proxy`, use the variable with the prefix …
=> Add example config to deploy kubernetes via RKE2

pkg/qemu/qemu.go
Apparently fix:
- #1689 
- #1691
=> qemu: virtio-serial-pci: set max_ports=1

examples/apptainer-rootful.yaml, examples/apptainer.yaml, examples/buildkit.yaml, examples/centos-stream-8.yaml, examples/centos-stream-9.yaml, examples/debian-11.yaml, examples/debian-12.yaml, examples/default.yaml, examples/docker-rootful.yaml, examples/docker.yaml, examples/experimental/9p.yaml, examples/experimental/armv7l.yaml, examples/experimental/opensuse-tumbleweed.yaml, examples/experimental/riscv64.yaml, examples/experimental/rke2.yaml, examples/experimental/virtiofs-linux.yaml, examples/faasd.yaml, examples/k3s.yaml, examples/k8s.yaml, examples/nomad.yaml, examples/opensuse.yaml, examples/oraclelinux-8.yaml, examples/oraclelinux-9.yaml, examples/ubuntu-lts.yaml, examples/ubuntu.yaml, examples/vmnet.yaml, pkg/limayaml/defaults.go
https://github.com/containerd/nerdctl/releases/tag/v1.5.0
=> nerdctl: update to v1.5.0; templates: update Ubuntu, Debian, openSUSE, CentOS Stream, Oracle Linux

docs/internal.md, examples/experimental/armv7l.yaml, pkg/qemu/qemu.go, pkg/store/filenames/filenames.go
On armv7l, dmesg is not shown in the default serial (ttyAMA0).
On aarch64, dmesg is still shown but cloud-init logs are not shown.
Add `pci-serial` device to enable ttyS0.
The default ttyAMA0 is still kept to show UEFI logs.
Fix #1701
=> qemu: armv7l, aarch64: add pci-serial

cmd/apptainer.lima
Not all software was happy with a read-only $HOME directory.
Using APPTAINER_HOME changed the $HOME in the container.
----
So use the regular VM $HOME, but do bind-mount host $HOME.
Using APPTAINER_BINDPATH is the same as using the `-B` flag.
=> Use APPTAINER_BINDPATH instead of APPTAINER_HOME

README.md
It was indented wrong, causing it to show up in the menu.
Rerun "doctoc" to fix the whitespace in the list as well.
----
Fixes the "Contents" menu on https://lima-vm.io/
Contents
* [Motivation](https://lima-vm.io/#motivation)
* [Community](https://lima-vm.io/#community)
* [Examples](https://lima-vm.io/#examples)
* [Getting started](https://lima-vm.io/#getting-started)
* [How it works](https://lima-vm.io/#how-it-works)
* [Developer guide](https://lima-vm.io/#developer-guide)
* [FAQs & Troubleshooting](https://lima-vm.io/#faqs--troubleshooting)
* ~~[VZ](https://lima-vm.io/#vz)~~
=> Fix toc level of VZ generic category

.markdownlint.json, README.md
Fix these errors:
1 MD001/heading-increment/header-increment
5 MD005/list-indent
13 MD007/ul-indent
1 MD024/no-duplicate-heading/no-duplicate-header
7 MD034/no-bare-urls
2 MD040/fenced-code-language
Ignore these issues:
2 MD004/ul-style
53 MD013/line-length
6 MD014/commands-show-output
50 MD022/blanks-around-headings/blanks-around-headers
10 MD031/blanks-around-fences
19 MD032/blanks-around-lists
4 MD033/no-inline-html
1 MD041/first-line-heading/first-line-h1
`npm install -g markdownlint-cli`
https://github.com/igorshubovych/markdownlint-cli
=> Run markdownlint on README.md

cmd/limactl/start.go
`limactl start` was spamming
`Hint: To create another instance, run the following command...` when the "default" instance exists
=> limactl start: silence unnecessary hint

README.md
Lima is also useful on Linux hosts and can be an alternative to Vagrant.
=> README.md: remove "(on macOS, in most cases)"

pkg/hostagent/hostagent.go
When we are forwarding a local socket, we should not delete it.
Theoretically we could delete the remote socket, if it exists.
Closes #1724
* https://github.com/lima-vm/lima/pull/836
=> Don't delete local socket when reverse

cmd/limactl/hostagent.go, docs/internal.md, examples/default.yaml, pkg/cidata/cidata.go, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go, pkg/limayaml/validate.go, pkg/start/start.go, pkg/usrlocalsharelima/usrlocalsharelima.go
Avoid hardcoding "linux" everywhere, use OS instead (like Arch).
~~TODO: Add proper cidata template parameter for LIMA_CIDATA_HOME~~
There are some other hardcoded Linux or Systemd specific things too:
`/bin/bash`  or `/run`, those are not addressed here and are left as is.
----
Doing the OS refactoring in a separate PR, makes it easier to add OS
* #1509
=> Add OS to lima.yaml for future guests

pkg/hostagent/dns/dns.go
Before: `Start tcp server listening on...`
After: `Start tcp DNS listening on...`
=> dns: make a debug message more descriptive

examples/experimental/riscv64.yaml, pkg/limayaml/validate.go
=> Validate arch against image not default

pkg/qemu/entitlementutil/entitlementutil.go, pkg/qemu/qemu.go, pkg/start/start.go
```console
$ limactl start
INFO[0000] Using the existing instance "default"        
WARN[0000] QEMU binary "/usr/local/bin/qemu-system-x86_64" is not properly signed with the "com.apple.security.hypervisor" entitlement  error="failed to run [codesign --verify /usr/local/bin/qemu-system-x86_64]: exit status 1 (out=\"/usr/local/bin/qemu-system-x86_64: invalid signature (code or signature have been modified)\\nIn architecture: x86_64\\n\")"
? Try to sign "/usr/local/bin/qemu-system-x86_64" with the "com.apple.security.hypervisor" entitlement? Yes
...
```
- - -
Workaround for:
- #1742
This workaround is needed because Homebrew's QEMU binary is not properly signed since v8.0.4. https://github.com/Homebrew/homebrew-core/pull/139409#issuecomment-1676165225
=> qemu: ask to sign QEMU binary when the binary is not properly signed

README.ja.md, README.md, README.zh.md
Noticed that link linting started failing on another PR (https://github.com/lima-vm/lima/pull/1726) because of the new sharding of Homebrew formulas (see https://github.com/Homebrew/homebrew-core/pull/139592).
=> fix(lint): update homebrew formula links

docs/internal.md, pkg/cidata/cidata.TEMPLATE.d/boot.sh, pkg/cidata/cidata.TEMPLATE.d/boot/08-shell-prompt.sh, pkg/cidata/cidata.TEMPLATE.d/boot/20-rootless-base.sh, pkg/cidata/cidata.TEMPLATE.d/boot/25-guestagent-base.sh, pkg/cidata/cidata.TEMPLATE.d/boot/40-install-containerd.sh, pkg/cidata/cidata.TEMPLATE.d/lima.env, pkg/cidata/cidata.TEMPLATE.d/user-data, pkg/cidata/cidata.go, pkg/cidata/template.go, pkg/cidata/template_test.go
Just a refactoring, to avoid hardcoding `/home` and `linux` everywhere in cidata.
=> Add variable for the guest home directory

pkg/guestagent/kubernetesservice/kubernetesservice.go, pkg/guestagent/kubernetesservice/kubernetesservice_test.go
This PR resolves #1741, the previously used method is deprecated since apimachinery@v0.27. Also updates unit-test to use assert package.
=> chore: replace deprecated poll method

examples/default.yaml, examples/experimental/rke2.yaml, examples/k3s.yaml, examples/k8s.yaml, pkg/hostagent/hostagent.go, pkg/limayaml/limayaml.go
Closes #1737
start
```
INFO[0027] [hostagent] The final requirement 1 of 1 is satisfied 
INFO[0027] [hostagent] Copying config from /etc/rancher/k3s/k3s.yaml to /home/anders/.lima/k3s/copied-from-guest/kubeconfig.yaml 
```
stop
```
INFO[0000] [hostagent] Shutting down the host agent     
INFO[0000] [hostagent] Deleting /home/anders/.lima/k3s/copied-from-guest/kubeconfig.yaml 
```
=> Delete the conf file when instance is stopped

pkg/hostagent/hostagent.go, pkg/hostagent/mount.go, pkg/hostagent/requirements.go, pkg/qemu/qemu_driver.go
https://github.com/containerd/nerdctl/pull/2434#issuecomment-1684415782
=> Fix usage of `errors.Join`

.github/workflows/test.yml, hack/fix-qemu-signature.sh
Workaround for:
- lima-vm/lima#1742
- Homebrew/homebrew-core#140244
=> CI: fix QEMU binary signature

examples/k8s.yaml
The package hosting is moving from Google to OBS.
https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/
There is now one repository per release version.
It is the exact _same_ binary content, as is available on [dl.k8s.io](https://www.downloadkubernetes.com/)
----
No building, just packaging:
```
12ea68bfef0377ccedc1a7c98a05ea76907decbcf1e1ec858a60a7b9b73211bb  kubeadm_1.28.0-00_amd64/usr/bin/kubeadm
12ea68bfef0377ccedc1a7c98a05ea76907decbcf1e1ec858a60a7b9b73211bb  kubeadm_1.28.0-1.1_amd64/usr/bin/kubeadm
```
https://dl.k8s.io/v1.28.0/bin/linux/amd64/kubeadm.sha256
=> Use pkgs.k8s.io instead of apt.k8s.io for k8s

cmd/limactl/delete.go, cmd/limactl/start.go, pkg/driver/driver.go, pkg/hostagent/hostagent.go, pkg/start/start.go, pkg/stop/stop.go
Addresses comment on https://github.com/lima-vm/lima/pull/1721#discussion_r1286619203 regarding reusing the Register/Unregister interface for both the new VBox and WSL2 drivers.
Refactored the implementation out of @afbjorklund's PR https://github.com/lima-vm/lima/pull/1277. I didn't see a call to `Register`, so I just added it before `Start` in the `pkg/hostagent`. Also added a nil instantiation of the `BaseDriver` in `pkg/driver` to help with typechecking/noticing if there are unimplemented members of the interface (can remove).
Added @afbjorklund as a co-author since I mostly just refactored. Let me know if that makes sense to you, happy to change it.
=> feat: add Register/Unregister to Driver interface

cmd/limactl/usernet.go, examples/experimental/net-user-v2.yaml, go.mod, hack/test-templates.sh, pkg/cidata/cidata.TEMPLATE.d/boot/09-host-dns-setup.sh, pkg/cidata/cidata.go, pkg/cidata/cidata_test.go, pkg/hostagent/hostagent.go, pkg/networks/config_test.go, pkg/networks/const.go, pkg/networks/networks.TEMPLATE.yaml, pkg/networks/usernet/client.go, pkg/networks/usernet/config.go, pkg/networks/usernet/config_test.go, pkg/networks/usernet/dnshosts/dnshosts.go, pkg/networks/usernet/dnshosts/dnshosts_test.go, pkg/networks/usernet/gvproxy.go, pkg/networks/usernet/recoincile.go, pkg/qemu/qemu_driver.go, pkg/vz/vm_darwin.go
Fixes #1551 #1333 
Keep the PR as draft for the following to be resolved
- https://github.com/containers/gvisor-tap-vsock/pull/236
- https://github.com/containers/gvisor-tap-vsock/issues/233
**What's done**
The user-v2 now honours gateway and netmask properties.
```
networks:
user-v2:
mode: user-v2
gateway: 192.168.109.1
netmask: 255.255.255.0
```
With the support of configurable subnet, we also required to provided support for dynamic DNS for user-v2
**Changes to DNS resolving for usernet**
_Before_
VM <-> gvisor-tap-vsock <-> hostagent dns resolver
_Now_
VM <-> gvisor-tap-vsock
No UDP or TCP forwarding will happen. So DNS lookup's will be faster now
**How to enable new way of DNS resolver ?**
Disabling the hostResolver will enable this new DNS for vz driver and for user-v2 network.
``` …
```
=> Support for configurable network address for user-v2

pkg/vz/vz_driver_darwin.go
Fix #1768 by:
1. add `"OS"` to the know list since #1735 introduced this field. 
2. make the log message more clear: `Ignoring: vmType vz: [...]` -> `Ignoring following configuration due to the use of vmType vz: [...]`
=> Avoid warning about OS with vz driver

website/content/en/docs/Usage/_index.md
`Lima may have bugs that result in loss of data` sounds too scary for the current version of Lima.
It is still true that Lima, as well as any software, may have such bugs, but it does no longer need to be particularly documented here.
In Lima v0.14.0, we had a regression (issue #1242, fixed in v0.14.1) that accidentally leaved `/var/lib/docker` in Colima instances unmounted, but the actualy data were not lost, and could be easily recovered by downgrading or upgrading Lima to other versions.
=> docs: Usage: remove scaring caution

website/content/en/docs/faq/_index.md
Remove "Their EULA even prohibits disclosure of benchmarking result", as the following clause no longer seems to exist:
> 3. RESTRICTED ACTIVITIES
> You shall not, and shall not encourage any third party to:
> ...
> (g) disclose the results of any benchmark tests on the Licensed
> Software without Docker’s prior written consent;
> ...
(From <https://web.archive.org/web/20230222093254/https://www.docker.com/legal/docker-software-end-user-license-agreement/>)
The comparison with Moby was outdated too since Moby v24, which experimentally supports the containerd-snapshotter mode.
=> docs: faq: remove outdated comparison with Docker for Mac

cmd/limactl/show_ssh.go, docs/deprecated.md, website/content/en/docs/Usage/_index.md
`limactl show-ssh` is now deprecated.
Instead, use `ssh -F ~/.lima/default/ssh.config lima-default` .
=> limactl: deprecate `limactl show-ssh` (Use `ssh -F ...` instead)

pkg/sshutil/sshutil.go, pkg/wsl2/lima-init.TEMPLATE
Without this change, Lima can't be used to create a VM in a path that contains a space. For example, if the InstanceDir is `C:\Users\My Name\.lima\data\`, all VM creations would fail.
Tested on a Windows machine.
=> fix: windows directory path containing spaces

cmd/apptainer.lima, cmd/docker.lima, cmd/kubectl.lima, cmd/podman.lima
Now that lima doesn't start the instances by default after creation, we need to suggest the user to do so.
----
```console
$ docker.lima version
instance "docker" does not exist, run `limactl create --name=docker template://docker` to create a new instance
$ limactl create --name=docker template://docker
? Creating an instance "docker" Proceed with the current configuration
INFO[0000] Attempting to download the image              arch=x86_64 digest="sha256:d5b419272e01cd69bfc15cbbbc5700d2196242478a54b9f19746da3a1269b7c8" location="https://cloud-images.ubuntu.com/releases/22.04/release-20230729/ubuntu-22.04-server-cloudimg-amd64.img"
INFO[0001] Using cache "/home/anders/.cache/lima/download/by-url-sha256/625afb7f7a4fbe30a232043af243cca76e06866624604da5ba5ec130d56c4244/data" 
INFO[0001] Run …
```
=> Prompt the user to also start the created instance

pkg/cidata/cidata.go
Setting proxy variables to the empty string doesn't make sense, so just remove them completely. This allows the user to set `http_proxy` and friends to the empty string, either in lima.yaml or in the process environment before running `limactl start`.
Fixes #1829
=> Ignore system proxy settings by overriding with empty string

website/data/adoptors.yaml, website/static/images/users/podman-desktop.svg
Logo previously only included the logomark and not the logotype. This version includes the logotype so the name of the app is apparent.
=> fix: adding full Podman Desktop logo

.github/workflows/release.yml
Use an old release of Ubuntu for better glibc compatibility
=> CI: release: use ubuntu-20.04 for Linux binaries

pkg/guestagent/guestagent_linux.go
WSL2 just put out a new pre-release version (version 2.0.1 at the time of writing). While testing Lima with the new version, I noticed that AUDIT is enabled in the kernel:
```
Linux EC2AMAZ-3QHKPN9 5.15.123.1-microsoft-standard-WSL2 #1 SMP Mon Aug 7 19:01:48 UTC 2023 x86_64 GNU/Linux
CONFIG_AUDIT=y
CONFIG_HAVE_ARCH_AUDITSYSCALL=y
CONFIG_AUDITSYSCALL=y
CONFIG_AUDIT_ARCH=y
```
and `cap_audit_read`/`cap_audit_write` are set:
```
CapInh: 0000000000000000
CapPrm: 000001ffffffffff
CapEff: 000001ffffffffff
CapBnd: 000001ffffffffff
CapAmb: 0000000000000000
0x000001ffffffffff=cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,ca …
```
=> fix: guestagent audit detection and fallback

cmd/limactl/editflags/editflags.go, website/content/en/docs/Releases/Experimental/_index.md
The following flags are no longer marked as experimental:
- `limactl (create|start|edit) --set=<YQ EXPRESSION>`
- `limactl (create|start|edit) --network=<NETWORK>`
- `limactl (create|start|edit) --video=<BOOL>`
=> limactl: move `--set`, `--network`, and `--video` out of experimental

README.ja.md
This PR includes:
- Translated README.ja.md based on up-to-date English README.md (commit: 6938ae5f)
I thought that it is better not to translate the files under the `docs` directory (to keep the translation always up-to-date takes resources and leaving documentation outdated would possibly cause users' confusion), so those docs are not currently translated.
---
Signed-off-by: KOSHIKAWA Kenichi <reishoku.misc@pm.me>
=> docs: Update Japanese translation of README.ja.md

pkg/sshutil/sshutil.go
I thought I fixed this issue in #1825, but I must have tested it incorrectly, as the issue was still occurring in my latest test
Before:
```
{"level":"info","msg":"Waiting for the essential requirement 1 of 3: \"ssh\"","time":"2023-09-29T18:46:02Z"}
{"level":"debug","msg":"executing script \"ssh\"","time":"2023-09-29T18:46:02Z"}
{"level":"debug","msg":"executing ssh for script \"ssh\": C:\\Program Files\\Git\\usr\\bin\\ssh.exe [ssh -F /dev/null -o IdentityFile=\"C:/Users/Administrator/Code/finch space/_output/lima/data/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o …
```
=> fix: Windows ssh command quoting

pkg/networks/sudoers.go
=> limactl sudoers: remove bogus user-v2 entries

website/content/en/docs/Config/Network/_index.md, website/content/en/docs/faq/_index.md
It is reported that the following commands fix the issue #1259:
```
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /usr/libexec/bootpd
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblock /usr/libexec/bootpd
```
=> docs: socketfilterfw needs sudo

pkg/wsl2/wsl_driver_windows.go, website/content/en/docs/Config/Mount/_index.md, website/content/en/docs/Config/VMType/_index.md
Temporarily remove the wsl2 docs, as the wsl2 driver does not seem to work. See PR #1826 for a failed attempt to get it work.
=> wsl2: temporarily remove docs

examples/k8s.yaml
When using user-v2 networks instead of slirp, the address is no longer static but dynamic.
Fortunately, we don't need to know the previous address in order to replace it with localhost...
```diff
-    server: https://192.168.5.15:6443
+    server: https://127.0.0.1:6443
```
So just remove the usage of this variable, from the k8s template.
=> k8s: Stop using LIMA_CIDATA_SLIRP_IP_ADDRESS

cmd/limactl/edit.go, cmd/limactl/main.go, cmd/limactl/start.go, hack/test-port-forwarding.pl, hack/test-templates.sh
`limactl start --tty=false` can be now `limactl --tty=false start` .
The previous form continues to work too.
Fix #1861
=> limactl: make `--tty` to be a global flag

pkg/downloader/downloader.go, pkg/downloader/downloader_test.go, pkg/fileutils/download.go, pkg/start/start.go
The nerdctl(-full) archive has already been downloaded to the cache (during `create`),
so don't log downloading it again (during `start`) - unless file is missing or digest fails.
Don't use files for different arch, or check for local files that are not available in the cache.
Refactor common methods out from the longer functions, so that they can be reused.
Closes #1875
Edit: it wasn't _actually_ downloading the file again, just spamming the INFO log about it
=> Don't download files that are already cached

pkg/cidata/cidata.TEMPLATE.d/boot/08-shell-prompt.sh
This makes it more legible with light backgrounds, and changes the fallback color from "light green" back to regular "green".
The previous "lime" color had issues on light background, where "lime green" works on dark backgrounds and OK on light backgrounds.
Closes #485
Issue #1892
=> Change prompt color from lime to lime green

.github/workflows/release.yml
=> Follow-up to "release.yml: migrate from `hub` to `gh`"

.github/workflows/test.yml, examples/experimental/wsl2.yaml, pkg/store/instance_windows.go, pkg/wsl2/lima-init.TEMPLATE, pkg/wsl2/vm_windows.go
Picking up where #1826 left off
According to [these docs](https://github.com/actions/runner-images/blob/win22/20230903.2/images/win/Windows2022-Readme.md), Windows runners should have Git for Windows pre-installed, meaning `tar.exe` and `gzip.exe` should be in the path already.
Let's see if just changing the rootfs from zstd to gz compression gets us any further, and iterate from there.
Closes #1781.
=> ci: add WSL2 CI

examples/README.md, examples/experimental/vnc.yaml
Set automatic login using a simple login manager (slim), and basic xorg programs including xterm and openbox wm.
Add a panel and some programs for the applications menu, use tint2 instead of the removed fbpanel and basic apps.
Also works with https://novnc.com/
And with  [lima-gui ](https://github.com/afbjorklund/lima-gui) "Display" button
----
* https://github.com/lima-vm/lima/discussions/1002
* https://github.com/lima-vm/lima/pull/1899
=> Add vnc example with xorg desktop environment

pkg/downloader/downloader_test.go, pkg/networks/usernet/gvproxy_test.go
This PR fixes `TestDownloadLocal` and `TestSearchDomain` on Windows. The problem is missed `f.Close()` call.
=> pkg/downloader,pkg/network: fix tests on Windows

.golangci.yml, cmd/limactl/edit.go, pkg/osutil/osutil_linux.go, pkg/osutil/osutil_others.go, pkg/osutil/osutil_windows.go, pkg/osutil/user.go
This PR modifies golangci-lint's config and enables few useful linters: `bodyclose`, `nolintlint`, `gosimple`. And fixes appeared lint issues:
```
cmd/limactl/edit.go:88:5: S1004: should use bytes.Equal(yBytes, yContent) instead (gosimple)
if bytes.Compare(yBytes, yContent) == 0 {
^
pkg/osutil/user.go:21:15: directive `//nolint:revive` is unused for linter "revive" (nolintlint)
Gid   uint32 //nolint:revive
^
pkg/osutil/user.go:27:14: directive `//nolint:revive` is unused for linter "revive" (nolintlint)
Gid  uint32 //nolint:revive
^
```
=> .golangci.yml: enable and fix nolintlint, bodyclose, gosimple

pkg/cidata/cidata_test.go, pkg/networks/config_test.go, pkg/networks/usernet/config_test.go, pkg/networks/usernet/gvproxy_test.go
This PR refactors tests by replacing `if err != nil` with `assert.NilError(t, err)`.
=> test: refactor asserts

examples/default.yaml, website/content/en/docs/Config/Network/_index.md
Update the doc according to: https://github.com/lima-vm/lima/blob/73200003a79cfe829caa2ee9cce7c68c99e33bcb/pkg/limayaml/limayaml.go#L37
=> docs: replace deprecated `useHostResolver` with new `hostResolver.enabled`

.github/workflows/test.yml, hack/test-selinux.sh, hack/test-templates.sh, pkg/cidata/cidata.TEMPLATE.d/boot/05-lima-mounts.sh
Fixes #1882
Signed-off-by: T K Chandra Hasan <t.k.chandra.hasan@ibm.com>
The approach taken here is, once the mounts are created using the parameters in user-data, we would be unmounting the existing mounts and remounting with secontext options for selinux enabled distros. It would update the /etc/fstab file also. The context type we have taken here is container_file_t, as it would be easier to mount those directories inside the container.
=> Set secontext for bind volumes in selinux enabled distros

.github/workflows/test.yml, hack/test-upgrade.sh
v0.10.0 (Apr 25, 2022) is too old to test upgradability. Bump up to v0.15.1 (Apr 16, 2023).
- https://github.com/lima-vm/lima/releases/tag/v0.10.0
- https://github.com/lima-vm/lima/releases/tag/v0.15.1
=> CI: upgrade test: bump up the old Lima (v0.10.0→v0.15.1)

.golangci.yml, pkg/osutil/osutil_linux.go, pkg/osutil/osutil_others.go, pkg/osutil/osutil_windows.go, pkg/osutil/user.go, pkg/osutil/user_test.go
This PR refactors the function `osutil.LimaUser` and `osutil.LimaGroup`:
- compile three regexps only once;
- replace `.Match([]byte(...` with `.MatchString(...`;
- remove duplicated regexp for matching username;
- replace regexp for matching uid/gid with the new function `parseUidGid`;
- replace `strconv.ParseUint` with `parseUidGid`;
- add function for converting `uid/gid` to string.
=> pkg/osutil: refactor LimaUser and LimaGroup functions

examples/README.md, examples/experimental/gentoo.yaml
Requested by user:
* #1934
Not sure what you would actually _use_ it for, it doesn't support systemd with the openstack image.
And you would have to build sshfs and containerd from source, including all their dependencies...
----
https://wiki.gentoo.org/wiki/Handbook:AMD64
```console
$ sudo -Ss
```
> The arm and arm64 architectures are supported by the Gentoo project but do not yet have Handbooks at their disposal due to too many variations in SoCs. It is simply not practical for the Handbook project to maintain a cohesive set of installation instructions.
> Equally, the riscv architecture is supported, however there is no separate Handbook for it (yet)
```yaml
arch: "armv7l"
arch: "aarch64"
arch: "riscv64"
```
=> Add Gentoo as an experimental distribution

pkg/guestagent/api/client/client_others.go, pkg/guestagent/api/client/client_windows.go, pkg/hostagent/port_others.go, pkg/hostagent/port_windows.go, pkg/httpclientutil/httpclientutil_others.go, pkg/httpclientutil/httpclientutil_windows.go, pkg/lockutil/lockutil_unix.go, pkg/osutil/dns_others.go, pkg/osutil/osutil_others.go, pkg/osutil/rosetta_others.go, pkg/start/ha_cmd_opts_others.go, pkg/store/instance_unix.go, pkg/vz/errors_darwin.go, pkg/vz/network_darwin.go, pkg/vz/rosetta_directory_share.go, pkg/vz/rosetta_directory_share_arm64.go, pkg/vz/vm_darwin.go, pkg/vz/vz_driver_darwin.go, pkg/vz/vz_driver_others.go, pkg/windows/process_windows.go, pkg/windows/registry_windows.go, pkg/windows/wsl_util_windows.go, pkg/wsl2/vm_windows.go, pkg/wsl2/wsl_driver_others.go, pkg/wsl2/wsl_driver_windows.go
This PR removes outdated `// +build` comments because the minimum supported version is Go 20. This achieved by running the command:
```
go fix -fix buildtag ./...
```
=> pkg: remove outdated or unnecessary build tags

cmd/limactl/factory-reset.go, pkg/driver/driver.go, pkg/osutil/osversion_darwin.go, pkg/osutil/osversion_others.go, pkg/qemu/qemu.go, pkg/start/start.go, pkg/vz/vz_driver_darwin.go
Split from:
- https://github.com/lima-vm/lima/pull/1951
=> vz: trivial changes

pkg/hostagent/dns/dns_test.go
This PR fixes the panic in `TestDNSRecords`. This happened during the [run](https://github.com/lima-vm/lima/actions/runs/6695532634/job/18191314455?pr=1970#step:7:2480):
```
=== RUN   TestDNSRecords
dns_test.go:39: 
--- FAIL: TestDNSRecords (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x62a833]
goroutine 6 [running]:
testing.tRunner.func1.2({0x67cee0, 0x913da0})
C:/hostedtoolcache/windows/go/1.21.3/x64/src/testing/testing.go:1545 +0x238
testing.tRunner.func1()
C:/hostedtoolcache/windows/go/1.21.3/x64/src/testing/testing.go:1548 +0x397
panic({0x67cee0?, 0x913da0?})
C:/hostedtoolcache/windows/go/1.21.3/x64/src/runtime/panic.go:914 …
```
=> hostagent/dns: fix panic in TestDNSRecords on Windows

go.mod, go.sum, pkg/cidata/cidata_test.go, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/ptr/ptr.go, pkg/ptr/ptr_test.go
This PR removes `github.com/xorcare/pointer` dependency. It's not worth to import the whole package for the one function. With generics we can write it in one line:
```go
func Of[T any](value T) *T {
return &value
}
```
=> pkg/limayaml: replace github.com/xorcare/pointer with ptr

.golangci.yml, pkg/hostagent/dns/dns.go, pkg/textutil/textutil.go
This PR enables `dupword` and fixes the following lint issues:
```sh
pkg/hostagent/dns/dns.go:71:16: Duplicate words (the) found (dupword)
logrus.Tracef("newStaticClientConfig creating config for the the following IPs: %v", ips)
^
pkg/textutil/textutil.go:80:26: Duplicate words (at) found (dupword)
return "", errors.New("function takes at at least one string argument")
^
pkg/textutil/textutil.go:100:26: Duplicate words (at) found (dupword)
return "", errors.New("function takes at at least one string argument")
^
```
=> textutil,dns: enable and fix dupword lint issues

examples/k8s.yaml
Wait for flannel and coredns to be fully deployed, before announcing the cluster "ready"...
We don't need to do this for k3s, since there it is more integrated (and starts up faster too)
```
NAMESPACE      NAME                               READY   STATUS     RESTARTS   AGE   IP             NODE       NOMINATED NODE   READINESS GATES
kube-flannel   kube-flannel-ds-9szh5              0/1     Init:0/2   0          4s    192.168.5.15   lima-k8s   <none>           <none>
kube-system    coredns-5dd5756b68-pxl27           0/1     Pending    0          3s    <none>         <none>     <none>           <none>
kube-system    coredns-5dd5756b68-tzx9t           0/1     Pending    0          3s    <none>         <none>     <none>           <none>
kube-system    etcd-lima-k8s                      1/1 …
```
=> k8s: wait for coredns deployment to be available

.golangci.yml, cmd/limactl/disk.go, cmd/limactl/gendoc.go, pkg/guestagent/kubernetesservice/kubernetesservice.go, pkg/guestagent/kubernetesservice/kubernetesservice_test.go, pkg/qemu/qemu_driver.go, pkg/start/start.go, pkg/store/instance_test.go, pkg/vz/vm_darwin.go
This PR adds `errcheck` to `golangci-lint` config. `errcheck` is useful for detecting code paths when a developer forgets to check for an `err`.
Also, fixes the following lint issues:
```sh
pkg/store/instance_test.go:68:16: Error return value is not checked (errcheck)
PrintInstances(&buf, instances, "table", nil)
^
pkg/store/instance_test.go:77:16: Error return value is not checked (errcheck)
PrintInstances(&buf, instances, "table", nil)
^
pkg/store/instance_test.go:88:16: Error return value is not checked (errcheck)
PrintInstances(&buf, instances, "table", nil)
^
pkg/store/instance_test.go:96:16: Error return value is not checked (errcheck)
PrintInstances(&buf, instances, "table", &options)
^
pkg/store/instance_test.go:104:16: Error return value is not checked …
```
=> Enable errcheck linter; fix lint issues

pkg/start/start.go
So just skip the check for missing entitlements on older macOS versions.
macOS 11 (Big Sur) is probably going to be end-of-lifed soon, but there is no reason not to add a simple affordance to keep Lima working, even if we no longer officially support the OS versions.
Fixes #1975
=> `codesign --xml` requires macOS Monterey or later

website/hugo.toml
This PR fixes #1914 .
It needs to specify `github_subdir` parameter. ([Doc](https://www.docsy.dev/docs/adding-content/repository-links/#github_subdir-optional))
=> Fix website github links

.github/workflows/test.yml, ROADMAP.md, hack/test-port-forwarding.pl, website/hugo.toml
This PR renames `Github` to `GitHub` (see this [page](https://github.com/logos)).
=> docs: fix typo in 'GitHub'

cmd/limactl/start.go
Currently, when creating a new instance, the instance name specified by the user via `--name` gets discarded when a template is chosen later; the template name is used instead:
```console
$ ./_output/bin/limactl create --name test
? Creating an instance "test" Choose another template (docker, podman, archlinux, fedora, ...)
? Choose a template ubuntu-lts
? Creating an instance "ubuntu-lts" Proceed with the current configuration
[output truncated...]
INFO[0005] Run `limactl start ubuntu-lts` to start the instance.
```
Fix that by only setting the instance name to the template name when it's not already set. After this change:
```console
$ ./_output/bin/limactl create --name test
? Creating an instance "test" Choose another template (docker, podman, archlinux, fedora, ...)
? Choose a …
```
=> limactl create: don't override user-specified name

examples/fedora.yaml, examples/podman-rootful.yaml, examples/podman.yaml
Update `fedora`, `podman`, and `podman-rootful` templates to use Fedora 39.
=> templates: update Fedora to 39

cmd/lima-guestagent/daemon_linux.go, cmd/limactl/copy.go, cmd/limactl/shell.go
This PR removes unnecessary global variables in `cmd` packages.
=> limactl,guestagent: Remove global variables

pkg/hostagent/hostagent.go, pkg/hostagent/hostagent_unix.go, pkg/hostagent/hostagent_windows.go
Default nofile limit in the standard terminal in macOS is 256. You can see it with `ulimit -n`.
So when I tried to open over 240 connections to 127.0.0.1, the ssh process crashed. 
Default limit is too low for a vm that can run many applications. 
I suggest to use the same approach as in golang - setting an increased limit for the lima needs.
PR relates on all types of networks, but only for the macOS.
I understand that users can increase the limit themselves using `ulimit -n <N>`. But the regular user expects to get a working environment without exploring such low-level features.
=> hostagent: increase nofile limit

examples/README.md, examples/experimental/u7s.yaml
Will run Kubernetes in rootless docker, a.k.a. "usernetes".
* https://github.com/rootless-containers/usernetes
* https://rootlesscontaine.rs/getting-started/docker
Add certificate for localhost so we can use it from the host.
Note: This is running kubernetes-in-docker ([kind](https://kind.sigs.k8s.io/))
Currently: `FROM docker.io/kindest/node:v1.28.0`
```
NAME           STATUS   ROLES           AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION      CONTAINER-RUNTIME
u7s-lima-u7s   Ready    control-plane   15m   v1.28.0   192.168.5.15   <none>        Debian GNU/Linux 11 (bullseye)   5.15.0-86-generic   containerd://1.7.1
```
----
```
CONTAINER ID   IMAGE            COMMAND                  CREATED          STATUS          PORTS …
```
=> Add usernetes with docker example

examples/rocky-8.yaml, examples/rocky-9.yaml
Update Rocky Linux templates to point at the recently updated images and provides fallback to unversioned image which should always be the most recent image available.
=> templates: Update Rocky Linux to 8.9 and 9.3

pkg/qemu/qemu.go
Lima does not start in qemu 6.2.0_1. Problem with USB forwarding to a virtual machine.
Logs:
```
time="2023-11-22T14:33:50+03:00" level=info msg="Terminal is not available, proceeding without opening an editor"
time="2023-11-22T14:33:50+03:00" level=debug msg="Evaluating yq expression: \"\""
time="2023-11-22T14:33:50+03:00" level=debug msg="Make sure \"user-v2\" network is running"
time="2023-11-22T14:33:50+03:00" level=debug msg="Make sure usernet network is started"
time="2023-11-22T14:33:50+03:00" level=debug msg="Starting usernet network: [limactl usernet -p <some-user>.lima/_networks/user-v2/usernet_user-v2.pid -e <some-user>.lima/_networks/user-v2/user-v2_ep.sock --listen-qemu <some-user>.lima/_networks/user-v2/user-v2_qemu.sock --listen …
```
=> fix usb-bus for qemu 6

.github/workflows/test.yml, pkg/hostagent/hostagent.go, pkg/hostagent/requirements.go
=> hostagent: avoid requiring `fuser` and `ss` in the guest ; CI: update colima (v0.5.5→v0.6.5)

pkg/vz/vm_darwin.go
Switch away from `DiskImageCachingModeAutomatic` to `DiskImageCachingModeCached`, as this is rumored to fix disk corruption on ARM
- https://github.com/utmapp/UTM/issues/4840#issuecomment-1824340975
- https://github.com/utmapp/UTM/issues/4840#issuecomment-1824542732
Expected to fix issue #1957 (for vz)
=> vz: use DiskImageCachingModeCached (rumored to fix disk corruption on ARM)

pkg/cidata/cidata.TEMPLATE.d/boot/04-persistent-data-volume.sh, pkg/cidata/cidata.TEMPLATE.d/boot/50-alpine-fix.sh
Otherwise it always reverts back to the first-boot settings once 04-persistent-data-volume.sh is done, and any further restarts of the networking service will revert to the old interfaces.
This problem was exposed by #1898. There are probably additional settings that might change `/etc` files on a reboot and need to be persisted, but I wanted to keep this PR small.
Similarly `/etc/resolv.conf` is generated by `udhcpc` (via `ifup`), but reverts back to the first-boot version after the bind-mount of the persistent data volume.
Restarting the networking service was just an expensive and indirect way to update `/etc/resolv.conf` by re-running `udhcpc` again.
Fixes https://github.com/rancher-sandbox/rancher-desktop/issues/6051
=> Update /mnt/data/etc/network/interfaces on each boot

pkg/vz/vz_driver_darwin.go, pkg/wsl2/wsl_driver_windows.go
This PR fixes #1932 .
`CopyToHost` is added in #1301 .
=> Register CopyToHost as a known property

pkg/limayaml/defaults.go
https://github.com/containerd/nerdctl/releases/tag/v1.7.0
https://github.com/containerd/nerdctl/releases/tag/v1.7.1
=> nerdctl: update to v1.7.1

cmd/limactl/disk.go, hack/test-templates.sh, pkg/cidata/cidata.TEMPLATE.d/boot/05-lima-disks.sh, pkg/qemu/qemu.go, pkg/store/disk.go
The size of the created disk cannot be changed now. Even if the user resizes the disk using `qemu-img resize` he needs to run some commands in VM to grow the partition and resize the FS.
I added command `limactl disk resize` which can resize disk of a stopped vm using qemu-img.
Also I added parsing a format of an existing disk and render it in `limactl ls`
In cidata was added commands to resize the partition and the FS across all attached disks.
Shrinking of a disk is a danger operation, so i explicitly disallow it
=> Disk resize command

pkg/cidata/cidata.TEMPLATE.d/boot/25-guestagent-base.sh
This is just the usual logging boilerplate used with supervise-daemon.
Should help with debugging #2064.
=> Add lima-guestagent logging for Alpine

.golangci.yml, cmd/limactl/gendoc.go, pkg/cidata/cidata.go, pkg/downloader/downloader.go, pkg/executil/command.go, pkg/guestagent/guestagent_linux.go, pkg/guestagent/procnettcp/procnettcp_linux.go, pkg/hostagent/hostagent.go, pkg/hostagent/mount.go, pkg/hostagent/port.go, pkg/hostagent/port_darwin.go, pkg/hostagent/port_others.go, pkg/hostagent/port_windows.go, pkg/httpclientutil/httpclientutil.go, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/networks/commands.go, pkg/networks/config.go, pkg/networks/usernet/config.go, pkg/networks/usernet/dnshosts/dnshosts_test.go, pkg/networks/usernet/gvproxy_test.go, pkg/qemu/entitlementutil/entitlementutil.go, pkg/qemu/imgutil/imgutil.go, pkg/qemu/qemu.go, pkg/sshutil/sshutil.go, pkg/store/disk.go, pkg/textutil/textutil.go, pkg/vz/vm_darwin.go
This PR enables `gocritic` linter. Also, fixes or disables `gocritic` issues.
The full log of running `golangci-lint`:
```sh
pkg/qemu/entitlementutil/entitlementutil.go:52:14: preferStringWriter: ent.WriteString(entXML) should be preferred to the ent.Write([]byte(entXML)) (gocritic)
if _, err = ent.Write([]byte(entXML)); err != nil {
^
pkg/qemu/entitlementutil/entitlementutil.go:65:1: whyNoLint: include an explanation for nolint directive (gocritic)
// isColimaWrapper__useThisFunctionOnlyForPrintingHints returns true
^
pkg/executil/command.go:19:18: ptrToRefParam: consider `ctx' to be of non-pointer type (gocritic)
func WithContext(ctx *context.Context) Opt {
^
pkg/networks/usernet/dnshosts/dnshosts_test.go:209:1: paramTypeCombine: func(i int, j int) bool could be …
```
=> Enable gocritic linter and fix issues

pkg/logrusutil/logrusutil.go, pkg/logrusutil/logrusutil_test.go
This PR refactors the function `logrusutil.PropagateJSON` by removing `goto`, changing fallback `logrus.Info` (which prints to stderr) to `logger.Info`, and adding unit tests.
=> pkg/logrusutil: Fix PropagateJSON to use logger; add tests

.github/workflows/test.yml
=> CI: increase timeout for golangci-lint

examples/default.yaml, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go, pkg/qemu/qemu.go, pkg/store/filenames/filenames.go, pkg/vz/vz_driver_darwin.go, website/content/en/docs/dev/Internals/_index.md
The "Firmware/edk2 20231213" patches <https://lists.gnu.org/archive/html/qemu-devel/2023-12/msg01694.html>
are necessary to boot most aarch64 images (except Debian, which does not use UEFI shim).
The patches are proposed for the QEMU v8.2.0 milestone, but likely to be postponed to v8.2.1.
Until the patches get accepted in the QEMU upstream, Lima fetches the patched
edk2 binary from <https://gitlab.com/kraxel/qemu/-/tags/firmware%2Fedk2-20231213-pull-request>.
=> qemu, aarch64: use EDK2 from "Firmware/edk2 20231213 patches" (needed for QEMU v8.2.0)

pkg/cidata/cidata.TEMPLATE.d/boot.sh
to make it easier to correlate them to entries in ha.std*.log files.
Related to debugging #2064.
Messages look like this:
```
LIMA 2023-12-19T06:56:36+00:00| Executing /mnt/lima-cidata/boot/25-guestagent-base.sh
```
At first I appended them to the end:
```
LIMA| Executing /mnt/lima-cidata/boot/25-guestagent-base.sh at 2023-12-19T06:56:36+00:00
```
but I found that makes them hard to locate in the log file.
=> Add timestamps to LIMA boot.sh messages

examples/default.yaml, pkg/cidata/cidata.TEMPLATE.d/boot/04-persistent-data-volume.sh, pkg/cidata/cidata.TEMPLATE.d/user-data, pkg/cidata/cidata.go, pkg/cidata/template.go, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go
Allow explicit override via lima.yaml.
Fixes #1921 
Replacement for abandoned #1931
=> Set guest timezone from host setting

examples/k3s.yaml
Fix: #2094
```shell
zjz:~$ limactl shell k3s ls -al /etc/rancher/k3s/k3s.yaml
-rw-r--r-- 1 root root 2961 Dec 21 09:01 /etc/rancher/k3s/k3s.yaml
zjz:~$ limactl shell k3s kubectl get ns
NAME              STATUS   AGE
kube-system       Active   346d
default           Active   346d
kube-public       Active   346d
kube-node-lease   Active   346d
```
=> fix limactl shell k3s kubectl command failed

cmd/limactl/edit.go, cmd/limactl/start.go, pkg/qemu/entitlementutil/entitlementutil.go, pkg/uiutil/uiutil.go
This makes it easier to replace the deprecated survey module with another Text User Interface implementation, later on.
* #1881
* https://github.com/AlecAivazis/survey
None of the currently available alternatives is a good replacement, they take over the entire window and add a lot of deps.
* https://github.com/charmbracelet/bubbletea
* https://github.com/rivo/tview
=> Move all usage of survey into an internal pkg

pkg/downloader/downloader_test.go, pkg/downloader/testdata/downloader.txt
The PR changes `TestDownloadRemote` to use a localhost HTTP server to serve the test contents without the Internet.
This resolves one `TODO` item.
=> pkg/downloader: serve test contents with local HTTP server

pkg/windows/registry_windows.go, pkg/wsl2/wsl_driver_windows.go
When how Lima connects to the guest agent was refactored in #1998, https://github.com/mdlayher/vsock was used to support vsock connections on Windows, but the library doesn't support Windows. The following error log is from a WSL Lima instance on v0.19.1:
```
{"error":"dial vsock host(2):994831394: vsock: not implemented on windows","level":"warning","msg":"connection to the guest agent was closed unexpectedlydial vsock host(2):994831394: vsock: not implemented on windows","time":"2024-01-08T19:19:49Z"}
```
The corresponding log from the library is [here](https://github.com/mdlayher/vsock/blob/068aff8a5e29cc13661b0f5a16cc347614c2bc7d/vsock_others.go#L17).
With this change to revert to using [winio's Dial](https://github.com/microsoft/go-winio/blob/bc421d9108ade8ae2f76c8ef3e90cd4ee690e2c0/h …
=> Fix GuestAgentConn vsock support

examples/default.yaml, pkg/limayaml/defaults.go
The LIMA_CIDATA_* variables are not a supported API and can change without warning.
Fixes #2055
=> Do guest template expansion for provisioning scripts

examples/k8s.yaml
Applies change from 0aed87173d47327049d3006dfd1b564e0d17f20e
```
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
Reverts the previous a5427ddca0f87cf60235400feeac514782f57b80
Still need to run `sudo crictl`
=> k8s: stop using sudo kubectl for kubeconfig

pkg/cidata/cidata.TEMPLATE.d/boot/25-guestagent-base.sh, pkg/hostagent/hostagent.go
The serial port sometimes doesn't seem to work: #2064.
The vsock implementation used for VZ doesn't seem to have this problem.
It makes sense to revert to the old mechanism for QEMU until the serialport has been fixed (if possible).
Just commenting out the virtioPort will fall back to the old socket method thanks to #2006.
=> Revert virtserialport back to unix socket for QEMU guest agent communication

pkg/ioutilx/ioutilx.go
The PR fixes a typo in the description for https://pkg.go.dev/github.com/lima-vm/lima/pkg/ioutilx#ReadAtMaximum
=> pkg/ioutilx: fix typo in doc comment

pkg/qemu/qemu.go
Debian Testing/Trixie recently updated the OVMF package which provides UEFI firmware for 64-bit x86 virtual machines.
Due to filename changes, Lima is no longer able to find firmware when starting a VM, resulting in the following error message: 
`{"level":"debug","msg":"firmware candidates = [/home/user/.local/share/qemu/edk2-x86_64-code.fd /usr/share/qemu/edk2-x86_64-code.fd /usr/share/OVMF/OVMF_CODE.fd /usr/share/qemu/ovmf-x86_64-code.bin /usr/share/edk2-ovmf/x64/OVMF_CODE.fd]","time":"2024-01-10T13:14:19+03:00"}`
`{"level":"fatal","msg":"could not find firmware for \"/usr/bin/qemu-system-x86_64\" (hint: try setting firmware.legacyBIOS to true)","time":"2024-01-10T13:14:19+03:00"}`
The change causing this error is as follows:
> /usr/share/OVMF/OVMF_CODE.fd
> to
> …
=> Add new Debian testing/trixie UEFI firmware file

website/content/en/docs/faq/colima/_index.md
There is probably a better way to word this, but since the [v0.6.0](https://github.com/abiosoft/colima/releases/tag/v0.6.0) release of Colima, the default distro is Ubuntu. I would highlight the difference between Colima and Lima, is that Colima uses an opinionated version Ubuntu image with custom bundled software that cannot be [overridden](https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#are-lima-overrides-supported).
=> Update difference between Colima and Lima

cmd/limactl/start.go, pkg/store/filenames/filenames.go, pkg/store/instance.go, pkg/store/instance_test.go, website/content/en/docs/dev/Internals/_index.md
That way future Lima releases can make decisions about default settings based on the Lima version that created the instance instead of the current instance, and settings for existing instances will not change just because the user updated Lima.
This implements the mechanism I described in https://github.com/lima-vm/lima/pull/1953#issuecomment-1784546687. I'm leaving it in draft mode for now because I'm not sure if the `store.MinVersion` function is the right way to use the data; I originally wanted to make it an instance method, but then noticed that most location that would need to call it don't have a copy of the instance.
So this PR probably needs to wait until we have a companion PR that makes use of this new mechanism. Or I could drop the `MinVersion` function for now and leave it …
=> Store Lima version in the instance directory

pkg/qemu/qemu.go
This PR closes #1683 
Sometimes disk is not unlocked while shutdown (for example on macOS restart) and existing link prevents restarting vm without additional commands.
Automatically remove existing link when using with the same vm.
=> Automatically unlock disk if it is already locked to the same instance (after restarting macOS)

examples/alpine.yaml
Also adds support for timezone syncing:
```console
$ ls -l /etc/localtime | sed 's/.*[0-9] //'
/etc/localtime -> /var/db/timezone/zoneinfo/America/Vancouver
$ limactl shell alpine ls -l /etc/localtime | sed 's/.*[0-9] //'
/etc/localtime -> /etc/zoneinfo/America/Vancouver
```
=> Bump to Alpine 3.19

pkg/cidata/cidata.TEMPLATE.d/boot/04-persistent-data-volume.sh
Because we are running from a RAM disk, any packages not installed from the ISO are removed after a reboot. They are still registered in `/etc/apk/world` (which is on `/mnt/data/etc/apk/world`), and the packages themselves are cached on `/mnt/data/apk/cache`, so reinstalling is quick and easy.
This worked fine in my testing (`apk fix` seems to reinstall the software, but not the config files in `/etc`), but I haven't found any documentation that guarantees that the config will not be touched).
=> Reinstall apk packages on reboot

examples/alpine.yaml
This avoids a race condition between mounting `/dev/sr0` to both `/media/cdrom` and `/media/sr0`.
See also https://github.com/lima-vm/lima/pull/2143#issuecomment-1893062016
=> Bump Alpine image to make sure /etc/fstab is empty

cmd/limactl/hostagent.go, pkg/hostagent/hostagent.go, pkg/osutil/osutil_unix.go, pkg/osutil/osutil_windows.go
This PR modifies the hostagent to handle not only the SIGINT (Interrupt) signal, but also the SIGTERM signal. This allows the hostagent to gracefully shut down when it receives a SIGTERM signal, which is a common way to request a process to terminate. This change improves the compatibility with macOS launchd, which uses SIGTERM to stop services.
The following are the steps to set up the Docker instance of Lima to start at login using launchd on macOS:
```bash
limactl start template://docker --vm-type vz --rosetta --network vzNAT --tty=false
limactl stop docker
echo '<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>Label</key>
<string>io.lima-vm.docker</string> …
```
=> hostagent: Handle SIGTERM signal for better compatibility with macOS launchd

cmd/limactl/edit.go, cmd/limactl/start.go, pkg/osutil/osutil_unix.go, pkg/osutil/osutil_windows.go, pkg/start/start.go
This change adds the `--foreground` flag to `limactl start`.
This flag:
- Launches `limactl hostagent` with `syscall.Exec`, which allows `limactl start --foreground` to be used in macOS's `launchd.plist`, making it possible to hide `limactl hostagent`.
- When launched from the terminal, it uses the terminal for standard output and standard error instead of the default `ha.std{out,err}.log` files. In this case, a message indicating that the default log files are not used is written to the log files.
- When launched from something other than the terminal, such as `launchd`, it uses the `ha.std{out,err}.log` files as before.
- Cannot be used on Windows.
The following are the updated steps to set up the Docker instance of Lima to start at login using launchd on macOS:
```bash
limactl create …
```
=> limactl start: add `--foreground` flag

.github/workflows/test.yml
"Larger" runners are no longer required for nested virt with Linux
=> CI: use standard GHA runners

examples/default.yaml, pkg/cidata/cidata.TEMPLATE.d/boot/00-reboot-if-required.sh, pkg/cidata/cidata.TEMPLATE.d/user-data, pkg/cidata/cidata.go, pkg/cidata/template.go, pkg/limayaml/defaults.go, pkg/limayaml/defaults_test.go, pkg/limayaml/limayaml.go
This will run "apt upgrade" or "dnf upgrade" on the first boot, to make sure that all packages are updated to the latest version.
It adds to the initial startup time and to the size of the diffdisk, so it is better to update the basedisk with a newer cloud release.
But it is a good way to make sure that you start your Fedora with the latest and greatest kernel...
It would be possible to extend the feature to be able to install some missing system packages too.
Closes #2129
=> Option to upgrade packages and reboot if necessary

website/content/en/docs/Config/Network/_index.md
With `user-v2` network, an instance's IP address is resolvable from another instance as `lima-<NAME>.internal.`
(e.g., `lima-default.internal.`)
- https://github.com/lima-vm/lima/discussions/2018
=> docs/config/network: mention `lima-<NAME>.internal`

examples/docker-rootful.yaml, examples/experimental/vnc.yaml, examples/k8s.yaml, examples/podman-rootful.yaml, pkg/limayaml/validate.go
Should only be merged once #2121 has been included in a release.
=> Use template variables instead of LIMA_CIDATA_* bash variables

.golangci.yml, cmd/limactl/start.go, pkg/downloader/downloader.go, pkg/downloader/downloader_test.go, pkg/driver/driver.go, pkg/fileutils/download.go, pkg/networks/reconcile/reconcile.go, pkg/networks/usernet/client.go, pkg/networks/usernet/recoincile.go, pkg/qemu/qemu.go, pkg/qemu/qemu_driver.go, pkg/start/start.go, pkg/vz/disk.go, pkg/vz/vm_darwin.go, pkg/vz/vz_driver_darwin.go, pkg/vz/vz_driver_others.go, pkg/wsl2/fs.go, pkg/wsl2/wsl_driver_others.go, pkg/wsl2/wsl_driver_windows.go
This PR enables [`noctx`](https://github.com/sonatard/noctx) linter in golangci-lint's config. The linter requires the usage of HTTP requests with context for cancelation long-running requests.
=> Enable noctx linter and fix up issues

cmd/limactl/disk.go
**User story:**
lima is built from source code. qemu not installed.
The user wants to run some vm with an additional disk:
```
$ limactl disk create --size=1G --format=qcow2 test
INFO[0000] Creating qcow2 disk "test" with size 1GiB
FATA[0000] Failed to create qcow2 disk in "/Users/testuser/.lima/_disks/test"
```
There are no details about qemu-img in the log. Let's assume he guessed the reason and installed the qemu package.
Now any actions with this disk will result in an error.:
```
$ limactl disk create --size=1G --format=qcow2 test
FATA[0000] disk "test" already exists ("/Users/testuser/.lima/_disks/test")
$ limactl disk rm test
WARN[0000] Ignoring non-existent disk "test"
```
Manual removing the directory helps, but it's not user friendly.
**PR:**
- remove created directory if disk …
=> fix state when create disk fails
